extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s has no move — turn passes back!": "%s no tiene jugada — ¡el turno vuelve!",
		"%s wins! %d - %d": "¡Gana %s! %d - %d",
		"%s's turn": "Turno de %s",
		"Avoid the squares right next to an empty corner: they hand the corner to your opponent.": "Evita las casillas junto a una esquina vacía: le regalan la esquina a tu rival.",
		"Back to Hub": "Volver al inicio",
		"Black": "Negras",
		"Black wins": "Victorias de las negras",
		"Corners can never be flipped back — they're the best squares on the board.": "Las esquinas nunca se pueden voltear — son las mejores casillas del tablero.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Have more discs of your colour on the board when it's full.": "Ten más fichas de tu color en el tablero cuando se llene.",
		"Having lots of discs early doesn't matter much. Keep your options open instead.": "Tener muchas fichas al principio no importa tanto. Mejor mantén abiertas tus opciones.",
		"If you can't make a legal move, your turn passes. The game ends when neither player can move.": "Si no puedes hacer un movimiento válido, pasas el turno. El juego termina cuando nadie puede mover.",
		"It's a tie! %d - %d": "¡Empate! %d - %d",
		"Lines can go across, down or diagonally, and one move can flip lines in several directions.": "Las líneas pueden ser horizontales, verticales o diagonales, y una jugada puede voltear líneas en varias direcciones.",
		"Medium": "Medio",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Place a disc so that one or more of your opponent's discs are trapped in a straight line between it and another of yours. Every trapped disc flips to your colour.": "Pon una ficha de modo que una o más fichas rivales queden atrapadas en línea recta entre ella y otra tuya. Cada ficha atrapada pasa a tu color.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Reversi": "Reversi",
		"Tap 🌐 Play Online to play a friend on another phone with a room code.": "Toca 🌐 Jugar en línea para jugar con un amigo en otro teléfono usando un código de sala.",
		"Two players share the phone. Black moves first.": "Dos jugadores comparten el teléfono. Empiezan las negras.",
		"White": "Blancas",
		"White wins": "Victorias de las blancas",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"⚫ Black: %d      ⚪ White: %d": "⚫ Negras: %d      ⚪ Blancas: %d",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
