extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Ask for ranks the computer asked you for earlier — it probably still has them.": "Pide los números que la computadora te pidió antes — seguramente todavía los tiene.",
		"Ask for the rank you hold the most of: you're closest to a book.": "Pide el número del que más cartas tienes: es el que tienes más cerca de un libro.",
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"Books: you %d, computer %d.": "Libros: tú %d, computadora %d.",
		"Collect the most books — sets of all four cards of one rank. You play against the computer.": "Junta la mayor cantidad de libros — las cuatro cartas de un mismo número. Juegas contra la computadora.",
		"Computer asked for %s — go fish!": "La computadora pidió %s — ¡a pescar!",
		"Computer asked for %s — you hand over %d.": "La computadora pidió %s — le das %d.",
		"Computer made a book of %s.": "La computadora completó un libro de %s.",
		"Computer's turn...": "Turno de la computadora...",
		"Computer: %d cards, %d books": "Computadora: %d cartas, %d libros",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Four of a kind make a book. When all 13 books are made, the most books wins.": "Cuatro cartas iguales forman un libro. Cuando se completan los 13 libros, gana quien tenga más.",
		"Go Fish": "Pesca",
		"Go fish! The pond is empty.": "¡A pescar! El mazo está vacío.",
		"Go fish! You drew %s.": "¡A pescar! Robaste %s.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"If it has any, it hands them all over and you ask again.": "Si tiene alguna, te las da todas y vuelves a pedir.",
		"If not, \"go fish\": you draw a card. If it's the rank you asked for, you go again.": "Si no, \"a pescar\": robas una carta. Si es el número que pediste, vuelves a jugar.",
		"It drew one and goes again.": "Robó justo esa y vuelve a jugar.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"New": "Nuevo",
		"On your turn, tap one of your cards to ask the computer for that rank.": "En tu turno, toca una de tus cartas para pedirle ese número a la computadora.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Pond: %d": "Mazo: %d",
		"Remember what you've handed over, so you know which ranks the computer is collecting.": "Recuerda lo que entregaste, así sabes qué números está juntando la computadora.",
		"Tap one of your cards to ask the computer for that rank.": "Toca una de tus cartas para pedirle ese número a la computadora.",
		"That's what you asked for — go again!": "¡Es la que pediste — juega otra vez!",
		"The computer gives you %d × %s!": "¡La computadora te da %d × %s!",
		"Wins": "Victorias",
		"You asked for %s.": "Pediste %s.",
		"You lose!": "¡Perdiste!",
		"You made a book of %s!": "¡Completaste un libro de %s!",
		"You win!": "¡Ganaste!",
		"Your books: %d": "Tus libros: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn — ask for a rank.": "Tu turno — pide un número.",
		"🐟 Go Fish": "🐟 Pesca",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
