extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Books: you %d, computer %d.": "Libros: tú %d, computadora %d.",
		"Computer asked for %s — go fish!": "La computadora pidió %s — ¡a pescar!",
		"Computer asked for %s — you hand over %d.": "La computadora pidió %s — le das %d.",
		"Computer made a book of %s.": "La computadora completó un libro de %s.",
		"Computer's turn...": "Turno de la computadora...",
		"Computer: %d cards, %d books": "Computadora: %d cartas, %d libros",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Go fish! The pond is empty.": "¡A pescar! El mazo está vacío.",
		"Go fish! You drew %s.": "¡A pescar! Robaste %s.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"It drew one and goes again.": "Robó justo esa y vuelve a jugar.",
		"Medium": "Medio",
		"New": "Nuevo",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Pond: %d": "Mazo: %d",
		"Tap one of your cards to ask the computer for that rank.": "Toca una de tus cartas para pedirle ese número a la computadora.",
		"That's what you asked for — go again!": "¡Es la que pediste — juega otra vez!",
		"The computer gives you %d × %s!": "¡La computadora te da %d × %s!",
		"You asked for %s.": "Pediste %s.",
		"You lose!": "¡Perdiste!",
		"You made a book of %s!": "¡Completaste un libro de %s!",
		"You win!": "¡Ganaste!",
		"Your books: %d": "Tus libros: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn — ask for a rank.": "Tu turno — pide un número.",
		"🐟 Go Fish": "🐟 Pesca",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
