extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"%d votes": "%d votos",
		"A party game for any number of people around one phone.": "Un juego de fiesta para cualquier cantidad de personas alrededor de un teléfono.",
		"Argue it out, then tap Next card.": "Discútanlo y luego toquen Siguiente carta.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Both decks": "Ambos mazos",
		"Card %d": "Carta %d",
		"Cards played": "Cartas jugadas",
		"Classic is for everyone; Spicy is for friends and dates; Mixed shuffles both. The cards come in English or Spanish, following the app's language.": "Clásico es para todos; Picante, para amigos y citas; Mezcla combina ambos. Las cartas están en español o inglés, según el idioma de la app.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Dilemmas argued over, all time.": "Dilemas discutidos, en total.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Everyone picks a side. Tap a choice once per person to count the votes and see the split.": "Cada uno elige un lado. Toca una opción una vez por persona para contar los votos y ver el reparto.",
		"Expert": "Experto",
		"For everyone": "Para todos",
		"Friends and dates": "Amigos y citas",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Make it a drinking game: the losing side drinks.": "Conviértelo en juego de tragos: bebe el lado que pierde.",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"Next card ▶": "Siguiente carta ▶",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"No sitting on the fence — \"neither\" isn't an answer.": "Nada de quedarse en medio: \"ninguna\" no es respuesta.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pick a deck": "Elige un mazo",
		"Pick a side on impossible choices — and defend it.": "Elige un lado en decisiones imposibles, y defiéndelo.",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Read the card out loud: \"Would you rather...\" and the two choices.": "Lee la carta en voz alta: \"¿Qué prefieres...\" y las dos opciones.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Tap a side to vote": "Toca un lado para votar",
		"The minority has to explain themselves.": "La minoría tiene que dar explicaciones.",
		"Two choices, no way out. Pick one and defend it.": "Dos opciones, sin escapatoria. Elige una y defiéndela.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"Would You Rather": "¿Qué prefieres?",
		"Would you rather...": "¿Qué prefieres...?",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"— or —": "— o —",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses; Resume on the Home screen keeps your deck and count.": "⏸ pausa; Continuar en la pantalla de inicio conserva tu mazo y la cuenta.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🌶️ Spicy": "🌶️ Picante",
		"🎯 Goal": "🎯 Objetivo",
		"🎲 Mixed": "🎲 Mezcla",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
		"😄 Classic": "😄 Clásico",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
