extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Clear one arm of the cross at a time.": "Limpia un brazo de la cruz a la vez.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fewest pegs left": "Menos fichas restantes",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Games solved": "Partidas resueltas",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Jump a peg over another into an empty hole. Leave just one!": "Salta una ficha sobre otra hasta un hueco vacío. ¡Deja solo una!",
		"Medium": "Medio",
		"New best!": "¡Nuevo récord!",
		"No more jumps. %d pegs left.": "No hay más saltos. Quedan %d fichas.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Peg Solitaire": "Senku",
		"Pegs left: %d": "Fichas: %d",
		"Perfect games": "Partidas perfectas",
		"Perfect! One peg, dead centre.": "¡Perfecto! Una ficha, justo en el centro.",
		"Play Again": "Jugar de nuevo",
		"Remove pegs by jumping over them until only one is left.": "Quita fichas saltando sobre ellas hasta que quede solo una.",
		"Restart": "Reiniciar",
		"Save the centre for last.": "Deja el centro para el final.",
		"Solved!": "¡Resuelto!",
		"Solved! Just one peg left.": "¡Resuelto! Queda una sola ficha.",
		"Tap a peg, then tap an empty hole two spaces away to jump over the peg in between.": "Toca una ficha y luego un hoyo vacío a dos espacios para saltar sobre la ficha del medio.",
		"The game ends when no jumps are left. One peg left is a win; one peg in the very centre is perfect.": "El juego termina cuando no quedan saltos. Dejar una ficha es ganar; dejarla justo en el centro es perfecto.",
		"The peg you jump over is removed. Jumps go up, down, left or right — never diagonally.": "La ficha que saltas se quita. Los saltos van arriba, abajo, a la izquierda o a la derecha — nunca en diagonal.",
		"Work from the outside in, and avoid leaving pegs stranded alone on the arms of the cross.": "Trabaja de afuera hacia adentro, y evita dejar fichas aisladas en los brazos de la cruz.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"↶ Undo takes back your last jump.": "↶ Deshacer anula tu último salto.",
		"📌 Peg Solitaire": "📌 Senku",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
