extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Jump a peg over another into an empty hole. Leave just one!": "Salta una ficha sobre otra hasta un hueco vacío. ¡Deja solo una!",
		"Medium": "Medio",
		"No more jumps. %d pegs left.": "No hay más saltos. Quedan %d fichas.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pegs left: %d": "Fichas: %d",
		"Perfect! One peg, dead centre.": "¡Perfecto! Una ficha, justo en el centro.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Solved! Just one peg left.": "¡Resuelto! Queda una sola ficha.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"📌 Peg Solitaire": "📌 Senku",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
