extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"%s   ·   Moves: %d   ·   %s": "%s   ·   Movimientos: %d   ·   %s",
		"A pink dot marks a wet pipe that leads nowhere — a leak.": "Un punto rosa marca una tubería con agua que no lleva a ningún lado: una fuga.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Best time (Easy)": "Mejor tiempo (Fácil)",
		"Best time (Expert)": "Mejor tiempo (Experto)",
		"Best time (Hard)": "Mejor tiempo (Difícil)",
		"Best time (Medium)": "Mejor tiempo (Medio)",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"End pieces (one opening) can never face each other — that would close off a pair.": "Dos piezas finales (una sola salida) nunca pueden mirarse: cerrarían a la pareja.",
		"Every piece starts turned the wrong way. Tap a piece to turn it a quarter turn clockwise.": "Cada pieza empieza mal girada. Toca una pieza para girarla un cuarto de vuelta en sentido horario.",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New best time!": "¡Nuevo mejor tiempo!",
		"Next puzzle": "Siguiente rompecabezas",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pick a size on the Home screen: Easy 5 × 5 up to Expert 11 × 11. Every board can be solved.": "Elige un tamaño en la pantalla de inicio: de Fácil 5 × 5 a Experto 11 × 11. Todos los tableros tienen solución.",
		"Pieces joined to the gold pump fill with blue water; the rest stay purple.": "Las piezas unidas a la bomba dorada se llenan de agua azul; las demás quedan moradas.",
		"Pipe Flow": "Tuberías",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Puzzles solved at any size.": "Rompecabezas resueltos de cualquier tamaño.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solved in %d moves!": "¡Resuelto en %d movimientos!",
		"Solved!": "¡Resuelto!",
		"Start at the edges and corners: a pipe there can only point inwards.": "Empieza por los bordes y las esquinas: ahí una tubería solo puede apuntar hacia adentro.",
		"Straight pieces have only two useful positions, so they're quick to settle.": "Las piezas rectas solo tienen dos posiciones útiles, así que se resuelven rápido.",
		"Tap a pipe to turn it.": "Toca una tubería para girarla.",
		"The puzzle is solved when every piece is wet and nothing leaks.": "El rompecabezas está resuelto cuando todas las piezas tienen agua y nada gotea.",
		"Time: %s": "Tiempo: %s",
		"Turn the pipes so the water from the pump in the middle reaches every piece, with no open ends.": "Gira las tuberías para que el agua de la bomba del centro llegue a todas las piezas, sin extremos abiertos.",
		"Turn the pipes until the water reaches every one.": "Gira las tuberías hasta que el agua llegue a todas.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock and keeps the board; Resume on the Home screen carries on.": "⏸ pausa el reloj y guarda el tablero; Continuar en la pantalla de inicio sigue la partida.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
		"🚰 Pipe Flow": "🚰 Tuberías",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
