extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Anyone who falls, or touches the mat with a knee or elbow, is out. The last player standing wins.": "Quien se caiga o toque el tapete con una rodilla o un codo queda fuera. Gana el último que quede.",
		"Auto-spin: %ds": "Giro automático: %ds",
		"Auto-spin: off": "Giro automático: no",
		"Back to Hub": "Volver al inicio",
		"Before:": "Antes:",
		"Best score": "Mejor puntaje",
		"Blue": "Azul",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Green": "Verde",
		"Hard": "Difícil",
		"It picks a hand or foot and a colour. That player puts that hand or foot on a circle of that colour.": "Elige una mano o un pie y un color. Ese jugador pone esa mano o pie en un círculo de ese color.",
		"Keep your weight low and centred to stay balanced.": "Mantén el peso bajo y centrado para no perder el equilibrio.",
		"Left foot": "Pie izquierdo",
		"Left hand": "Mano izquierda",
		"Lf": "Pi",
		"Lh": "Mi",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Party Spinner": "Ruleta de fiesta",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Put the phone where everyone can see it.": "Deja el teléfono donde todos lo vean.",
		"Red": "Rojo",
		"Resume": "Continuar",
		"Rf": "Pd",
		"Rh": "Md",
		"Right foot": "Pie derecho",
		"Right hand": "Mano derecha",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Spins": "Giros",
		"Tap the wheel (or 🌀 Spin) to spin it.": "Toca la ruleta (o 🌀 Girar) para hacerla girar.",
		"Tap the wheel to spin!": "¡Toca la ruleta para girar!",
		"The spinner for the body-twisting mat game — no cardboard arrow needed.": "La ruleta para el juego del tapete de contorsiones — sin flecha de cartón.",
		"Turn on auto-spin to spin by itself every few seconds, so nobody has to hold the phone. The last move is shown under Before.": "Activa el giro automático para que gire solo cada pocos segundos, así nadie tiene que sostener el teléfono. La jugada anterior aparece en Antes.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use a mat with rows of red, yellow, green and blue circles.": "Usa un tapete con filas de círculos rojos, amarillos, verdes y azules.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"Yellow": "Amarillo",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌀 Party Spinner": "🌀 Ruleta de fiesta",
		"🌀 Spin": "🌀 Girar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
