extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Auto-spin: %ds": "Giro automático: %ds",
		"Auto-spin: off": "Giro automático: no",
		"Before:": "Antes:",
		"Blue": "Azul",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Green": "Verde",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Left foot": "Pie izquierdo",
		"Left hand": "Mano izquierda",
		"Lf": "Pi",
		"Lh": "Mi",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Red": "Rojo",
		"Rf": "Pd",
		"Rh": "Md",
		"Right foot": "Pie derecho",
		"Right hand": "Mano derecha",
		"Tap the wheel to spin!": "¡Toca la ruleta para girar!",
		"Yellow": "Amarillo",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🌀 Party Spinner": "🌀 Ruleta de fiesta",
		"🌀 Spin": "🌀 Girar",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
