extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"Back to Hub": "Volver al inicio",
		"Best level": "Mejor nivel",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Each round adds one more colour to the end of the sequence.": "Cada ronda agrega un color más al final de la secuencia.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game Over — reached level %d": "Fin del juego — llegaste al nivel %d",
		"Games played": "Partidas jugadas",
		"Group the sequence into chunks of three or four.": "Agrupa la secuencia en bloques de tres o cuatro.",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Level %d": "Nivel %d",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Memory Lights": "Luces de memoria",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"One mistake ends it": "Un error y se acaba",
		"One wrong tap and the game is over. Your level is the longest sequence you repeated.": "Un toque equivocado y se termina el juego. Tu nivel es la secuencia más larga que repetiste.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Repeat the sequence of colours for as long as you can.": "Repite la secuencia de colores todo lo que puedas.",
		"Resume": "Continuar",
		"Say the colours out loud, or give each one a number.": "Di los colores en voz alta o dale un número a cada uno.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start": "Empezar",
		"The longest sequence you've repeated.": "La secuencia más larga que repetiste.",
		"The sequence only ever grows at the end, so you just need to remember one new colour each round.": "La secuencia solo crece al final, así que en cada ronda solo tienes que recordar un color nuevo.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Watch the lights, then repeat the sequence. It grows every round.": "Mira las luces y repite la secuencia. Crece en cada ronda.",
		"Watch the pads light up, then tap them in the same order.": "Mira cómo se encienden los botones y tócalos en el mismo orden.",
		"Watch, then repeat the sequence": "Mira y luego repite la secuencia",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses. A game is quick, so it isn't saved for later.": "⏸ pausa. Una partida es rápida, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"▶  Play": "▶  Jugar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
