extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Falling gems that make new matches are a chain, and chains score extra.": "Las joyas que caen y forman nuevas combinaciones hacen una cadena, y las cadenas dan puntos extra.",
		"Games played": "Partidas jugadas",
		"Gem Match": "Joyas",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Lines of 4 or 5 score a big bonus.": "Las líneas de 4 o 5 dan un gran bono.",
		"Look over the whole board before each move — you only have 30.": "Revisa todo el tablero antes de cada movimiento — solo tienes 30.",
		"Make matches near the bottom: more gems fall, so more chains happen.": "Haz combinaciones cerca de abajo: caen más joyas y se forman más cadenas.",
		"Matched gems clear, the gems above fall down and new ones drop in from the top.": "Las joyas combinadas desaparecen, las de arriba caen y entran nuevas desde arriba.",
		"Medium": "Medio",
		"Only swaps that make a match are allowed, and each one uses a move.": "Solo se permiten los cambios que forman una combinación, y cada uno gasta un movimiento.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of Moves": "Sin movimientos",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Score as many points as you can in 30 moves.": "Suma todos los puntos que puedas en 30 movimientos.",
		"Score: %d": "Puntos: %d",
		"Score: %d   Moves: %d   Best: %d": "Puntos: %d   Movimientos: %d   Récord: %d",
		"Swap two neighbouring gems to line up three or more of the same kind.": "Intercambia dos joyas vecinas para alinear tres o más iguales.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"💎 Gem Match": "💎 Joyas",
		"💡 Hint": "💡 Pista",
		"💡 Hint shows you a swap that works.": "💡 Pista te muestra un intercambio que funciona.",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
