extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"+%ds": "+%ds",
		"4 in a row leaves a 💣 bomb. A bomb is a wild card: line it up with 2 or more alike gems and it explodes, clearing the 3×3 square around it.": "4 en línea dejan una 💣 bomba. La bomba es comodín: alinéala con 2 o más gemas iguales y explota, limpiando el cuadro de 3×3 a su alrededor.",
		"5 in a row clears every gem of that kind from the board.": "5 en línea eliminan todas las gemas de ese tipo del tablero.",
		"Back to Hub": "Volver al inicio",
		"Beat the clock": "Gánale al reloj",
		"Beat the clock! Every match adds time. Match fast for a multiplier, 4 in a row for a bomb, 5 to clear a colour.": "¡Gánale al reloj! Cada combinación suma tiempo. Combina rápido para un multiplicador, 4 en línea para una bomba, 5 para borrar un color.",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Chain ×%d!": "¡Cadena ×%d!",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Gem Match": "Joyas",
		"Gems fall into the gaps and new ones drop in; falls that make new matches are chains and score extra.": "Las gemas caen a los huecos y entran nuevas; las caídas que forman combinaciones nuevas son cadenas y dan puntos extra.",
		"Hard": "Difícil",
		"Keep moving — a fast ×5 is worth much more than one perfect move.": "No te detengas — un ×5 rápido vale mucho más que una jugada perfecta.",
		"Loading...": "Cargando...",
		"Longest chain": "Cadena más larga",
		"Losses": "Derrotas",
		"Make matches near the bottom: more gems fall, so more chains happen.": "Haz combinaciones cerca de abajo: caen más joyas y se forman más cadenas.",
		"Match quickly to build a multiplier (up to ×8) — wait too long between matches and it drops back to ×1.": "Combina rápido para subir el multiplicador (hasta ×8) — si tardas mucho entre combinaciones vuelve a ×1.",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No moves — shuffled!": "¡Sin jugadas — mezclado!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Save a bomb next to a crowded spot, then set it off with a match.": "Deja una bomba junto a un grupo de gemas y luego hazla explotar con una combinación.",
		"Score as many points as you can before the clock runs out.": "Consigue todos los puntos que puedas antes de que se acabe el tiempo.",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start": "Empezar",
		"Swap gems to line up three or more. Race the clock!": "Intercambia joyas para alinear tres o más. ¡Corre contra el reloj!",
		"Swap two neighbouring gems to line up three or more of the same kind.": "Intercambia dos joyas vecinas para alinear tres o más iguales.",
		"Time's up!": "¡Se acabó el tiempo!",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You start with 60 seconds. Every match adds time: 3 in a row +2 s, 4 in a row +4 s, 5 or more +6 s.": "Empiezas con 60 segundos. Cada combinación suma tiempo: 3 en línea +2 s, 4 en línea +4 s, 5 o más +6 s.",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score.": "Tu mejor puntaje.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock. A round is short, so it isn't saved for later.": "⏸ pausa el reloj. Una ronda es corta, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💎  Play": "💎  Jugar",
		"💎 Gem Match": "💎 Joyas",
		"💡 Hint": "💡 Pista",
		"💡 Hint shows you a swap that works.": "💡 Pista te muestra un intercambio que funciona.",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
