extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Continue": "Continuar",
		"Continue (Score %d)": "Continuar (Puntos %d)",
		"Dual-stick neon shooter": "Shooter neón de doble stick",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Geometry Wars": "Geometry Wars",
		"Hard": "Difícil",
		"Lives: %d": "Vidas: %d",
		"Lives: 3": "Vidas: 3",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Rotate your device to landscape": "Gira tu teléfono a horizontal",
		"Score: %d": "Puntos: %d",
		"Score: %d   Time survived: %s": "Puntos: %d   Tiempo sobrevivido: %s",
		"Score: 0": "Puntos: 0",
		"Start": "Empezar",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"x%d Combo": "Combo x%d",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
