extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"After you appear, a glowing halo keeps you safe for 5 seconds. Six quick beeps warn that it is about to fade.": "Cuando apareces, un halo brillante te protege durante 5 segundos. Seis pitidos rápidos avisan que está por desaparecer.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Continue": "Continuar",
		"Continue (Score %d)": "Continuar (Puntos %d)",
		"Dual-stick neon shooter": "Shooter neón de doble stick",
		"Easy": "Fácil",
		"Every kill scores its points times your multiplier.": "Cada enemigo eliminado da sus puntos por tu multiplicador.",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fire at a weaver's wall side to pin it, or get close and shoot a quick burst it can't dodge.": "Dispara al tejedor contra una pared para acorralarlo, o acércate y lanza una ráfaga rápida que no pueda esquivar.",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Geometry Wars": "Geometry Wars",
		"Hard": "Difícil",
		"Highest multiplier": "Multiplicador máximo",
		"Hold the phone sideways. The left stick flies the ship, and it points the way you steer. The right stick aims and fires without turning the ship.": "Sostén el teléfono en horizontal. El stick izquierdo mueve la nave, y esta apunta hacia donde la diriges. El stick derecho apunta y dispara sin girar la nave.",
		"Keep moving in wide circles — standing still gets you surrounded.": "Muévete en círculos amplios — si te quedas quieto te rodean.",
		"Kill grunts early: the older they get, the faster they chase.": "Elimina pronto a los soldados: cuanto más viejos, más rápido te persiguen.",
		"Kills drop tiny yellow crystals called geoms. Fly over one to raise your score multiplier by 1 — they vanish after 3 seconds. Huge orange geoms are worth 10.": "Los enemigos destruidos sueltan pequeños cristales amarillos llamados geoms. Pasa sobre uno para subir tu multiplicador en 1; desaparecen a los 3 segundos. Los geoms naranjas enormes valen 10.",
		"Lives: %d": "Vidas: %d",
		"Lives: 3": "Vidas: 3",
		"Longest time survived": "Mayor tiempo sobrevivido",
		"Medium": "Medio",
		"New best!": "¡Nuevo récord!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Rotate your device to landscape": "Gira tu teléfono a horizontal",
		"Save a bomb for when you're cornered.": "Guarda una bomba para cuando estés acorralado.",
		"Score: %d": "Puntos: %d",
		"Score: %d   Time survived: %s": "Puntos: %d   Tiempo sobrevivido: %s",
		"Score: 0": "Puntos: 0",
		"Snakes can only be killed by hitting the head. Rockets charge in straight lines. Shoot a gravity well to wake it — it sucks in enemies, shots and you. Kill it to blow up everything around it, or let it eat too much and it bursts into protons.": "A las serpientes solo se las destruye golpeando la cabeza. Los cohetes embisten en línea recta. Dispara a un pozo de gravedad para despertarlo: absorbe enemigos, disparos y a ti. Destrúyelo para volar todo lo que lo rodea, o deja que coma demasiado y estallará en protones.",
		"Start": "Empezar",
		"Survive the swarm of neon shapes and score as many points as you can.": "Sobrevive al enjambre de figuras de neón y suma todos los puntos que puedas.",
		"Sweep through geoms after a fight, before they vanish.": "Recoge los geoms después de una pelea, antes de que desaparezcan.",
		"Touching anything costs one of your three lives, clears the screen and resets the multiplier.": "Tocar cualquier cosa te cuesta una de tus tres vidas, limpia la pantalla y reinicia el multiplicador.",
		"Wanderers and neutrons drift and bounce. Blue grunts chase you and get faster the longer they live. Green weavers dodge your shots. Pink spinners split in three. Tiny mayflies swarm in hordes, and one shot pierces many.": "Los vagabundos y neutrones van a la deriva y rebotan. Los soldados azules te persiguen y se vuelven más rápidos cuanto más viven. Los tejedores verdes esquivan tus disparos. Los giradores rosas se dividen en tres. Las diminutas efímeras llegan en enjambres, y un disparo atraviesa a muchas.",
		"You fire bursts of three shots, ten bursts a second. The middle shot is faster and flies farther.": "Disparas ráfagas de tres tiros, diez ráfagas por segundo. El tiro del medio es más rápido y llega más lejos.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"💣 Bomb wipes out every enemy on screen. You start with 3 and earn another every 2,500 points.": "💣 Bomba elimina a todos los enemigos en pantalla. Empiezas con 3 y ganas otra cada 2.500 puntos.",
		"💣 Bomb ×%d": "💣 Bomba ×%d",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
