extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Continue": "Continuar",
		"Continue (Score %d)": "Continuar (Puntos %d)",
		"Crystals drift toward you when you're close; sweep through them after a fight.": "Los cristales se acercan a ti cuando estás cerca; recógelos después de cada pelea.",
		"Dual-stick neon shooter": "Shooter neón de doble stick",
		"Easy": "Fácil",
		"Every kill scores its points times your multiplier.": "Cada enemigo eliminado da sus puntos por tu multiplicador.",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Geometry Wars": "Geometry Wars",
		"Hard": "Difícil",
		"Hold the phone sideways. The left stick moves your ship and the right stick aims and fires.": "Pon el teléfono de costado. El control izquierdo mueve tu nave y el derecho apunta y dispara.",
		"Keep moving in wide circles — standing still gets you surrounded.": "Muévete en círculos amplios — si te quedas quieto te rodean.",
		"Lives: %d": "Vidas: %d",
		"Lives: 3": "Vidas: 3",
		"Longest time survived": "Mayor tiempo sobrevivido",
		"Medium": "Medio",
		"New best!": "¡Nuevo récord!",
		"New enemies join the longer you survive: green weavers dodge your shots, purple pinwheels split in three, yellow darts charge, red hexagons take three hits.": "Aparecen enemigos nuevos mientras más sobrevives: los verdes esquivan tus disparos, los molinetes morados se dividen en tres, los dardos amarillos embisten y los hexágonos rojos aguantan tres golpes.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Rotate your device to landscape": "Gira tu teléfono a horizontal",
		"Save a bomb for when you're cornered.": "Guarda una bomba para cuando estés acorralado.",
		"Score: %d": "Puntos: %d",
		"Score: %d   Time survived: %s": "Puntos: %d   Tiempo sobrevivido: %s",
		"Score: 0": "Puntos: 0",
		"Shot enemies drop green crystals. Fly over one to raise your score multiplier by 1 — they fade after 3 seconds.": "Los enemigos derribados sueltan cristales verdes. Pasa sobre uno para subir tu multiplicador en 1 — desaparecen a los 3 segundos.",
		"Start": "Empezar",
		"Survive the swarm of neon shapes and score as many points as you can.": "Sobrevive al enjambre de figuras de neón y suma todos los puntos que puedas.",
		"Touching an enemy costs one of your three lives, clears the screen and resets the multiplier.": "Tocar un enemigo te cuesta una de tus tres vidas, limpia la pantalla y reinicia el multiplicador.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"💣 Bomb wipes out every enemy on screen. You start with 3 and earn another every 2,500 points.": "💣 Bomba elimina a todos los enemigos en pantalla. Empiezas con 3 y ganas otra cada 2.500 puntos.",
		"💣 Bomb ×%d": "💣 Bomba ×%d",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
