extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"Change one thing at a time so you know what made the difference.": "Cambia una cosa a la vez para saber qué hizo la diferencia.",
		"Check": "Revisar",
		"Code Breaker": "Descifra el código",
		"Crack the 4-colour code in 10 tries.\n● right colour & spot   ○ right colour, wrong spot": "Descifra el código de 4 colores en 10 intentos.\n● color y lugar correctos   ○ color correcto, lugar equivocado",
		"Cracked in %d tries!": "¡Descifrado en %d intentos!",
		"Easy": "Fácil",
		"Every guess should fit everything you've learned so far.": "Cada intento debe encajar con todo lo que ya sabes.",
		"Expert": "Experto",
		"Fewest tries": "Menos intentos",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"New best!": "¡Nuevo récord!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of tries — the code is shown at the top.": "Sin intentos — el código aparece arriba.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Start with guesses like two colours in pairs (red, red, blue, blue) to find which colours are in the code.": "Empieza con intentos de dos colores en pares (rojo, rojo, azul, azul) para descubrir qué colores hay en el código.",
		"Tap colours to fill the four slots, then tap Check. Colours can repeat.": "Toca colores para llenar los cuatro lugares y luego toca Revisar. Los colores pueden repetirse.",
		"The markers don't tell you which peg they belong to — that's the puzzle.": "Las marcas no dicen a qué ficha corresponden — ese es el desafío.",
		"Wins": "Victorias",
		"Work out the secret code of 4 colours in 10 tries or fewer.": "Descubre el código secreto de 4 colores en 10 intentos o menos.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"○ means a peg is the right colour but in the wrong spot.": "○ significa que una ficha es del color correcto pero en el lugar equivocado.",
		"● means a peg is the right colour in the right spot.": "● significa que una ficha es del color correcto en el lugar correcto.",
		"🧠 Code Breaker": "🧠 Descifra el código",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
