extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Check": "Revisar",
		"Crack the 4-colour code in 10 tries.\n● right colour & spot   ○ right colour, wrong spot": "Descifra el código de 4 colores en 10 intentos.\n● color y lugar correctos   ○ color correcto, lugar equivocado",
		"Cracked in %d tries!": "¡Descifrado en %d intentos!",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of tries — the code is shown at the top.": "Sin intentos — el código aparece arriba.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🧠 Code Breaker": "🧠 Descifra el código",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
