extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s wins!\n%s %d - %s %d": "¡Gana %s!\n%s %d - %s %d",
		"%s's turn": "Turno de %s",
		"2 Players": "2 jugadores",
		"Back to Hub": "Volver al inicio",
		"Blue": "Azul",
		"Change Board Size": "Cambiar tamaño del tablero",
		"Choose a board size": "Elige el tamaño del tablero",
		"Choose a board size for both of you": "Elige el tablero para los dos",
		"Computer": "Computadora",
		"Computer is thinking...": "La computadora está pensando...",
		"Confirm Line": "Confirmar línea",
		"Dots and Boxes": "Timbiriche",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Friend": "Amigo",
		"Friend disconnected — waiting...": "Tu amigo se desconectó — esperando...",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"It's a tie!\n%s %d - %s %d": "¡Empate!\n%s %d - %s %d",
		"Medium": "Medio",
		"New Game": "Nueva partida",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again (Same Setup)": "Jugar de nuevo (igual)",
		"Red": "Rojo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Waiting for your friend to choose a board...": "Esperando a que tu amigo elija el tablero...",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"vs Computer": "vs Computadora",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
