extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d ms\nTap to try again": "%d ms\nToca para intentar de nuevo",
		"%d of %d unlocked": "%d de %d desbloqueados",
		"After a random delay it turns green — tap it right away.": "Tras un tiempo al azar se pone verde — tócalo enseguida.",
		"Attempt #%d": "Intento #%d",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d ms": "Mejor: %d ms",
		"Best: —": "Mejor: —",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't try to guess the moment — the delay is random every time.": "No intentes adivinar el momento — la espera es al azar cada vez.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fastest reaction (ms)": "Reacción más rápida (ms)",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Most people land between 200 and 300 ms. Under 200 is very fast!": "La mayoría de las personas marca entre 200 y 300 ms. ¡Menos de 200 es muy rápido!",
		"Multiplayer": "Multijugador",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Reaction Test": "Test de reacción",
		"Relax your hand and keep your finger just above the screen.": "Relaja la mano y mantén el dedo justo encima de la pantalla.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"TAP NOW!": "¡TOCA YA!",
		"Tap as fast as you can the moment the pad turns green.": "Toca lo más rápido que puedas en cuanto el botón se ponga verde.",
		"Tap before it turns green and it counts as a false start.": "Si tocas antes de que se ponga verde, cuenta como salida en falso.",
		"Tap the button below to start": "Toca el botón de abajo para empezar",
		"Tap the pad to start": "Toca el panel para empezar",
		"Tap the pad to start, then wait while it's red.": "Toca el botón para empezar y espera mientras está rojo.",
		"Tap the pad when it turns green": "Toca el panel cuando se ponga verde",
		"Tests taken": "Pruebas hechas",
		"Tests taken, all time. (Your fastest time is in Statistics.)": "Pruebas hechas en total. (Tu tiempo más rápido está en Estadísticas.)",
		"Too soon!\nTap to try again": "¡Muy pronto!\nToca para intentar de nuevo",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Wait for green...": "Espera el verde...",
		"Wait for green… then tap as fast as you can.": "Espera el verde… y toca lo más rápido que puedas.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your reaction time is shown in milliseconds (1000 ms = 1 second).": "Tu tiempo de reacción se muestra en milisegundos (1000 ms = 1 segundo).",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏱️ Reaction Test": "⏱️ Test de reacción",
		"⏸ pauses. Every test is a single tap, so there's nothing to save.": "⏸ pausa. Cada prueba es un solo toque, así que no hay nada que guardar.",
		"▶  Continue": "▶  Continuar",
		"⚡  Start": "⚡  Empezar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
