extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d ms\nTap to try again": "%d ms\nToca para intentar de nuevo",
		"After a random delay it turns green — tap it right away.": "Tras un tiempo al azar se pone verde — tócalo enseguida.",
		"Attempt #%d": "Intento #%d",
		"Best: %d ms": "Mejor: %d ms",
		"Best: —": "Mejor: —",
		"Don't try to guess the moment — the delay is random every time.": "No intentes adivinar el momento — la espera es al azar cada vez.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fastest reaction (ms)": "Reacción más rápida (ms)",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Most people land between 200 and 300 ms. Under 200 is very fast!": "La mayoría de las personas marca entre 200 y 300 ms. ¡Menos de 200 es muy rápido!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Reaction Test": "Test de reacción",
		"Relax your hand and keep your finger just above the screen.": "Relaja la mano y mantén el dedo justo encima de la pantalla.",
		"TAP NOW!": "¡TOCA YA!",
		"Tap as fast as you can the moment the pad turns green.": "Toca lo más rápido que puedas en cuanto el botón se ponga verde.",
		"Tap before it turns green and it counts as a false start.": "Si tocas antes de que se ponga verde, cuenta como salida en falso.",
		"Tap the button below to start": "Toca el botón de abajo para empezar",
		"Tap the pad to start, then wait while it's red.": "Toca el botón para empezar y espera mientras está rojo.",
		"Tests taken": "Pruebas hechas",
		"Too soon!\nTap to try again": "¡Muy pronto!\nToca para intentar de nuevo",
		"Wait for green...": "Espera el verde...",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your reaction time is shown in milliseconds (1000 ms = 1 second).": "Tu tiempo de reacción se muestra en milisegundos (1000 ms = 1 segundo).",
		"Your turn (%s)": "Tu turno (%s)",
		"⏱️ Reaction Test": "⏱️ Test de reacción",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
