extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Card %d": "Carta %d",
		"Cards played": "Cartas jugadas",
		"Deck: 🌶️ Spicy": "Mazo: 🌶️ Picante",
		"Deck: 🎲 Mixed": "Mazo: 🎲 Mixto",
		"Deck: 😇 Mild": "Mazo: 😇 Suave",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Find out who's done what — one card at a time.": "Descubre quién ha hecho qué — carta por carta.",
		"Hard": "Difícil",
		"Honesty makes the game. Story time is allowed when someone drinks!": "La honestidad hace el juego. ¡Cuando alguien bebe, se vale contar la historia!",
		"Hub": "Inicio",
		"Make up your own \"Never have I ever\" between cards to target your friends.": "Inventa tus propios \"Yo nunca nunca\" entre cartas para apuntar a tus amigos.",
		"Medium": "Medio",
		"Never Have I Ever": "Yo nunca nunca",
		"Next card ➜": "Siguiente carta ➜",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pick a deck: 😇 Mild for anyone, 🌶️ Spicy for flirty questions, or 🎲 Mixed.": "Elige un mazo: 😇 Suave para todos, 🌶️ Picante para preguntas coquetas, o 🎲 Mixto.",
		"Read it out loud. Everyone who HAS done it drinks!": "Léela en voz alta. ¡Bebe todo el que SÍ lo haya hecho!",
		"Read the card out loud. Everyone who HAS done it takes a drink.": "Lee la carta en voz alta. Todo el que SÍ lo haya hecho toma un trago.",
		"Sit in a circle and pass the phone around, or let one person read for everyone.": "Siéntense en círculo y pásense el teléfono, o que una persona lea para todos.",
		"Tap the card (or Next card) for the next one. No card repeats until the whole deck has been played.": "Toca la carta (o Siguiente carta) para pasar a la próxima. Ninguna carta se repite hasta que se juegue todo el mazo.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🙊 Never Have I Ever": "🙊 Yo nunca nunca",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
