extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s ran out of cards mid-war!": "¡%s se quedó sin cartas en plena guerra!",
		"%sCPU wins %d cards!": "%s¡La CPU gana %d cartas!",
		"%sYou win %d cards!": "%s¡Ganas %d cartas!",
		"A long War can swing the game in one go!": "¡Una Guerra larga puede dar vuelta el juego de un golpe!",
		"A tie means War: each player puts three cards face down and one face up. The higher face-up card takes them all.": "Un empate es Guerra: cada jugador pone tres cartas boca abajo y una boca arriba. La carta boca arriba más alta se lleva todas.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"CPU wins the game!": "¡La CPU gana la partida!",
		"CPU: %d": "CPU: %d",
		"CPU: 26": "CPU: 26",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Flip, compare, win the cards. Take all 52!": "Voltea, compara y gánate las cartas. ¡Llévate las 52!",
		"Games won against the computer.": "Partidas ganadas a la computadora.",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play Round": "Jugar ronda",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Run out of cards and you lose.": "Si te quedas sin cartas, pierdes.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Tap Play Round to begin!": "¡Toca Jugar ronda para empezar!",
		"The deck is split in two. Tap Play Round and each player turns over their top card.": "El mazo se divide en dos. Toca Jugar ronda y cada jugador da vuelta su carta de arriba.",
		"The higher card wins both. Aces are high.": "La carta más alta se lleva las dos. El As es la más alta.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"War": "Guerra",
		"War is pure luck — there's nothing to decide, so just enjoy it.": "La Guerra es pura suerte — no hay nada que decidir, así que disfrútala.",
		"Win all 52 cards. You play against the computer.": "Gana las 52 cartas. Juegas contra la computadora.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win the game!": "¡Ganaste la partida!",
		"You win!": "¡Ganaste!",
		"You: %d": "Tú: %d",
		"You: %s": "Tú: %s",
		"You: 26": "Tú: 26",
		"Your turn (%s)": "Tu turno (%s)",
		"vs the computer": "contra la computadora",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the game; Resume on the Home screen carries on.": "⏸ pausa y guarda la partida; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"⚔️  Play": "⚔️  Jugar",
		"⚔️ WAR! ": "⚔️ ¡GUERRA! ",
		"⚔️ War": "⚔️ Guerra",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
