extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s ran out of cards mid-war!": "¡%s se quedó sin cartas en plena guerra!",
		"%sCPU wins %d cards!": "%s¡La CPU gana %d cartas!",
		"%sYou win %d cards!": "%s¡Ganas %d cartas!",
		"A long War can swing the game in one go!": "¡Una Guerra larga puede dar vuelta el juego de un golpe!",
		"A tie means War: each player puts three cards face down and one face up. The higher face-up card takes them all.": "Un empate es Guerra: cada jugador pone tres cartas boca abajo y una boca arriba. La carta boca arriba más alta se lleva todas.",
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"CPU wins the game!": "¡La CPU gana la partida!",
		"CPU: %d": "CPU: %d",
		"CPU: 26": "CPU: 26",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Play Round": "Jugar ronda",
		"Restart": "Reiniciar",
		"Run out of cards and you lose.": "Si te quedas sin cartas, pierdes.",
		"Tap Play Round to begin!": "¡Toca Jugar ronda para empezar!",
		"The deck is split in two. Tap Play Round and each player turns over their top card.": "El mazo se divide en dos. Toca Jugar ronda y cada jugador da vuelta su carta de arriba.",
		"The higher card wins both. Aces are high.": "La carta más alta se lleva las dos. El As es la más alta.",
		"War": "Guerra",
		"War is pure luck — there's nothing to decide, so just enjoy it.": "La Guerra es pura suerte — no hay nada que decidir, así que disfrútala.",
		"Win all 52 cards. You play against the computer.": "Gana las 52 cartas. Juegas contra la computadora.",
		"Wins": "Victorias",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win the game!": "¡Ganaste la partida!",
		"You win!": "¡Ganaste!",
		"You: %d": "Tú: %d",
		"You: 26": "Tú: 26",
		"Your turn (%s)": "Tu turno (%s)",
		"⚔️ WAR! ": "⚔️ ¡GUERRA! ",
		"⚔️ War": "⚔️ Guerra",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
