extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s ran out of cards mid-war!": "¡%s se quedó sin cartas en plena guerra!",
		"%sCPU wins %d cards!": "%s¡La CPU gana %d cartas!",
		"%sYou win %d cards!": "%s¡Ganas %d cartas!",
		"Back to Hub": "Volver al inicio",
		"CPU wins the game!": "¡La CPU gana la partida!",
		"CPU: %d": "CPU: %d",
		"CPU: 26": "CPU: 26",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Play Round": "Jugar ronda",
		"Restart": "Reiniciar",
		"Tap Play Round to begin!": "¡Toca Jugar ronda para empezar!",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win the game!": "¡Ganaste la partida!",
		"You win!": "¡Ganaste!",
		"You: %d": "Tú: %d",
		"You: 26": "Tú: 26",
		"Your turn (%s)": "Tu turno (%s)",
		"⚔️ WAR! ": "⚔️ ¡GUERRA! ",
		"⚔️ War": "⚔️ Guerra",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
