extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A right answer scores 10 points, plus up to 5 bonus points for answering quickly. A wrong answer or running out of time scores nothing.": "Una respuesta correcta vale 10 puntos, más hasta 5 puntos extra por responder rápido. Una respuesta incorrecta, o quedarte sin tiempo, no suma nada.",
		"Answer ten questions and score as many points as you can.": "Responde diez preguntas y suma todos los puntos que puedas.",
		"Arts & Culture": "Arte y cultura",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Best: %d": "Mejor: %d",
		"Change topic": "Cambiar de tema",
		"Choose a topic": "Elige un tema",
		"Correct answers": "Respuestas correctas",
		"Correct! +%d": "¡Correcto! +%d",
		"Correct: %d of %d": "Correctas: %d de %d",
		"Don't linger: the speed bonus shrinks every 3 seconds.": "No te demores: el bono de rapidez se reduce cada 3 segundos.",
		"Each question has four answers and you have 20 seconds. Tap the right one.": "Cada pregunta tiene cuatro respuestas y tienes 20 segundos. Toca la correcta.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Geography": "Geografía",
		"Hard": "Difícil",
		"History": "Historia",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Mixed": "Mezcla",
		"Nature & Animals": "Naturaleza y animales",
		"New best!": "¡Nuevo récord!",
		"Not quite.": "No exactamente.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pick a topic (or Mixed for questions from all of them).": "Elige un tema (o Mezcla para preguntas de todos ellos).",
		"Play Again": "Jugar de nuevo",
		"Question %d of %d": "Pregunta %d de %d",
		"Quiz complete!": "¡Cuestionario completo!",
		"Rule out the answers you know are wrong first; it is faster than hunting for the right one.": "Descarta primero las respuestas que sabes que son incorrectas; es más rápido que buscar la correcta.",
		"Science": "Ciencia",
		"Score: %d": "Puntos: %d",
		"Sports & Games": "Deportes y juegos",
		"The questions come in your app's language, English or Spanish.": "Las preguntas vienen en el idioma de tu app, inglés o español.",
		"Time's up!": "¡Se acabó el tiempo!",
		"Trivia": "Trivia",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"❓ Trivia": "❓ Trivia",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
