extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A right answer scores 10 points, plus up to 5 bonus points for answering quickly. A wrong answer or running out of time scores nothing.": "Una respuesta correcta vale 10 puntos, más hasta 5 puntos extra por responder rápido. Una respuesta incorrecta, o quedarte sin tiempo, no suma nada.",
		"Answer ten questions and score as many points as you can.": "Responde diez preguntas y suma todos los puntos que puedas.",
		"Arts & Culture": "Arte y cultura",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Best: %d": "Mejor: %d",
		"Change topic": "Cambiar de tema",
		"Choose a topic": "Elige un tema",
		"Close": "Cerrar",
		"Correct answers": "Respuestas correctas",
		"Correct! +%d": "¡Correcto! +%d",
		"Correct: %d of %d": "Correctas: %d de %d",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't linger: the speed bonus shrinks every 3 seconds.": "No te demores: el bono de rapidez se reduce cada 3 segundos.",
		"Draws": "Empates",
		"Each question has four answers and you have 20 seconds. Tap the right one.": "Cada pregunta tiene cuatro respuestas y tienes 20 segundos. Toca la correcta.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Geography": "Geografía",
		"Hard": "Difícil",
		"History": "Historia",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Mixed": "Mezcla",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"Nature & Animals": "Naturaleza y animales",
		"New best!": "¡Nuevo récord!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Not quite.": "No exactamente.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pick a topic": "Elige un tema",
		"Pick a topic (or Mixed for questions from all of them).": "Elige un tema (o Mezcla para preguntas de todos ellos).",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Question %d of %d": "Pregunta %d de %d",
		"Quiz complete!": "¡Cuestionario completo!",
		"Resume": "Continuar",
		"Rule out the answers you know are wrong first; it is faster than hunting for the right one.": "Descarta primero las respuestas que sabes que son incorrectas; es más rápido que buscar la correcta.",
		"Science": "Ciencia",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Sports & Games": "Deportes y juegos",
		"Ten questions. Answer fast for more points.": "Diez preguntas. Responde rápido para sumar más puntos.",
		"The questions come in your app's language, English or Spanish.": "Las preguntas vienen en el idioma de tu app, inglés o español.",
		"Time's up!": "¡Se acabó el tiempo!",
		"Trivia": "Trivia",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score in one game.": "Tu mejor puntaje en una partida.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock. A game is ten quick questions, so it isn't saved for later.": "⏸ pausa el reloj. Una partida son diez preguntas rápidas, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"❓ Trivia": "❓ Trivia",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
		"🧠  Play": "🧠  Jugar",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
