extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Card %d": "Carta %d",
		"Cards played": "Cartas jugadas",
		"Count to three together, then everyone points at someone at the same time.": "Cuenten juntos hasta tres y todos señalan a alguien al mismo tiempo.",
		"Deck: 🌶️ Spicy": "Mazo: 🌶️ Picante",
		"Deck: 🎲 Mixed": "Mazo: 🎲 Mixto",
		"Deck: 😇 Mild": "Mazo: 😇 Suave",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Find out what your friends really think of you — one card at a time.": "Descubre qué piensan de verdad tus amigos de ti — carta por carta.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Most Likely To": "Quién es más probable",
		"Next card ➜": "Siguiente carta ➜",
		"No pointing at yourself — unless you really are the most likely!": "No vale señalarse a uno mismo — ¡salvo que de verdad seas el más probable!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Read it out loud, count to 3 and point! Most fingers drinks.": "¡Léela en voz alta, cuenten hasta 3 y señalen! Bebe quien tenga más dedos.",
		"Read the card out loud: \"Who's most likely to…\"": "Lee la carta en voz alta: \"¿Quién es más probable que…?\"",
		"Sit in a circle and pass the phone around, or let one person read for everyone.": "Siéntense en círculo y pásense el teléfono, o que una persona lea para todos.",
		"Tap the card (or Next card) for the next one. Pick a deck: 😇 Mild, 🌶️ Spicy or 🎲 Mixed.": "Toca la carta (o Siguiente carta) para pasar a la próxima. Elige un mazo: 😇 Suave, 🌶️ Picante o 🎲 Mixto.",
		"The person with the most fingers has to explain themselves.": "Quien tenga más dedos tiene que dar explicaciones.",
		"Whoever gets the most fingers drinks — one sip per finger if you're feeling brave.": "Bebe quien tenga más dedos — un trago por dedo si se sienten valientes.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"👉 Most Likely To": "👉 Quién es más probable",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
