extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Card %d": "Carta %d",
		"Cards played": "Cartas jugadas",
		"Cards played, all time.": "Cartas jugadas en total.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Count to three together, then everyone points at someone at the same time.": "Cuenten juntos hasta tres y todos señalan a alguien al mismo tiempo.",
		"Deck: 🌶️ Spicy": "Mazo: 🌶️ Picante",
		"Deck: 🎲 Mixed": "Mazo: 🎲 Mixto",
		"Deck: 😇 Mild": "Mazo: 😇 Suave",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Find out what your friends really think of you — one card at a time.": "Descubre qué piensan de verdad tus amigos de ti — carta por carta.",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Most Likely To": "Quién es más probable",
		"Multiplayer": "Multijugador",
		"Next card ➜": "Siguiente carta ➜",
		"No pointing at yourself — unless you really are the most likely!": "No vale señalarse a uno mismo — ¡salvo que de verdad seas el más probable!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Party · one phone, pass it around": "Fiesta · un teléfono, pásenlo",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Read it out loud, count to 3 and point! Most fingers drinks.": "¡Léela en voz alta, cuenten hasta 3 y señalen! Bebe quien tenga más dedos.",
		"Read the card out loud: \"Who's most likely to…\"": "Lee la carta en voz alta: \"¿Quién es más probable que…?\"",
		"Read the card, count to three and point. Most fingers drinks!": "Lee la carta, cuenta hasta tres y señala. ¡Bebe quien tenga más dedos!",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Sit in a circle and pass the phone around, or let one person read for everyone.": "Siéntense en círculo y pásense el teléfono, o que una persona lea para todos.",
		"Tap the card (or Next card) for the next one. Pick a deck: 😇 Mild, 🌶️ Spicy or 🎲 Mixed.": "Toca la carta (o Siguiente carta) para pasar a la próxima. Elige un mazo: 😇 Suave, 🌶️ Picante o 🎲 Mixto.",
		"The person with the most fingers has to explain themselves.": "Quien tenga más dedos tiene que dar explicaciones.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Whoever gets the most fingers drinks — one sip per finger if you're feeling brave.": "Bebe quien tenga más dedos — un trago por dedo si se sienten valientes.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses. There's nothing to save: every card is drawn fresh.": "⏸ pausa. No hay nada que guardar: cada carta sale nueva.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌶️ Spicy": "🌶️ Picante",
		"🎯 Goal": "🎯 Objetivo",
		"🎲 Mixed": "🎲 Mezcla",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👉 Most Likely To": "👉 Quién es más probable",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
		"😇 Mild": "😇 Suave",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
