extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"3 ships · extra ship every 10,000": "3 naves · una extra cada 10.000",
		"A rock that hits your ship costs a life. You start with 3 and get one more every 10,000 points. A new ship blinks for a moment and can't be hit.": "Una roca que choca con tu nave te cuesta una vida. Empiezas con 3 y ganas otra cada 10.000 puntos. Una nave nueva parpadea un momento y no puede ser golpeada.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Big rocks split into two medium ones, medium into two small; small ones turn to dust. Big 20, medium 50, small 100 points.": "Las rocas grandes se parten en dos medianas, las medianas en dos pequeñas y las pequeñas se hacen polvo. Grande 20, mediana 50, pequeña 100 puntos.",
		"Blast the space rocks for points and survive as many waves as you can.": "Destruye las rocas espaciales para sumar puntos y sobrevive todas las oleadas que puedas.",
		"Clear every rock for the next wave: more rocks, a little faster each time.": "Limpia todas las rocas para pasar a la siguiente oleada: más rocas y un poco más rápidas cada vez.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game over!": "¡Fin del juego!",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Highest wave": "Oleada más alta",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Rock Blaster": "Rompe rocas",
		"Score: %d": "Puntos: %d",
		"Short taps are safer than flying: stay near the middle and let the rocks come to you.": "Los toques cortos son más seguros que volar: quédate cerca del centro y deja que las rocas vengan.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Small rocks are fast and worth the most — finish them before splitting another big one.": "Las rocas pequeñas son rápidas y valen más: acábalas antes de partir otra grande.",
		"Tap anywhere: your ship turns that way and fires one shot.": "Toca en cualquier lugar: tu nave gira hacia ahí y dispara una vez.",
		"Tap to shoot, hold to fly. Split the rocks before they split you.": "Toca para disparar, mantén para volar. Parte las rocas antes de que te partan a ti.",
		"The field wraps around: fly off one edge and you come back on the other — and so do the rocks.": "El campo da la vuelta: si sales por un borde, vuelves por el otro, y las rocas también.",
		"Touch and hold: the ship turns towards your finger, flies that way and keeps firing. Let go to drift.": "Toca y mantén: la nave gira hacia tu dedo, vuela hacia ahí y sigue disparando. Suelta para flotar.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Watch the edges: a rock leaving one side is about to appear on the other.": "Vigila los bordes: una roca que sale por un lado está por aparecer del otro.",
		"Wave %d": "Oleada %d",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the game; Resume on the Home screen carries on.": "⏸ pausa y guarda la partida; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
