extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"3 of a Kind": "Trío",
		"4 of a Kind": "Póker",
		"63 or more in Ones to Sixes earns a 35-point bonus. Every extra Yacht after the first is worth 100.": "63 o más entre Unos y Seises da un bono de 35 puntos. Cada Generala extra después de la primera vale 100.",
		"Aim for three of each number in the upper section — that's exactly 63 and the bonus.": "Busca tres de cada número en la sección de arriba — eso da justo 63 y el bono.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Chance": "Libre",
		"Each turn, roll the five dice up to three times. Tap dice to hold them between rolls.": "En cada turno, tira los cinco dados hasta tres veces. Toca los dados para guardarlos entre tiradas.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Final score: %d": "Puntaje final: %d",
		"Fives": "Cincos",
		"Fours": "Cuatros",
		"Full House": "Full",
		"Full House is 25, Small Straight (4 in a row) is 30, Large Straight (5 in a row) is 40, and Yacht (five of a kind) is 50.": "Full vale 25, Escalera menor (4 seguidos) 30, Escalera mayor (5 seguidos) 40 y Generala (cinco iguales) 50.",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Held": "Guardado",
		"Hub": "Inicio",
		"If a turn goes badly, put a 0 in a box you're unlikely to fill anyway, like Yacht or Ones.": "Si un turno sale mal, anota un 0 en una casilla que difícilmente completes, como Generala o Unos.",
		"Keep Chance for a bad turn.": "Guarda Libre para un mal turno.",
		"Large Straight": "Escalera mayor",
		"Medium": "Medio",
		"Ones": "Unos",
		"Ones to Sixes: the total of that number. 3 and 4 of a Kind and Chance: the total of all dice.": "Unos a Seises: la suma de ese número. Trío, Póker y Libre: la suma de todos los dados.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pick a box to score.": "Elige una casilla para anotar.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Roll the dice to start your turn.": "Tira los dados para empezar tu turno.",
		"Score as many points as you can by filling all 13 boxes.": "Suma todos los puntos que puedas llenando las 13 casillas.",
		"Sixes": "Seises",
		"Small Straight": "Escalera menor",
		"Tap dice to hold them, roll again, or pick a box.": "Toca dados para guardarlos, vuelve a tirar o elige una casilla.",
		"Then pick a box to score your dice in. Each box can be used only once, even if it scores 0.": "Luego elige una casilla para anotar tus dados. Cada casilla se usa una sola vez, aunque valga 0.",
		"Threes": "Treses",
		"Total: %d   Upper: %d/63   Best: %d": "Total: %d   Arriba: %d/63   Récord: %d",
		"Twos": "Doses",
		"Yacht": "Generala",
		"Yacht Dice": "Generala",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🎲 Roll (%d left)": "🎲 Tirar (quedan %d)",
		"🎲 Yacht Dice": "🎲 Generala",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
