extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"3 of a Kind": "Trío",
		"4 of a Kind": "Póker",
		"Back to Hub": "Volver al inicio",
		"Best: %d": "Mejor: %d",
		"Chance": "Libre",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Final score: %d": "Puntaje final: %d",
		"Fives": "Cincos",
		"Fours": "Cuatros",
		"Full House": "Full",
		"Game Over": "Fin del juego",
		"Hard": "Difícil",
		"Held": "Guardado",
		"Hub": "Inicio",
		"Large Straight": "Escalera mayor",
		"Medium": "Medio",
		"Ones": "Unos",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pick a box to score.": "Elige una casilla para anotar.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Roll the dice to start your turn.": "Tira los dados para empezar tu turno.",
		"Sixes": "Seises",
		"Small Straight": "Escalera menor",
		"Tap dice to hold them, roll again, or pick a box.": "Toca dados para guardarlos, vuelve a tirar o elige una casilla.",
		"Threes": "Treses",
		"Total: %d   Upper: %d/63   Best: %d": "Total: %d   Arriba: %d/63   Récord: %d",
		"Twos": "Doses",
		"Yacht": "Generala",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🎲 Roll (%d left)": "🎲 Tirar (quedan %d)",
		"🎲 Yacht Dice": "🎲 Generala",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
