extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A clue in the bottom-left is the total for the run going down below it.": "Una pista abajo a la izquierda es el total de la fila de casillas que baja debajo de ella.",
		"A clue in the top-right of a dark square is the total for the run of white squares to its right.": "Una pista arriba a la derecha de una casilla oscura es el total de las casillas blancas a su derecha.",
		"Back to Hub": "Volver al inicio",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Big sums in short runs force big digits, small sums force small digits.": "Las sumas grandes en filas cortas obligan a usar dígitos grandes, y las chicas, dígitos chicos.",
		"Each run adds up to its clue (top-right → across, bottom-left ↓ down). No repeats in a run.": "Cada tramo suma su pista (arriba a la derecha → horizontal, abajo a la izquierda ↓ vertical). Sin repetir en un tramo.",
		"Easy": "Fácil",
		"Every sum checks out.": "Todas las sumas cuadran.",
		"Expert": "Experto",
		"Fill the white squares with 1–9 so each run adds up to its clue.": "Llena las casillas blancas con 1–9 para que cada fila sume su pista.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Kakuro": "Kakuro",
		"Large": "Grande",
		"Learn the runs with only one answer: 3 in two squares is always 1+2, 4 is 1+3, 16 is 7+9 and 17 is 8+9.": "Aprende las filas con una sola respuesta: 3 en dos casillas siempre es 1+2, 4 es 1+3, 16 es 7+9 y 17 es 8+9.",
		"Medium": "Medio",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"No digit can repeat within a run.": "Ningún dígito se puede repetir en una misma fila.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Puzzles solved": "Puzzles resueltos",
		"Small": "Chico",
		"Solved!": "¡Resuelto!",
		"Switch between Small and Large boards with the size button.": "Cambia entre tablero Chico y Grande con el botón de tamaño.",
		"Tap a square, then a digit to fill it (⌫ clears it). Repeated digits are shown in red.": "Toca una casilla y luego un dígito para llenarla (⌫ la borra). Los dígitos repetidos se muestran en rojo.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Where an across run and a down run cross, the square must suit both sums.": "Donde se cruzan una fila horizontal y una vertical, la casilla debe servir para las dos sumas.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"➗ Kakuro": "➗ Kakuro",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
