extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Each run adds up to its clue (top-right → across, bottom-left ↓ down). No repeats in a run.": "Cada tramo suma su pista (arriba a la derecha → horizontal, abajo a la izquierda ↓ vertical). Sin repetir en un tramo.",
		"Easy": "Fácil",
		"Every sum checks out.": "Todas las sumas cuadran.",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Large": "Grande",
		"Medium": "Medio",
		"New": "Nuevo",
		"Next Puzzle": "Siguiente puzzle",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Small": "Chico",
		"Solved!": "¡Resuelto!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"➗ Kakuro": "➗ Kakuro",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
