extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s drew %d.": "%s robó %d.",
		"%s is thinking...": "%s está pensando...",
		"%s passes.": "%s pasa.",
		"%s plays %s": "%s juega %s",
		"%s wins!": "¡Gana %s!",
		"%s: %d cards": "%s: %d cartas",
		"8s are wild: play one on anything and choose the next suit.": "Los 8 son comodines: juégalos sobre cualquier carta y elige el siguiente palo.",
		"8️⃣ Crazy Eights": "8️⃣ Ocho loco",
		"Back to Hub": "Volver al inicio",
		"Be the first to get rid of all your cards. You play against two computers.": "Sé el primero en quedarte sin cartas. Juegas contra dos computadoras.",
		"Best streak": "Mejor racha",
		"CPU %d": "CPU %d",
		"Can't play? Tap the deck to draw until you can. If the deck is empty too, you pass.": "¿No puedes jugar? Toca el mazo para robar hasta que puedas. Si el mazo también está vacío, pasas.",
		"Choose a suit": "Elige un palo",
		"Crazy Eights": "Ocho loco",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Keep your 8s for when you're stuck.": "Guarda tus 8 para cuando te trabes.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"New": "Nuevo",
		"No match and no cards left — tap the deck to pass.": "No hay jugada ni cartas — toca el mazo para pasar.",
		"No match — tap the deck to draw.": "No hay jugada — toca el mazo para robar.",
		"Nobody can move — it's a draw.": "Nadie puede jugar — empate.",
		"On your turn, play a card that matches the top card's suit or rank.": "En tu turno, juega una carta del mismo palo o número que la de arriba.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"The first player with no cards left wins.": "Gana el primer jugador que se quede sin cartas.",
		"Watch how many cards the computers have left, and change the suit when one is about to go out.": "Fíjate cuántas cartas les quedan a las computadoras y cambia el palo cuando una esté por ganar.",
		"When you play an 8, pick the suit you hold the most of.": "Cuando juegues un 8, elige el palo del que más cartas tengas.",
		"Wins": "Victorias",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn: match %s or a rank, 8s are wild.": "Tu turno: juega %s o el mismo número; los 8 son comodines.",
		"suit is now %s": "ahora el palo es %s",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
