extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d points.": "%d puntos.",
		"%s undercut the knock": "%s contraatacó el golpe",
		"%s went gin": "%s hizo gin",
		"%s won the knock": "%s ganó con el golpe",
		"(deadwood %d)": "(sueltas %d)",
		"Back to Hub": "Volver al inicio",
		"Computer": "Computadora",
		"Computer draws from the stock.": "La computadora roba del mazo.",
		"Computer takes the %s.": "La computadora toma el %s.",
		"Computer's turn...": "Turno de la computadora...",
		"Discard": "Descartar",
		"Draw from the stock or the discard pile.  Deadwood: %d": "Roba del mazo o del descarte.  Sueltas: %d",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Gin!": "¡Gin!",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Knock": "Golpear",
		"Knock (%d)": "Golpear (%d)",
		"Match Over": "Fin de la partida",
		"Medium": "Medio",
		"New": "Nuevo",
		"Next Hand": "Siguiente mano",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Select a card to discard.  Deadwood: %d": "Elige una carta para descartar.  Sueltas: %d",
		"Stock: %d": "Mazo: %d",
		"The computer": "La computadora",
		"The computer wins the match.": "La computadora gana la partida.",
		"The stock ran out — this hand is a draw.": "Se acabó el mazo — esta mano es empate.",
		"You": "Tú",
		"You %d  ·  Computer %d   (to %d)": "Tú %d  ·  Computadora %d   (a %d)",
		"You lose!": "¡Perdiste!",
		"You win the match!": "¡Ganaste la partida!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🃁 Gin Rummy": "🃁 Gin Rummy",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
