extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"1 = 100 · 5 = 50 · three of a kind = face × 100 (1s = 1000), each extra doubles · straight or three pairs = 1500": "1 = 100 · 5 = 50 · tres iguales = cara × 100 (tres 1 = 1000), cada dado extra duplica · escalera o tres pares = 1500",
		"Back to Hub": "Volver al inicio",
		"Bank": "Plantarse",
		"Bank %d": "Plantarse con %d",
		"Computer banks %d.": "La computadora se planta con %d.",
		"Computer farkled!": "¡La computadora hizo Farkle!",
		"Computer keeps %d points.": "La computadora aparta %d puntos.",
		"Computer rolls again (turn: %d).": "La computadora vuelve a tirar (turno: %d).",
		"Computer's turn...": "Turno de la computadora...",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Farkle! No scoring dice — you lose this turn's points.": "¡Farkle! Ningún dado puntúa — pierdes los puntos del turno.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Keep & roll %d": "Apartar y tirar %d",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Selected: %d  (turn total %d)": "Seleccionado: %d  (total del turno %d)",
		"Set aside:": "Apartados:",
		"Those dice don't all score.": "No todos esos dados puntúan.",
		"Turn: %d — tap scoring dice to set them aside.": "Turno: %d — toca los dados que puntúan para apartarlos.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %d   ·   Computer: %d   (to %d)": "Tú: %d   ·   Computadora: %d   (a %d)",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn — roll the dice!": "Tu turno — ¡tira los dados!",
		"🎯 Farkle": "🎯 Farkle",
		"🎲 Roll": "🎲 Tirar",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
