extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s\nScore: %d": "%s\nPuntos: %d",
		"A new 2 or 4 appears after every move.": "Después de cada movimiento aparece un 2 o un 4 nuevo.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best tile": "Mejor ficha",
		"Best: %d": "Mejor: %d",
		"Build a chain of shrinking numbers leading away from the corner, so merges cascade into it.": "Arma una cadena de números que van bajando desde la esquina, para que las uniones caigan en cascada hacia ella.",
		"Each merge adds the new tile's number to your score.": "Cada unión suma el número de la nueva ficha a tu puntaje.",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Keep Going": "Seguir jugando",
		"Keep the row along your corner full, so it can't shift out of place.": "Mantén llena la fila de tu esquina para que no se desacomode.",
		"Medium": "Medio",
		"Mostly use just two or three directions, so the big tile never gets pushed out of its corner.": "Usa casi siempre solo dos o tres direcciones, para que la ficha grande nunca salga de su esquina.",
		"New best!": "¡Nuevo récord!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Pick a corner and keep your biggest tile in it.": "Elige una esquina y mantén ahí tu ficha más grande.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Slide the tiles and merge matching numbers until you make a 2048 tile.": "Desliza las fichas y une números iguales hasta formar una ficha de 2048.",
		"Swipe or use arrow keys": "Desliza o usa las flechas",
		"Swipe up, down, left or right (or use the arrow keys). Every tile slides as far as it can.": "Desliza hacia arriba, abajo, izquierda o derecha (o usa las flechas). Todas las fichas se deslizan lo más lejos posible.",
		"The game ends when the board is full and nothing can merge. Reach 2048 and you can keep going for a bigger score.": "El juego termina cuando el tablero se llena y nada se puede unir. Si llegas a 2048 puedes seguir para sumar más.",
		"Two tiles with the same number that bump into each other merge into one: 2+2 makes 4, 4+4 makes 8, and so on.": "Dos fichas con el mismo número que chocan se unen en una: 2+2 da 4, 4+4 da 8, y así.",
		"You lose!": "¡Perdiste!",
		"You reached 2048!": "¡Llegaste a 2048!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
