extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"A small bump doesn't count — give it a real shake.": "Un golpecito no cuenta: agítala de verdad.",
		"Ask a yes-or-no question, then shake your phone": "Haz una pregunta de sí o no y agita el teléfono",
		"Ask a yes-or-no question, then tap or shake the ball": "Haz una pregunta de sí o no y toca o sacude la bola",
		"Ask it anything. Shake it. Believe it… or don't.": "Pregúntale lo que quieras. Agítala. Créele… o no.",
		"Ask the ball a yes-or-no question and see what fate says.": "Hazle a la bola una pregunta de sí o no y mira qué dice el destino.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Classic answers": "Respuestas clásicas",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fortune Ball": "Bola de la fortuna",
		"Green answers lean yes, gold ones are unsure, pink ones lean no.": "Las respuestas verdes tiran a sí, las doradas no están seguras y las rosas tiran a no.",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No answer repeats until you've seen them all.": "Ninguna respuesta se repite hasta que las hayas visto todas.",
		"No answers": "Respuestas no",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"On Home, pick the ball's voice: Classic answers, or Spooky answers from the spirits.": "En el inicio, elige la voz de la bola: Respuestas clásicas, o Respuestas tenebrosas de los espíritus.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pick the ball's voice": "Elige la voz de la bola",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Questions asked": "Preguntas hechas",
		"Questions asked, all time.": "Preguntas hechas, desde siempre.",
		"Resume": "Continuar",
		"Shake again for another answer": "Agita otra vez para otra respuesta",
		"Shake your phone. No sensor? Grab the ball and flick it around, tap it, or press Shake.": "Agita el teléfono. ¿No tiene sensor? Arrastra la bola y sacúdela, tócala o pulsa Agitar.",
		"Shaking…": "Agitando…",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Spooky answers": "Respuestas tenebrosas",
		"Stop shaking: the ball settles and the answer floats up in its window.": "Deja de agitar: la bola se calma y la respuesta sube flotando en su ventana.",
		"The answer is rising…": "La respuesta está subiendo…",
		"The answers are just for fun. Don't make big decisions with a ball!": "Las respuestas son solo para divertirse. ¡No tomes decisiones importantes con una bola!",
		"The spirits, the bones and the skull reply": "Responden los espíritus, los huesos y la calavera",
		"Think of a yes-or-no question — or say it out loud for everyone.": "Piensa una pregunta de sí o no, o dila en voz alta para todos.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"Yes answers": "Respuestas sí",
		"Yes, no, maybe — the fortune-teller way": "Sí, no, quizás: al estilo de las adivinas",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses. There's nothing to save: every question is fresh.": "⏸ pausa. No hay nada que guardar: cada pregunta es nueva.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🎱  Classic answers": "🎱  Respuestas clásicas",
		"🎱 Fortune Ball": "🎱 Bola de la fortuna",
		"🎱 Shake": "🎱 Agitar",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💀  Spooky answers": "💀  Respuestas tenebrosas",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
