extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Break through one side and get the ball above the wall — it will clear bricks from behind.": "Abre un hueco por un lado y mete la pelota detrás del muro — romperá ladrillos por detrás.",
		"Brick Breaker": "Rompeladrillos",
		"Bricks are worth more points on higher levels.": "Los ladrillos valen más puntos en los niveles altos.",
		"Clear the wall to move on to a new, tougher one. The ball speeds up as you go.": "Limpia el muro para pasar a uno nuevo y más difícil. La pelota se acelera a medida que avanzas.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Darker bricks take two hits.": "Los ladrillos más oscuros necesitan dos golpes.",
		"Demolisher": "Demoledor",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Highest level": "Nivel más alto",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Keep the paddle under the ball rather than chasing it at the last moment.": "Mantén la paleta bajo la pelota en vez de perseguirla a último momento.",
		"Level %d   Score: %d   Lives: %s   Best: %d": "Nivel %d   Puntos: %d   Vidas: %s   Récord: %d",
		"Level %d!": "¡Nivel %d!",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Miss the ball and you lose one of your three lives.": "Si se te escapa la pelota, pierdes una de tus tres vidas.",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Ouch! Tap to launch": "¡Ay! Toca para lanzar",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Slide the paddle, tap to launch. Smash every brick!": "Desliza la paleta y toca para lanzar. ¡Rompe todos los ladrillos!",
		"Slide to move the paddle, tap to launch. Break every brick!": "Desliza para mover la paleta, toca para lanzar. ¡Rompe todos los ladrillos!",
		"Slide your finger to move the paddle, and tap to launch the ball.": "Desliza el dedo para mover la paleta y toca para lanzar la pelota.",
		"Smash every brick on the wall without letting the ball fall.": "Rompe todos los ladrillos del muro sin dejar caer la pelota.",
		"Start": "Empezar",
		"Tap to launch": "Toca para lanzar",
		"Three lives, level after level": "Tres vidas, nivel tras nivel",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Wall Cracker": "Rompemuros",
		"Where the ball hits the paddle sets its angle: the edges send it off sideways.": "El lugar donde la pelota toca la paleta define su ángulo: los bordes la mandan de costado.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"Wrecking Ball": "Bola de demolición",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score.": "Tu mejor puntaje.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the game. A round can't be saved for later: leaving it ends it.": "⏸ pausa el juego. Una ronda no se puede guardar: si sales, termina.",
		"▶  Continue": "▶  Continuar",
		"▶  Play": "▶  Jugar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Brick Breaker": "🎯 Rompeladrillos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
