extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Break through one side and get the ball above the wall — it will clear bricks from behind.": "Abre un hueco por un lado y mete la pelota detrás del muro — romperá ladrillos por detrás.",
		"Brick Breaker": "Rompeladrillos",
		"Bricks are worth more points on higher levels.": "Los ladrillos valen más puntos en los niveles altos.",
		"Clear the wall to move on to a new, tougher one. The ball speeds up as you go.": "Limpia el muro para pasar a uno nuevo y más difícil. La pelota se acelera a medida que avanzas.",
		"Darker bricks take two hits.": "Los ladrillos más oscuros necesitan dos golpes.",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Highest level": "Nivel más alto",
		"Hub": "Inicio",
		"Keep the paddle under the ball rather than chasing it at the last moment.": "Mantén la paleta bajo la pelota en vez de perseguirla a último momento.",
		"Level %d   Score: %d   Lives: %s   Best: %d": "Nivel %d   Puntos: %d   Vidas: %s   Récord: %d",
		"Level %d!": "¡Nivel %d!",
		"Medium": "Medio",
		"Miss the ball and you lose one of your three lives.": "Si se te escapa la pelota, pierdes una de tus tres vidas.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Ouch! Tap to launch": "¡Ay! Toca para lanzar",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Slide to move the paddle, tap to launch. Break every brick!": "Desliza para mover la paleta, toca para lanzar. ¡Rompe todos los ladrillos!",
		"Slide your finger to move the paddle, and tap to launch the ball.": "Desliza el dedo para mover la paleta y toca para lanzar la pelota.",
		"Smash every brick on the wall without letting the ball fall.": "Rompe todos los ladrillos del muro sin dejar caer la pelota.",
		"Start": "Empezar",
		"Tap to launch": "Toca para lanzar",
		"Where the ball hits the paddle sets its angle: the edges send it off sideways.": "El lugar donde la pelota toca la paleta define su ángulo: los bordes la mandan de costado.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🎯 Brick Breaker": "🎯 Rompeladrillos",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
