extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"All cards are dealt face up in eight columns. Build down in alternating colours.": "Todas las cartas se reparten boca arriba en ocho columnas. Construye hacia abajo alternando colores.",
		"Almost every deal can be won, so if you get stuck, Undo and try another way.": "Casi todas las manos se pueden ganar, así que si te trabas, deshaz y prueba otro camino.",
		"An empty column is worth even more than a free cell.": "Una columna vacía vale todavía más que una celda libre.",
		"Back to Hub": "Volver al inicio",
		"Before you start, look for the Aces and twos buried deepest, and plan how to dig them out.": "Antes de empezar, busca los Ases y doses más enterrados y planea cómo sacarlos.",
		"Best score": "Mejor puntaje",
		"Best time": "Mejor tiempo",
		"Cards that aren't needed any more go up to the foundations by themselves.": "Las cartas que ya no se necesitan suben solas a las pilas de base.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Deals won, all time.": "Manos ganadas en total.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Four free cells. Every deal can be won.": "Cuatro celdas libres. Todas las manos se pueden ganar.",
		"Free cells are precious — try to keep at least one empty.": "Las celdas libres son valiosas — intenta dejar al menos una vacía.",
		"Games won": "Partidas ganadas",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Move all 52 cards onto the foundations, each suit from Ace up to King.": "Pasa las 52 cartas a las bases, cada palo del As al Rey.",
		"Moves: %d": "Movimientos: %d",
		"Moves: %d   Free cells: %d": "Movimientos: %d   Celdas libres: %d",
		"Multiplayer": "Multijugador",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solitaire": "Solitario",
		"Solved in %d moves!": "¡Resuelto en %d movimientos!",
		"Tap a card to send it to the best spot: a foundation, another column, or a free cell. Cards below it move along if there's room.": "Toca una carta para mandarla al mejor lugar: una base, otra columna o una celda libre. Las cartas de debajo la acompañan si hay espacio.",
		"The four free cells (top left) each hold one card for a while.": "Las cuatro celdas libres (arriba a la izquierda) guardan una carta cada una por un rato.",
		"The more free cells and empty columns you have, the longer the runs you can move at once.": "Cuantas más celdas libres y columnas vacías tengas, más largas las escaleras que puedes mover de una vez.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You Win!": "¡Ganaste!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the deal; Resume on the Home screen picks it up.": "⏸ pausa y guarda la mano; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🃏  New deal": "🃏  Nueva mano",
		"🆓 FreeCell": "🆓 FreeCell",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
