extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A row or column with a 0 is completely empty — mark it all off.": "Una fila o columna con un 0 está completamente vacía — márcala toda.",
		"Back to Hub": "Volver al inicio",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Easy": "Fácil",
		"Every line matches its clues.": "Todas las líneas coinciden con sus pistas.",
		"Every puzzle can be solved by logic alone — no guessing needed.": "Todos los puzzles se resuelven solo con lógica — no hace falta adivinar.",
		"Expert": "Experto",
		"Fill in the right squares to reveal the hidden picture.": "Pinta las casillas correctas para descubrir el dibujo oculto.",
		"Go back and forth between rows and columns.": "Alterna entre filas y columnas.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Mark the squares you've ruled out. Every ✕ narrows down the lines that cross it.": "Marca las casillas que descartaste. Cada ✕ reduce las opciones de las líneas que la cruzan.",
		"Medium": "Medio",
		"Mode: ■ Fill": "Modo: ■ Pintar",
		"Mode: ✕ Mark": "Modo: ✕ Marcar",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"Nonogram": "Nonograma",
		"Numbers are the runs of filled squares in each row and column, in order.": "Los números son los bloques de casillas pintadas de cada fila y columna, en orden.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Puzzles solved": "Puzzles resueltos",
		"Runs are separated by at least one empty square. \"3 1\" means three filled, a gap, then one filled.": "Los grupos están separados por al menos una casilla vacía. \"3 1\" significa tres pintadas, un espacio y una pintada.",
		"Solved!": "¡Resuelto!",
		"Start with big numbers: a 7 in a 10-square row must cover its middle four squares.": "Empieza por los números grandes: un 7 en una fila de 10 casillas debe cubrir sus cuatro casillas centrales.",
		"Tap or drag to fill squares. Switch to ✕ mode to mark squares you know are empty.": "Toca o arrastra para pintar casillas. Cambia al modo ✕ para marcar las que sabes que están vacías.",
		"The numbers beside each row and above each column are the lengths of its runs of filled squares, in order.": "Los números junto a cada fila y sobre cada columna son las longitudes de sus grupos de casillas pintadas, en orden.",
		"The puzzle is solved when every row and column matches its numbers.": "El puzzle está resuelto cuando cada fila y columna coincide con sus números.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🖼️ Nonogram": "🖼️ Nonograma",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
