extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Every line matches its clues.": "Todas las líneas coinciden con sus pistas.",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Mode: ■ Fill": "Modo: ■ Pintar",
		"Mode: ✕ Mark": "Modo: ✕ Marcar",
		"New": "Nuevo",
		"Next Puzzle": "Siguiente puzzle",
		"Numbers are the runs of filled squares in each row and column, in order.": "Los números son los bloques de casillas pintadas de cada fila y columna, en orden.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Solved!": "¡Resuelto!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🖼️ Nonogram": "🖼️ Nonograma",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
