extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"\nFastest time yet!": "\n¡Tu mejor tiempo!",
		"\nFewest moves yet!": "\n¡Tu récord de movimientos!",
		"%d moves in %s%s": "%d movimientos en %s%s",
		"15-Puzzle": "Puzzle deslizante 15",
		"Back to Hub": "Volver al inicio",
		"Best time": "Mejor tiempo",
		"Best: %d moves · %s": "Mejor: %d movimientos · %s",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Finish the bottom two rows column by column, from left to right.": "Termina las dos filas de abajo columna por columna, de izquierda a derecha.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Moves: %d": "Movimientos: %d",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Place the last two tiles of a row together: line them up next to their spots, then rotate them in.": "Coloca juntas las dos últimas fichas de una fila: alinéalas junto a su lugar y luego gíralas hacia adentro.",
		"Play Again": "Jugar de nuevo",
		"Puzzles solved": "Puzzles resueltos",
		"Shuffle": "Mezclar",
		"Shuffle starts a new puzzle. Every shuffle can be solved.": "Mezclar empieza un puzzle nuevo. Todas las mezclas tienen solución.",
		"Slide the tiles back into order, 1 to 15, with the gap in the bottom-right corner.": "Desliza las fichas para ordenarlas del 1 al 15, con el hueco en la esquina de abajo a la derecha.",
		"Solve the top row first, then the second row. Never disturb a finished row.": "Resuelve primero la fila de arriba y luego la segunda. Nunca desarmes una fila terminada.",
		"Solved!": "¡Resuelto!",
		"Tap a tile in the same row or column as the gap to slide it (and any tiles between) into the gap.": "Toca una ficha en la misma fila o columna que el hueco para deslizarla (junto con las del medio) hacia el hueco.",
		"Tiles turn green when they're in the right spot": "Las fichas se ponen verdes cuando están en su lugar",
		"Tiles turn green when they're in their correct spot.": "Las fichas se ponen verdes cuando están en su lugar.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🔲 15-Puzzle": "🔲 Puzzle 15",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
