extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"3 landers · new terrain every landing": "3 módulos · terreno nuevo en cada aterrizaje",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Crashed!": "¡Te estrellaste!",
		"Down: %d": "Caída: %d",
		"Draws": "Empates",
		"Each landing brings new mountains, a little less fuel and a little more gravity. A crash costs one of your 3 landers.": "Cada aterrizaje trae montañas nuevas, un poco menos de combustible y un poco más de gravedad. Un choque te cuesta uno de tus 3 módulos.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Fuel": "Combustible",
		"Games played": "Partidas jugadas",
		"Gentle on the engine, gentle on the ground. Land on a pad.": "Suave con el motor, suave al tocar suelo. Aterriza en una plataforma.",
		"Gravity always pulls you down. Without fuel the engine stops.": "La gravedad siempre te jala hacia abajo. Sin combustible, el motor se apaga.",
		"Hard": "Difícil",
		"Height: %d": "Altura: %d",
		"Highest level": "Nivel más alto",
		"Hold ⟲ or ⟳ to tilt the lander. Hold 🔥 to fire the engine: it pushes the way the nose points and burns fuel.": "Mantén ⟲ o ⟳ para inclinar el módulo. Mantén 🔥 para encender el motor: empuja hacia donde apunta la nariz y gasta combustible.",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Kill your sideways speed first, high up, then come straight down over the pad.": "Frena primero la velocidad lateral, en lo alto, y luego baja derecho sobre la plataforma.",
		"Land on the green pads, gently and upright, as many times as you can.": "Aterriza en las plataformas verdes, suave y derecho, todas las veces que puedas.",
		"Landed! +%d": "¡Aterrizaste! +%d",
		"Landings": "Aterrizajes",
		"Landings on ×5 pads": "Aterrizajes en ×5",
		"Level %d": "Nivel %d",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Moon Lander": "Alunizaje",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"Narrow pads pay more: ×2, ×3 and ×5. Fuel left over and a soft touchdown add to the score.": "Las plataformas angostas pagan más: ×2, ×3 y ×5. El combustible que sobra y un aterrizaje suave suman puntos.",
		"New best!": "¡Nuevo récord!",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of landers!": "¡Sin módulos!",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Sideways: %d": "Lateral: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Straighten up just before touchdown: the tilt counts as much as the speed.": "Enderézate justo antes de tocar suelo: la inclinación cuenta tanto como la velocidad.",
		"Tilt: %d°": "Inclinación: %d°",
		"To land safely: on a green pad, falling slower than 42, sliding slower than 26 and tilted less than about 12°. The numbers turn green when they're safe.": "Para aterrizar bien: en una plataforma verde, cayendo a menos de 42, deslizando a menos de 26 e inclinado menos de unos 12°. Los números se ponen verdes cuando son seguros.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use short bursts of the engine — long burns waste fuel and shoot you upwards.": "Usa el motor en ráfagas cortas: los encendidos largos gastan combustible y te lanzan hacia arriba.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses; Resume on the Home screen keeps your score, level and landers, and starts a fresh descent.": "⏸ pausa; Continuar en la pantalla de inicio conserva tus puntos, nivel y módulos, y empieza un descenso nuevo.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
