extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A wrong number turns red and counts as a mistake.": "Un número equivocado se pone rojo y cuenta como error.",
		"Avg. time": "Tiempo prom.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time": "Mejor tiempo",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Difficulty": "Dificultad",
		"Each correct square scores points, mistakes cost points, and fast solves earn a time bonus. Harder levels multiply your score.": "Cada casilla correcta suma puntos, los errores restan y resolver rápido da un bono de tiempo. Los niveles más difíciles multiplican tu puntaje.",
		"Easy": "Fácil",
		"Erase": "Borrar",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fill the grid so every row, column and 3×3 box has the numbers 1 to 9 exactly once.": "Completa la cuadrícula para que cada fila, columna y caja de 3×3 tenga los números del 1 al 9 una sola vez.",
		"Fill the grid. Every row, column and box: 1 to 9.": "Completa la cuadrícula. Cada fila, columna y caja: del 1 al 9.",
		"Generating puzzle...": "Generando el tablero...",
		"Hard": "Difícil",
		"Hint: %d": "Pistas: %d",
		"Loading...": "Cargando...",
		"Look for a number that can only go in one place in a row, column or box.": "Busca un número que solo pueda ir en un lugar de una fila, columna o caja.",
		"Look for a square where only one number fits, because the other eight are already in its row, column or box.": "Busca una casilla donde solo quepa un número, porque los otros ocho ya están en su fila, columna o caja.",
		"Medium": "Medio",
		"Mistakes": "Errores",
		"More": "Más",
		"New Puzzle (Same Difficulty)": "Nuevo tablero (misma dificultad)",
		"New best!": "¡Nuevo récord!",
		"New puzzle": "Nuevo sudoku",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Not solved yet": "Sin resolver aún",
		"Notes mode lets you pencil in small candidate numbers. Erase clears a square and Undo takes back your last move.": "El modo notas te deja anotar pequeños números candidatos. Borrar limpia una casilla y Deshacer anula tu último movimiento.",
		"Notes: Off": "Notas: No",
		"Notes: On": "Notas: Sí",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Perfect": "Perfectas",
		"Perfect games": "Partidas perfectas",
		"Play Again": "Jugar de nuevo",
		"Played": "Jugadas",
		"Player": "Jugador",
		"Puzzle Solved!": "¡Resuelto!",
		"Puzzles solved": "Puzzles resueltos",
		"Puzzles solved (%s)": "Puzzles resueltos (%s)",
		"Resume": "Continuar",
		"Scan each number from 1 to 9 across the whole grid before you start guessing.": "Revisa cada número del 1 al 9 en toda la cuadrícula antes de empezar a adivinar.",
		"Score": "Puntos",
		"Scores: points for each correct square, minus mistakes, plus a time bonus, times the difficulty (Expert ×3).": "Puntaje: puntos por cada casilla correcta, menos los errores, más un bono por tiempo, multiplicado por la dificultad (Experto ×3).",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Solve rate": "% resueltas",
		"Solved": "Resueltas",
		"Solved!": "¡Resuelto!",
		"Sudoku": "Sudoku",
		"Tap an empty square, then tap a number to place it.": "Toca una casilla vacía y luego un número para ponerlo.",
		"Time": "Tiempo",
		"Time: %s   Mistakes: %d\nFinal Score: %d": "Tiempo: %s   Errores: %d\nPuntaje final: %d",
		"Undo": "Deshacer",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use notes on harder puzzles: when two squares in a box can only be the same two numbers, those numbers can't go anywhere else in that box.": "Usa notas en los puzzles difíciles: cuando dos casillas de una caja solo pueden ser los mismos dos números, esos números no pueden ir en otro lugar de esa caja.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your best: %d": "Tu récord: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 Sudoku Home": "🏠 Inicio de Sudoku",
		"💡 Hint fills in one correct square — you get 3 per puzzle.": "💡 Pista completa una casilla correcta — tienes 3 por puzzle.",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📊 Statistics on the Sudoku menu shows your games, solves, best and average times and best scores for each difficulty.": "📊 Estadísticas, en el menú de Sudoku, muestra tus partidas, resueltas, mejores tiempos, tiempos promedio y mejores puntajes en cada dificultad.",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
