extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A wrong number turns red and counts as a mistake.": "Un número equivocado se pone rojo y cuenta como error.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Change Difficulty": "Cambiar dificultad",
		"Choose Difficulty": "Elige la dificultad",
		"Choose a difficulty": "Elige la dificultad",
		"Continue": "Continuar",
		"Continue (%s - %s)": "Continuar (%s - %s)",
		"Difficulty": "Dificultad",
		"Each correct square scores points, mistakes cost points, and fast solves earn a time bonus. Harder levels multiply your score.": "Cada casilla correcta suma puntos, los errores restan y resolver rápido da un bono de tiempo. Los niveles más difíciles multiplican tu puntaje.",
		"Easy": "Fácil",
		"Erase": "Borrar",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fill the grid so every row, column and 3×3 box has the numbers 1 to 9 exactly once.": "Completa la cuadrícula para que cada fila, columna y caja de 3×3 tenga los números del 1 al 9 una sola vez.",
		"Generating puzzle...": "Generando el tablero...",
		"Hard": "Difícil",
		"Hint: %d": "Pistas: %d",
		"Look for a number that can only go in one place in a row, column or box.": "Busca un número que solo pueda ir en un lugar de una fila, columna o caja.",
		"Look for a square where only one number fits, because the other eight are already in its row, column or box.": "Busca una casilla donde solo quepa un número, porque los otros ocho ya están en su fila, columna o caja.",
		"Medium": "Medio",
		"Mistakes": "Errores",
		"New Puzzle (Same Difficulty)": "Nuevo tablero (misma dificultad)",
		"New best!": "¡Nuevo récord!",
		"Notes mode lets you pencil in small candidate numbers. Erase clears a square and Undo takes back your last move.": "El modo notas te deja anotar pequeños números candidatos. Borrar limpia una casilla y Deshacer anula tu último movimiento.",
		"Notes: Off": "Notas: No",
		"Notes: On": "Notas: Sí",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Perfect games": "Partidas perfectas",
		"Play Again": "Jugar de nuevo",
		"Puzzle Solved!": "¡Resuelto!",
		"Puzzles solved": "Puzzles resueltos",
		"Puzzles solved (%s)": "Puzzles resueltos (%s)",
		"Resume": "Continuar",
		"Scan each number from 1 to 9 across the whole grid before you start guessing.": "Revisa cada número del 1 al 9 en toda la cuadrícula antes de empezar a adivinar.",
		"Score": "Puntos",
		"Solved!": "¡Resuelto!",
		"Sudoku": "Sudoku",
		"Tap an empty square, then tap a number to place it.": "Toca una casilla vacía y luego un número para ponerlo.",
		"Time": "Tiempo",
		"Time: %s   Mistakes: %d\nFinal Score: %d": "Tiempo: %s   Errores: %d\nPuntaje final: %d",
		"Undo": "Deshacer",
		"Use notes on harder puzzles: when two squares in a box can only be the same two numbers, those numbers can't go anywhere else in that box.": "Usa notas en los puzzles difíciles: cuando dos casillas de una caja solo pueden ser los mismos dos números, esos números no pueden ir en otro lugar de esa caja.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"💡 Hint fills in one correct square — you get 3 per puzzle.": "💡 Pista completa una casilla correcta — tienes 3 por puzzle.",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
