extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d moves, %d pushes": "%d movimientos, %d empujes",
		"A box against a wall can only slide along that wall. Make sure there's a goal along it.": "Una caja pegada a una pared solo puede deslizarse a lo largo de ella. Asegúrate de que haya una meta en esa pared.",
		"A box pushed into a corner can never come out again — unless the corner is a goal.": "Una caja empujada a una esquina ya no puede salir — salvo que la esquina sea una meta.",
		"Back to Hub": "Volver al inicio",
		"Before each push, check that you'll still be able to get behind the box for the next one.": "Antes de cada empujón, revisa que después puedas ponerte detrás de la caja para el siguiente.",
		"Best score": "Mejor puntaje",
		"Box Pusher": "Empuja cajas",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Highest level unlocked": "Nivel más alto desbloqueado",
		"Level %d": "Nivel %d",
		"Level Complete!": "¡Nivel completado!",
		"Levels solved": "Niveles resueltos",
		"Levels solved, all time.": "Niveles resueltos en total.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Moves: %d   Pushes: %d": "Movimientos: %d   Empujes: %d",
		"Multiplayer": "Multijugador",
		"Next Level": "Siguiente nivel",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pick up at your latest level": "Sigue en tu último nivel",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Push every box onto a goal square.": "Empuja cada caja hasta una casilla meta.",
		"Push every box onto a goal. You can't pull!": "Empuja cada caja a una meta. ¡No puedes jalar!",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solved!": "¡Resuelto!",
		"Stuck? ↶ Undo takes back a step, and Restart resets the level. Finished levels unlock the next one.": "¿Te trabaste? ↶ Deshacer anula un paso y Reiniciar vuelve a empezar el nivel. Cada nivel terminado desbloquea el siguiente.",
		"Swipe on the board (or use the arrow buttons) to walk one square at a time.": "Desliza sobre el tablero (o usa los botones de flecha) para caminar de a una casilla.",
		"The level is done when every box sits on a goal.": "El nivel se completa cuando todas las cajas están sobre una meta.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Walk into a box to push it. You can only push one box at a time, and you can never pull.": "Camina contra una caja para empujarla. Solo puedes empujar una caja a la vez, y nunca tirar de ella.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your level progress is kept. ⏸ pauses; Resume on the Home screen goes back to the level you were on.": "Tu avance de niveles se guarda. ⏸ pausa; Continuar en la pantalla de inicio vuelve al nivel en que estabas.",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"↺  Restart": "↺  Reiniciar",
		"▶  Continue": "▶  Continuar",
		"▶  Play": "▶  Jugar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📦 Box Pusher": "📦 Empuja cajas",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
