extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"3 lives · faster every level": "3 vidas · más rápido cada nivel",
		"A ghost that catches you costs a life. You have 3.": "Un fantasma que te atrapa te cuesta una vida. Tienes 3.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Blue ghosts run away and can be eaten: 200, 400, 800, then 1600 points. Their eyes fly home and they come back.": "Los fantasmas azules huyen y te los puedes comer: 200, 400, 800 y luego 1600 puntos. Sus ojos vuelven a casa y regresan.",
		"Clear all the dots for the next level: the ghosts get faster and stay blue for less time.": "Come todos los puntos para pasar de nivel: los fantasmas van más rápido y están azules menos tiempo.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Dots are 10 points. The big flashing power dots are 50 — and turn the ghosts blue for a few seconds.": "Cada punto vale 10. Los puntos grandes que parpadean valen 50 y vuelven azules a los fantasmas unos segundos.",
		"Draws": "Empates",
		"Each ghost hunts its own way: red chases you, pink cuts you off, cyan works with red, orange keeps its distance.": "Cada fantasma caza a su manera: el rojo te persigue, el rosa te corta el paso, el celeste ayuda al rojo y el naranja guarda distancia.",
		"Easy": "Fácil",
		"Eat every dot in the maze without getting caught by the ghosts.": "Cómete todos los puntos del laberinto sin que te atrapen los fantasmas.",
		"Eat every dot. Power dots turn the ghosts blue.": "Cómete todos los puntos. Los grandes vuelven azules a los fantasmas.",
		"Every now and then the ghosts scatter to their corners: use the gap to clear a crowded area.": "De vez en cuando los fantasmas se van a sus esquinas: aprovecha para limpiar una zona difícil.",
		"Expert": "Experto",
		"Game over!": "¡Fin del juego!",
		"Games played": "Partidas jugadas",
		"Ghosts can't turn back on themselves, so a corner is a good place to lose them.": "Los fantasmas no pueden darse la vuelta, así que una esquina es buen lugar para perderlos.",
		"Hard": "Difícil",
		"Highest level": "Nivel más alto",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Level %d": "Nivel %d",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Maze Muncher": "Come laberintos",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Ready!": "¡Listos!",
		"Resume": "Continuar",
		"Save the power dots until the ghosts are close — then eat them all.": "Guarda los puntos grandes hasta que los fantasmas estén cerca, y luego cómetelos a todos.",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Swipe anywhere to steer.": "Desliza en cualquier lugar para moverte.",
		"Swipe up, down, left or right anywhere on the screen to steer. A swipe before a corner turns you as soon as the way is open.": "Desliza hacia arriba, abajo, izquierda o derecha en cualquier parte de la pantalla. Si deslizas antes de una esquina, giras en cuanto el camino esté libre.",
		"The tunnel at the sides takes you across the maze — ghosts slow down in it.": "El túnel de los lados te lleva al otro extremo del laberinto; ahí los fantasmas van más lento.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses; Resume on the Home screen keeps your score, lives and the dots left.": "⏸ pausa; Continuar en la pantalla de inicio conserva tus puntos, vidas y los puntos que quedan.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
