extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d min": "%d min",
		"Best Blitz points": "Mejor puntaje Blitz",
		"Blitz runs": "Partidas Blitz",
		"Blitz: quick questions against the clock. Harder types earn more points, wrong multiple-choice answers lose a fraction, Skip costs 2 seconds.": "Blitz: preguntas rápidas contra reloj. Los tipos más difíciles suman más puntos, las respuestas incorrectas de opción múltiple restan una fracción y Saltar cuesta 2 segundos.",
		"Couldn't reach the server. Check your connection and try again.": "No se pudo conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.",
		"Each new kind of question starts with untimed instructions; the clock is paused while you read.": "Cada tipo de pregunta nuevo empieza con instrucciones sin tiempo; el reloj se pausa mientras lees.",
		"Easy": "Fácil",
		"English": "English",
		"Español": "Español",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"IQ Test: questions adapt to you. Get them right and they get harder; the score comes from how hard the questions you handled were, not from percent correct.": "Test de IQ: las preguntas se adaptan a ti. Si aciertas, se ponen más difíciles; el puntaje depende de qué tan difíciles eran las preguntas que resolviste, no del porcentaje de aciertos.",
		"Instant answers are scored wrong, so take the time to actually solve each one.": "Las respuestas instantáneas se cuentan como incorrectas, así que tómate el tiempo de resolver cada una.",
		"Leaving the app during a question counts that question as wrong. A test can't be paused or resumed later.": "Salir de la app durante una pregunta la cuenta como incorrecta. Un test no se puede pausar ni retomar más tarde.",
		"Measure nine kinds of smart with an adaptive test, and climb the boards once there is enough evidence.": "Mide nueve tipos de inteligencia con un test adaptativo y sube en los rankings cuando haya suficiente evidencia.",
		"Medium": "Medio",
		"Missing about half is normal: the test keeps raising the difficulty until you do.": "Fallar más o menos la mitad es normal: el test sube la dificultad hasta que pase.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Ranked counts for your scores: one ranked IQ attempt per section per day, and quitting still uses it. Practice is unlimited and never saved.": "Ranked cuenta para tus puntajes: un intento ranked de IQ por sección por día, y si abandonas igual se usa. La práctica es ilimitada y nunca se guarda.",
		"Ranked play needs an account, a player profile and age 16+.": "Para jugar ranked necesitas una cuenta, un perfil de jugador y 16 años o más.",
		"Retry": "Reintentar",
		"Sign in to take the IQ test: hub → ⚙ Options → Account. Scores are saved to your account.": "Inicia sesión para hacer el test de IQ: inicio → ⚙ Opciones → Cuenta. Los puntajes se guardan en tu cuenta.",
		"Something went wrong (%s). Try again.": "Algo salió mal (%s). Inténtalo de nuevo.",
		"Tap a region of the brain (or a numbered chip) to pick a section, or keep All sections for a mixed test.": "Toca una región del cerebro (o una ficha numerada) para elegir una sección, o deja Todas las secciones para un test mezclado.",
		"Tests taken": "Pruebas hechas",
		"Use headphones for the musical questions.": "Usa auriculares para las preguntas musicales.",
		"Voodoo IQ": "Voodoo IQ",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
