extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d min": "%d min",
		"Back": "Volver",
		"Back to the question": "Volver a la pregunta",
		"Best Blitz points": "Mejor puntaje Relámpago",
		"Blitz runs": "Partidas Relámpago",
		"Can't play sound? The musical questions offer 🔇: skip them for the rest of the test (they count only for the Musical section) or end the test.": "¿No puedes usar sonido? Las preguntas musicales tienen 🔇: sáltalas por el resto del test (solo cuentan para la sección Musical) o termina el test.",
		"Continue": "Continuar",
		"Couldn't reach the server. Check your connection and try again.": "No se pudo conectar con el servidor. Revisa tu conexión e inténtalo de nuevo.",
		"Counts for the leaderboard. Your last 3 ranked tests in each section count, so one lucky run can't carry you.": "Cuenta para el ranking. Cuentan tus últimos 3 tests ranked de cada sección, así que una partida con suerte no alcanza.",
		"Does this test count?": "¿Este test cuenta?",
		"Don't judge whether you agree with the conclusion. Pick the description of the mistake in HOW the argument reasons.": "No juzgues si estás de acuerdo con la conclusión. Elige la descripción del error en CÓMO razona el argumento.",
		"Each new kind of question starts with untimed instructions; the clock is paused while you read.": "Cada tipo de pregunta nuevo empieza con instrucciones sin tiempo; el reloj se pausa mientras lees.",
		"Easy": "Fácil",
		"End the test": "Terminar el test",
		"English": "English",
		"Español": "Español",
		"Example": "Ejemplo",
		"Existential questions are pure logic: 💡 Example shows how to read them.": "Las preguntas existenciales son pura lógica: 💡 Ejemplo muestra cómo leerlas.",
		"Expert": "Experto",
		"Extra large": "Extra grande",
		"Finish": "Terminar",
		"Finish the test?": "¿Terminar el test?",
		"Forget the real world: the statements are the only facts. Picture each group as a circle. A conclusion is right only if it is true in EVERY way the circles could be drawn.": "Olvida el mundo real: las afirmaciones son los únicos hechos. Imagina cada grupo como un círculo. Una conclusión es correcta solo si es verdad en TODAS las formas en que se podrían dibujar los círculos.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"I can't play sound right now": "Ahora no puedo usar sonido",
		"IQ Test": "Test de IQ",
		"IQ Test: questions adapt to you. Get them right and they get harder; the score comes from how hard the questions you handled were, not from percent correct.": "Test de IQ: las preguntas se adaptan a ti. Si aciertas, se ponen más difíciles; el puntaje depende de qué tan difíciles eran las preguntas que resolviste, no del porcentaje de aciertos.",
		"Instant answers are scored wrong, so take the time to actually solve each one.": "Las respuestas instantáneas se cuentan como incorrectas, así que tómate el tiempo de resolver cada una.",
		"Large": "Grande",
		"Leaderboards show everyone's real estimate, high or low, with its ± range. ✓ marks a score with enough evidence behind it: 15+ questions and a tight ±.": "Los rankings muestran la estimación real de cada uno, alta o baja, con su rango ±. ✓ marca un puntaje con suficiente evidencia: 15+ preguntas y un ± ajustado.",
		"Leaving the app during a question counts that question as wrong. A test can't be resumed after you leave it.": "Salir de la app durante una pregunta la cuenta como incorrecta. Un test no se puede retomar después de salir.",
		"Logic + Spatial + Verbal combined, highest first. Everyone with all three is shown; ✓ = verified (sessions on 2 days that agree).": "Lógica + Espacial + Verbal combinadas, de mayor a menor. Se muestra a todos los que tienen las tres; ✓ = verificado (sesiones en 2 días que coinciden).",
		"Measure nine kinds of smart with an adaptive test, and climb the boards once there is enough evidence.": "Mide nueve tipos de inteligencia con un test adaptativo y sube en los rankings cuando haya suficiente evidencia.",
		"Medium": "Medio",
		"Missing about half is normal: the test keeps raising the difficulty until you do.": "Fallar más o menos la mitad es normal: el test sube la dificultad hasta que pase.",
		"Musical question skipped": "Pregunta musical saltada",
		"No sound right now?": "¿Sin sonido ahora?",
		"No sound?": "¿Sin sonido?",
		"Normal": "Normal",
		"Not saved": "No se guarda",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Ranked counts for the leaderboards: your last 3 ranked tests in each section are combined, and a quit test still counts. Practice is never saved.": "Ranked cuenta para los rankings: se combinan tus últimos 3 tests ranked de cada sección, y un test abandonado igual cuenta. La práctica nunca se guarda.",
		"Ranked play needs an account, a player profile and age 16+.": "Para jugar ranked necesitas una cuenta, un perfil de jugador y 16 años o más.",
		"Retry": "Reintentar",
		"Saved, on the boards": "Se guarda, va al ranking",
		"See my score": "Ver mi puntaje",
		"Sign in to take the IQ test: hub → ⚙ Options → Account. Scores are saved to your account.": "Inicia sesión para hacer el test de IQ: inicio → ⚙ Opciones → Cuenta. Los puntajes se guardan en tu cuenta.",
		"Skip musical questions": "Saltar las preguntas musicales",
		"Something went wrong (%s). Try again.": "Algo salió mal (%s). Inténtalo de nuevo.",
		"Sound": "Sonido",
		"Speed Round: quick questions against the clock. Harder types earn more points, wrong multiple-choice answers lose a fraction, Skip costs 2 seconds.": "Relámpago: preguntas rápidas contra reloj. Los tipos más difíciles suman más puntos, las respuestas incorrectas de opción múltiple restan una fracción y Saltar cuesta 2 segundos.",
		"Tap a region of the brain (or a numbered chip) to pick a section, or keep All sections for a mixed test.": "Toca una región del cerebro (o una ficha numerada) para elegir una sección, o deja Todas las secciones para un test mezclado.",
		"Tests taken": "Pruebas hechas",
		"Text size": "Tamaño del texto",
		"The clock is stopped and the question is hidden until you continue.": "El reloj está detenido y la pregunta oculta hasta que continúes.",
		"This ranked test will be scored with the answers you gave.": "Este test ranked se va a puntuar con las respuestas que diste.",
		"This section is all musical questions, so it needs sound. End the test now and come back when you can listen.": "Esta sección es solo de preguntas musicales, así que necesita sonido. Termina el test ahora y vuelve cuando puedas escuchar.",
		"Use headphones for the musical questions.": "Usa auriculares para las preguntas musicales.",
		"Voodoo IQ": "Voodoo IQ",
		"You can skip the musical questions for the rest of this test. Each one counts as unanswered for the Musical section only: your IQ score (Logic, Spatial and Verbal) isn't affected.": "Puedes saltar las preguntas musicales por el resto de este test. Cada una cuenta como sin responder solo para la sección Musical: tu puntaje de IQ (Lógica, Espacial y Verbal) no se ve afectado.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You'll see your score now. Every answer you gave counts.": "Vas a ver tu puntaje ahora. Cuentan todas las respuestas que diste.",
		"Your last 3 ranked tests in this section (90 days), highest first. ✓ = enough questions for a tight ±.": "Tus últimos 3 tests ranked de esta sección (90 días), de mayor a menor. ✓ = suficientes preguntas para un ± ajustado.",
		"Your turn (%s)": "Tu turno (%s)",
		"“All poets are dreamers.” + “All dreamers are mortals.”  →  “All poets are mortals.” must be true.": "“Todos los poetas son soñadores.” + “Todos los soñadores son mortales.”  →  “Todos los poetas son mortales.” tiene que ser verdad.",
		"“My grandmother took this herb and got better, so it cures everyone.”  →  Generalizes from too few cases.": "“Mi abuela tomó esta hierba y se curó, así que cura a todos.”  →  Generaliza a partir de muy pocos casos.",
		"“No ghosts are mortals.” + “All poets are mortals.”  →  “No poets are ghosts.” must be true.": "“Ningún fantasma es mortal.” + “Todos los poetas son mortales.”  →  “Ningún poeta es fantasma.” tiene que ser verdad.",
		"“Nobody has proven that ghosts don't exist, so they must exist.”  →  Not disproven, so it must be true.": "“Nadie demostró que los fantasmas no existen, así que existen.”  →  No se refutó, así que debe ser verdad.",
		"“Some poets are ghosts.” + “Some ghosts are sages.”  →  nothing is guaranteed: the poets who are ghosts may not be the ghosts who are sages. Pick “None”.": "“Algunos poetas son fantasmas.” + “Algunos fantasmas son sabios.”  →  nada está garantizado: los poetas que son fantasmas pueden no ser los fantasmas que son sabios. Elige “Ninguna”.",
		"∞ (the default time) has no clock and no per-question limit: keep answering as long as you like and tap Finish. Every answer counts, so long runs reach the boards faster. If you close the app instead, the test is scored the next time you play.": "∞ (el tiempo por defecto) no tiene reloj ni límite por pregunta: responde todo lo que quieras y toca Terminar. Cuenta cada respuesta, así que las partidas largas llegan antes al ranking. Si cierras la app, el test se puntúa la próxima vez que juegues.",
		"∞ No time limit: answer as many questions as you like and tap Finish when you're done. Every answer counts, so long runs reach the boards faster.": "∞ Sin límite de tiempo: responde todas las preguntas que quieras y toca Terminar cuando quieras. Cuenta cada respuesta, así que las partidas largas llegan antes al ranking.",
		"⏸ pauses a test: the clock stops and the question is hidden, and you can change the text size and sound there.": "⏸ pausa el test: el reloj se detiene y la pregunta se oculta, y ahí puedes cambiar el tamaño del texto y el sonido.",
		"🏆 Leaderboards: the IQ board, the 9-Mind board, one board per section and the Speed Round bests, filtered by age, country and language. Nothing is capped or hidden: everyone is ranked by their real estimate, and ✓ marks scores with enough evidence behind them.": "🏆 Rankings: el ranking de IQ, el de 9-Mentes, uno por sección y los mejores de Relámpago, filtrados por edad, país e idioma. Nada tiene tope ni se oculta: todos se ordenan por su estimación real, y ✓ marca los puntajes con suficiente evidencia.",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
