extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s (3 Man) drinks 1.": "%s (el 3 Man) toma 1.",
		"%s (3 Man) drinks twice.": "%s (el 3 Man) toma 2.",
		"%s becomes 3 Man!": "¡%s es el nuevo 3 Man!",
		"%s drinks 1 (to your left).": "%s toma 1 (a tu izquierda).",
		"%s drinks 1 (to your right).": "%s toma 1 (a tu derecha).",
		"%s is no longer 3 Man!": "¡%s ya no es el 3 Man!",
		"%s is still 3 Man.": "%s sigue siendo el 3 Man.",
		"3 Man: Player %d": "3 Man: Jugador %d",
		"3 Man: not assigned yet": "3 Man: nadie todavía",
		"3️⃣ Three Man": "3️⃣ Three Man",
		"Doubles! Give out %d drinks, your choice.": "¡Dobles! Reparte %d tragos a quien quieras.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Give out 3 drinks, your choice.": "Reparte 3 tragos a quien quieras.",
		"Hard": "Difícil",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Next Player ➜": "Siguiente jugador ➜",
		"No one is 3 Man yet — stays that way.": "Todavía no hay 3 Man — sigue así.",
		"Nothing happens.": "No pasa nada.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Player %d": "Jugador %d",
		"Player %d goes first!": "¡Empieza el jugador %d!",
		"Player %d's turn": "Turno del jugador %d",
		"Roll 1 die each — lowest goes first (ties re-roll).\nThen pass the phone: roll 2 dice on your turn.\n7 = right drinks · 11 = left drinks · Doubles = give that many\nAny 3 (or 2&1) = become/feed 3 Man. Keep rolling while someone drinks!": "Cada uno tira 1 dado — el más bajo empieza (si empatan, se vuelve a tirar).\nLuego pasen el teléfono: en tu turno tira 2 dados.\n7 = toma el de la derecha · 11 = toma el de la izquierda · Dobles = reparte esa cantidad\nCualquier 3 (o 2 y 1) = serás o alimentarás al 3 Man. ¡Sigue tirando mientras alguien tome!",
		"Roll for First": "Tirar para empezar",
		"Rolling to see who goes first…": "Tirando para ver quién empieza…",
		"Start Game": "Empezar partida",
		"Start Playing ➜": "Empezar a jugar ➜",
		"Tied: %s — reroll!": "Empate: %s — ¡a tirar de nuevo!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🎲 Roll": "🎲 Tirar",
		"🎲 Roll Again": "🎲 Tirar otra vez",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
