extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"A narrow tower is fast to miss: chase perfect drops to earn width back.": "Una torre angosta es fácil de fallar: busca caídas perfectas para recuperar ancho.",
		"A slab slides back and forth above the tower. Tap anywhere to drop it.": "Un bloque se desliza de un lado a otro sobre la torre. Toca en cualquier lugar para soltarlo.",
		"Any part that hangs over the slab below is sliced off and falls — so the next slab is narrower.": "Lo que sobresale del bloque de abajo se corta y cae, así que el siguiente bloque es más angosto.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Build the tallest tower you can.": "Construye la torre más alta que puedas.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Find a rhythm — the slab takes the same time to cross each way.": "Encuentra el ritmo: el bloque tarda lo mismo en cruzar en cada sentido.",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Height: %d": "Altura: %d",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"How high can you build?": "¿Qué tan alto puedes llegar?",
		"Line it up almost exactly for a Perfect drop: nothing is sliced. Three perfect drops in a row win back a little width.": "Alinéalo casi exacto para una caída Perfecta: no se corta nada. Tres perfectas seguidas te devuelven un poco de ancho.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Miss the tower completely and the game is over. The slabs slide faster as the tower grows.": "Si fallas la torre por completo, se acaba el juego. Los bloques van más rápido a medida que la torre crece.",
		"More": "Más",
		"Most perfect drops in a row": "Más caídas perfectas seguidas",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Perfect ×%d": "Perfecto ×%d",
		"Perfect!": "¡Perfecto!",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Stack Tower": "Torre",
		"Tap anywhere to drop.": "Toca en cualquier lugar para soltar.",
		"Tap to drop. Line it up — the overhang gets sliced off.": "Toca para soltar. Alinéalo: lo que sobresale se corta.",
		"The slab missed!": "¡El bloque no cayó en la torre!",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Watch the edge of the slab, not its middle: drop when its edge meets the edge below.": "Mira el borde del bloque, no el centro: suéltalo cuando su borde coincida con el de abajo.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the tower; Resume on the Home screen carries on.": "⏸ pausa y guarda la torre; Continuar en la pantalla de inicio sigue la partida.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
