extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Every cage adds up.": "Todas las jaulas cuadran.",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"New": "Nuevo",
		"Next Puzzle": "Siguiente puzzle",
		"No repeats in any row or column. Each cage must make its number using its operation.": "Sin repetir en filas ni columnas. Cada jaula debe dar su número con su operación.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Size: %d×%d": "Tamaño: %d×%d",
		"Solved!": "¡Resuelto!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🔟 Calcudoku": "🔟 Calcudoku",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
