extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"A one-square cage just gives you its number.": "Una jaula de una sola casilla te da su número directamente.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Calcudoku": "Calcudoku",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Each outlined cage shows a target and an operation (+ − × ÷). Its numbers must combine to make the target.": "Cada jaula marcada muestra un objetivo y una operación (+ − × ÷). Sus números deben combinarse para dar el objetivo.",
		"Easy": "Fácil",
		"Every cage adds up.": "Todas las jaulas cuadran.",
		"Every row and column once. Every cage hits its target.": "Cada número una vez por fila y columna. Cada jaula llega a su objetivo.",
		"Expert": "Experto",
		"Fill the grid so every row and column has each number once, and every cage makes its target.": "Completa la cuadrícula para que cada fila y columna tenga cada número una vez, y cada jaula dé su objetivo.",
		"Fill the one-square cages first — they're free.": "Completa primero las jaulas de una casilla — son gratis.",
		"For − and ÷, start with the bigger number: a \"2÷\" cage could be 4 and 2.": "Para − y ÷, empieza por el número más grande: una jaula \"2÷\" podría ser 4 y 2.",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"In a 4×4 grid use 1–4, in a 5×5 use 1–5, and so on. No number repeats in any row or column.": "En una cuadrícula de 4×4 usa 1–4, en una de 5×5 usa 1–5, y así. Ningún número se repite en una fila o columna.",
		"Large × targets have few options: 12× in two squares on a 4×4 can only be 3 and 4.": "Los objetivos × grandes tienen pocas opciones: 12× en dos casillas de un 4×4 solo puede ser 3 y 4.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No repeats in any row or column. Each cage must make its number using its operation.": "Sin repetir en filas ni columnas. Cada jaula debe dar su número con su operación.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Once a row has only one number missing, it's whatever is left over.": "Cuando a una fila le falta un solo número, es el que sobra.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Puzzles solved, all sizes.": "Tableros resueltos, todos los tamaños.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Size: %d×%d": "Tamaño: %d×%d",
		"Solved!": "¡Resuelto!",
		"Tap a square, then a number to fill it (⌫ clears it). Repeated numbers are shown in red.": "Toca una casilla y luego un número para llenarla (⌫ la borra). Los números repetidos se muestran en rojo.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use the size button to try a bigger grid.": "Usa el botón de tamaño para probar una cuadrícula más grande.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the puzzle; Resume on the Home screen picks it up.": "⏸ pausa y guarda la partida; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
		"🔟 Calcudoku": "🔟 Calcudoku",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
