extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A one-square cage just gives you its number.": "Una jaula de una sola casilla te da su número directamente.",
		"Back to Hub": "Volver al inicio",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Calcudoku": "Calcudoku",
		"Each outlined cage shows a target and an operation (+ − × ÷). Its numbers must combine to make the target.": "Cada jaula marcada muestra un objetivo y una operación (+ − × ÷). Sus números deben combinarse para dar el objetivo.",
		"Easy": "Fácil",
		"Every cage adds up.": "Todas las jaulas cuadran.",
		"Expert": "Experto",
		"Fill the grid so every row and column has each number once, and every cage makes its target.": "Completa la cuadrícula para que cada fila y columna tenga cada número una vez, y cada jaula dé su objetivo.",
		"Fill the one-square cages first — they're free.": "Completa primero las jaulas de una casilla — son gratis.",
		"For − and ÷, start with the bigger number: a \"2÷\" cage could be 4 and 2.": "Para − y ÷, empieza por el número más grande: una jaula \"2÷\" podría ser 4 y 2.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"In a 4×4 grid use 1–4, in a 5×5 use 1–5, and so on. No number repeats in any row or column.": "En una cuadrícula de 4×4 usa 1–4, en una de 5×5 usa 1–5, y así. Ningún número se repite en una fila o columna.",
		"Large × targets have few options: 12× in two squares on a 4×4 can only be 3 and 4.": "Los objetivos × grandes tienen pocas opciones: 12× en dos casillas de un 4×4 solo puede ser 3 y 4.",
		"Medium": "Medio",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"No repeats in any row or column. Each cage must make its number using its operation.": "Sin repetir en filas ni columnas. Cada jaula debe dar su número con su operación.",
		"Once a row has only one number missing, it's whatever is left over.": "Cuando a una fila le falta un solo número, es el que sobra.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Puzzles solved": "Puzzles resueltos",
		"Size: %d×%d": "Tamaño: %d×%d",
		"Solved!": "¡Resuelto!",
		"Tap a square, then a number to fill it (⌫ clears it). Repeated numbers are shown in red.": "Toca una casilla y luego un número para llenarla (⌫ la borra). Los números repetidos se muestran en rojo.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Use the size button to try a bigger grid.": "Usa el botón de tamaño para probar una cuadrícula más grande.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🔟 Calcudoku": "🔟 Calcudoku",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
