extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d discs": "%d discos",
		"%d moves": "%d movimientos",
		"A perfect solve!": "¡Solución perfecta!",
		"Add a Disc": "Añadir un disco",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Most discs solved": "Más discos resueltos",
		"Move the whole tower of discs to the right-hand peg.": "Mueve toda la torre de discos a la varilla de la derecha.",
		"Move the whole tower to the right peg. Never a big disc on a small one.": "Pasa toda la torre a la varilla derecha. Nunca un disco grande sobre uno chico.",
		"Move the whole tower to the right peg. Never put a bigger disc on a smaller one.": "Lleva toda la torre a la varilla derecha. Nunca pongas un disco grande sobre uno más chico.",
		"Moves: %d   (best possible: %d)": "Movimientos: %d   (mínimo posible: %d)",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Number of discs": "Número de discos",
		"On the turns in between, make the only legal move that doesn't touch the smallest disc.": "En los turnos intermedios, haz el único movimiento válido que no toca el disco más chico.",
		"Only one disc moves at a time, and a bigger disc can never sit on a smaller one.": "Se mueve un disco a la vez, y un disco grande nunca puede ir sobre uno más chico.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Perfect solves": "Soluciones perfectas",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solved!": "¡Resuelto!",
		"Tap a peg to lift its top disc, then tap another peg to put it down.": "Toca una varilla para levantar su disco de arriba y luego toca otra para dejarlo.",
		"The smallest disc moves every other turn, always around the pegs in the same direction.": "El disco más chico se mueve un turno sí y uno no, siempre dando la vuelta a las varillas en la misma dirección.",
		"Think big: to move a tower of 5, first move the top 4 out of the way.": "Piensa en grande: para mover una torre de 5, primero quita del medio los 4 de arriba.",
		"Tower of Hanoi": "Torre de Hanói",
		"Towers moved, all sizes.": "Torres movidas, todos los tamaños.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use − and + to change the number of discs. The best possible number of moves is shown.": "Usa − y + para cambiar la cantidad de discos. Se muestra la mejor cantidad posible de movimientos.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"With an odd number of discs, move the smallest one to the right-hand peg first; with an even number, to the middle one.": "Con una cantidad impar de discos, mueve primero el más chico a la varilla de la derecha; con una cantidad par, a la del medio.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best: %d": "Tu récord: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the tower; Resume on the Home screen picks it up.": "⏸ pausa y guarda la torre; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
		"🗼 Tower of Hanoi": "🗼 Torre de Hanói",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
