extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d discs": "%d discos",
		"%d moves": "%d movimientos",
		"A perfect solve!": "¡Solución perfecta!",
		"Add a Disc": "Añadir un disco",
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Most discs solved": "Más discos resueltos",
		"Move the whole tower of discs to the right-hand peg.": "Mueve toda la torre de discos a la varilla de la derecha.",
		"Move the whole tower to the right peg. Never put a bigger disc on a smaller one.": "Lleva toda la torre a la varilla derecha. Nunca pongas un disco grande sobre uno más chico.",
		"Moves: %d   (best possible: %d)": "Movimientos: %d   (mínimo posible: %d)",
		"On the turns in between, make the only legal move that doesn't touch the smallest disc.": "En los turnos intermedios, haz el único movimiento válido que no toca el disco más chico.",
		"Only one disc moves at a time, and a bigger disc can never sit on a smaller one.": "Se mueve un disco a la vez, y un disco grande nunca puede ir sobre uno más chico.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Perfect solves": "Soluciones perfectas",
		"Play Again": "Jugar de nuevo",
		"Puzzles solved": "Puzzles resueltos",
		"Restart": "Reiniciar",
		"Solved!": "¡Resuelto!",
		"Tap a peg to lift its top disc, then tap another peg to put it down.": "Toca una varilla para levantar su disco de arriba y luego toca otra para dejarlo.",
		"The smallest disc moves every other turn, always around the pegs in the same direction.": "El disco más chico se mueve un turno sí y uno no, siempre dando la vuelta a las varillas en la misma dirección.",
		"Think big: to move a tower of 5, first move the top 4 out of the way.": "Piensa en grande: para mover una torre de 5, primero quita del medio los 4 de arriba.",
		"Tower of Hanoi": "Torre de Hanói",
		"Use − and + to change the number of discs. The best possible number of moves is shown.": "Usa − y + para cambiar la cantidad de discos. Se muestra la mejor cantidad posible de movimientos.",
		"With an odd number of discs, move the smallest one to the right-hand peg first; with an even number, to the middle one.": "Con una cantidad impar de discos, mueve primero el más chico a la varilla de la derecha; con una cantidad par, a la del medio.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your best: %d": "Tu récord: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"🗼 Tower of Hanoi": "🗼 Torre de Hanói",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
