extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d discs": "%d discos",
		"%d moves": "%d movimientos",
		"A perfect solve!": "¡Solución perfecta!",
		"Add a Disc": "Añadir un disco",
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Move the whole tower to the right peg. Never put a bigger disc on a smaller one.": "Lleva toda la torre a la varilla derecha. Nunca pongas un disco grande sobre uno más chico.",
		"Moves: %d   (best possible: %d)": "Movimientos: %d   (mínimo posible: %d)",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Solved!": "¡Resuelto!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your best: %d": "Tu récord: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"🗼 Tower of Hanoi": "🗼 Torre de Hanói",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
