extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d dice": "%d dados",
		"%d × face %d": "%d × cara %d",
		"%s bids %s.": "%s apuesta %s.",
		"%s calls Liar on %s!": "¡%s dice «mentira» a %s!",
		"%s is thinking...": "%s está pensando...",
		"%s wins!": "¡Gana %s!",
		"%s — %d dice": "%s — %d dados",
		"Back to Hub": "Volver al inicio",
		"Bid %s": "Apostar %s",
		"CPU %d": "CPU %d",
		"Current bid: %s by %s.": "Apuesta actual: %s de %s.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Liar!": "¡Mentira!",
		"Medium": "Medio",
		"Next Round": "Siguiente ronda",
		"No bid yet.": "Todavía no hay apuesta.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"There are %d. %s loses a die.": "Hay %d. %s pierde un dado.",
		"You": "Tú",
		"You bid %s.": "Apostaste %s.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You're out of dice!": "¡Te quedaste sin dados!",
		"You're out — watching the computers.": "Quedaste fuera — mirando a las computadoras.",
		"Your move.": "Te toca.",
		"Your turn (%s)": "Tu turno (%s)",
		"🤥 Liar's Dice": "🤥 Dudo",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
