extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"As you get longer, follow your own tail — it always moves out of the way.": "Cuando seas largo, sigue tu propia cola — siempre se quita del camino.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Each piece of food makes you longer and scores a point.": "Cada comida te hace más largo y suma un punto.",
		"Easy": "Fácil",
		"Eat as much food as you can without crashing.": "Come toda la comida que puedas sin chocar.",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fill the entire board and you win!": "¡Llena todo el tablero y ganas!",
		"Game Over!\nScore: %d": "¡Fin del juego!\nPuntos: %d",
		"Games played": "Partidas jugadas",
		"Go around the edges in wide loops rather than zig-zagging through the middle.": "Recorre los bordes en vueltas amplias en lugar de zigzaguear por el medio.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Plan an escape route before you grab food in a tight spot.": "Planea una salida antes de ir por comida en un lugar estrecho.",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Running into a wall or your own body ends the game.": "Chocar contra una pared o contra tu propio cuerpo termina el juego.",
		"Score: %d": "Puntos: %d",
		"Snake": "Snake",
		"Start": "Empezar",
		"Use the arrow pad to steer (arrow keys work too). The snake keeps moving on its own.": "Usa las flechas de la pantalla para girar (las del teclado también sirven). La serpiente avanza sola.",
		"You filled the board!\nScore: %d": "¡Llenaste el tablero!\nPuntos: %d",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🐍 Snake": "🐍 Snake",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
