extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"\n%s wins!": "\n¡Ganan las %s!",
		" — Check!": " — ¡Jaque!",
		"%s's turn%s": "Turno de %s%s",
		"Back to Hub": "Volver al inicio",
		"Black": "Negras",
		"Checkmate!": "¡Jaque mate!",
		"Chess": "Ajedrez",
		"Draw — 50-move rule": "Tablas — regla de 50 movimientos",
		"Draw — insufficient material": "Tablas — material insuficiente",
		"Draw — same position 3 times": "Tablas — misma posición 3 veces",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game over": "Fin del juego",
		"Hard": "Difícil",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Promote to:": "Coronar como:",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Stalemate — draw": "Rey ahogado — tablas",
		"White": "Blancas",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"♟️ Chess": "♟️ Ajedrez",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
