extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"\n%s wins!": "\n¡Ganan las %s!",
		" — Check!": " — ¡Jaque!",
		"%s's turn%s": "Turno de %s%s",
		"Back to Hub": "Volver al inicio",
		"Before every move, check what your opponent's last move threatens.": "Antes de cada jugada, revisa qué amenaza la última jugada de tu rival.",
		"Black": "Negras",
		"Black wins": "Victorias de las negras",
		"Castle early to keep your king safe.": "Enroca temprano para proteger a tu rey.",
		"Castling, en passant and pawn promotion are all allowed.": "Se permiten el enroque, la captura al paso y la coronación de peones.",
		"Checkmate your opponent's king: attack it so it has no way to escape.": "Dale jaque mate al rey rival: atácalo de modo que no tenga escapatoria.",
		"Checkmate!": "¡Jaque mate!",
		"Chess": "Ajedrez",
		"Control the centre with your pawns and pieces early on.": "Controla el centro con tus peones y piezas desde el principio.",
		"Develop your knights and bishops before moving the queen out.": "Desarrolla tus caballos y alfiles antes de sacar a la dama.",
		"Draw — 50-move rule": "Tablas — regla de 50 movimientos",
		"Draw — insufficient material": "Tablas — material insuficiente",
		"Draw — same position 3 times": "Tablas — misma posición 3 veces",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game over": "Fin del juego",
		"Hard": "Difícil",
		"King: one square any way. Queen: any distance in any direction. Rook: straight lines. Bishop: diagonals. Knight: an L-shape, jumping over pieces. Pawn: one square forward (two on its first move), capturing diagonally.": "Rey: una casilla en cualquier dirección. Dama: cualquier distancia en cualquier dirección. Torre: en línea recta. Alfil: en diagonal. Caballo: en forma de L, saltando piezas. Peón: una casilla hacia adelante (dos en su primer movimiento) y captura en diagonal.",
		"Medium": "Medio",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Promote to:": "Coronar como:",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Stalemate — draw": "Rey ahogado — tablas",
		"Tap a piece to see where it can go, then tap a highlighted square.": "Toca una pieza para ver adónde puede ir y luego toca una casilla resaltada.",
		"Tap 🌐 Play Online to play a friend on another phone with a room code.": "Toca 🌐 Jugar en línea para jugar con un amigo en otro teléfono usando un código de sala.",
		"Two players share the phone. White moves first.": "Dos jugadores comparten el teléfono. Empiezan las blancas.",
		"White": "Blancas",
		"White wins": "Victorias de las blancas",
		"You can never leave your own king in check. No legal move while not in check is stalemate — a draw. So are repeating a position 3 times, 50 moves without a capture or pawn move, and too few pieces to checkmate.": "Nunca puedes dejar a tu propio rey en jaque. No tener movimientos sin estar en jaque es rey ahogado — tablas. También son tablas repetir una posición 3 veces, 50 movimientos sin capturas ni movimientos de peón, y no tener piezas suficientes para dar mate.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"♟️ Chess": "♟️ Ajedrez",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
