extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d moves": "%d movimientos",
		"Average time": "Tiempo promedio",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time": "Mejor tiempo",
		"Build down the seven columns in alternating colours: a red 6 goes on a black 7.": "Construye hacia abajo en las siete columnas alternando colores: un 6 rojo va sobre un 7 negro.",
		"Classic Klondike: build up the foundations from Ace to King.": "Klondike clásico: arma las bases del as al rey.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't rush cards to the foundations — low cards are often still needed to build on.": "No apures las cartas a las bases — muchas veces las bajas todavía sirven para construir.",
		"Draw one": "Robar de a una",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Games won": "Partidas ganadas",
		"Games won, all time.": "Partidas ganadas en total.",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Move all 52 cards onto the four foundation piles, each suit from Ace up to King.": "Pasa las 52 cartas a las cuatro pilas de base, cada palo del As al Rey.",
		"Moves": "Movimientos",
		"Moves: %d": "Movimientos: %d",
		"Moves: 0": "Movimientos: 0",
		"Multiplayer": "Multijugador",
		"New Deal": "Nueva mano",
		"New best!": "¡Nuevo récord!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"No wins yet. Finish a deal and it shows up here.": "Aún no hay victorias. Termina una partida y aparecerá aquí.",
		"Once every card is face up and the stock is used up, the rest fly up to the foundations by themselves.": "Cuando todas las cartas están boca arriba y el mazo se acabó, el resto vuela solo a las bases.",
		"Only a King (or a run starting with a King) can go into an empty column.": "Solo un Rey (o una escalera que empiece con un Rey) puede ir a una columna vacía.",
		"Only empty a column when you have a King ready to move into it.": "Vacía una columna solo cuando tengas un Rey listo para ocuparla.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Recent wins": "Victorias recientes",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solitaire": "Solitario",
		"Tap a card to pick it up (with any cards on top of it), then tap where it should go.": "Toca una carta para tomarla (con las cartas que tenga encima) y luego toca adónde debe ir.",
		"Tap the stock to turn over a card. When it runs out, tap it again to turn the pile back over.": "Toca el mazo para dar vuelta una carta. Cuando se acabe, tócalo otra vez para volver a darlo vuelta.",
		"Time": "Tiempo",
		"Turning over face-down cards in the columns is usually the best move.": "Dar vuelta cartas boca abajo en las columnas suele ser la mejor jugada.",
		"Undo": "Deshacer",
		"Undo takes back a move. New Deal starts over.": "Deshacer anula un movimiento. Nueva mano empieza de nuevo.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win #%d": "Victoria n.º %d",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"Wins from before the history was kept: %d": "Victorias de antes del historial: %d",
		"Work on the columns with the most face-down cards first.": "Trabaja primero en las columnas con más cartas boca abajo.",
		"You Win!": "¡Ganaste!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock and keeps the deal; Resume on the Home screen picks it up.": "⏸ pausa el reloj y guarda la mano; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🃏  New deal": "🃏  Nueva mano",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📜 History": "📜 Historial",
		"📜 History on the Home screen lists every win with its time and moves.": "📜 Historial, en la pantalla de inicio, muestra cada victoria con su tiempo y sus movimientos.",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
