extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best time": "Mejor tiempo",
		"Build down the seven columns in alternating colours: a red 6 goes on a black 7.": "Construye hacia abajo en las siete columnas alternando colores: un 6 rojo va sobre un 7 negro.",
		"Don't rush cards to the foundations — low cards are often still needed to build on.": "No apures las cartas a las bases — muchas veces las bajas todavía sirven para construir.",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Games won": "Partidas ganadas",
		"Hard": "Difícil",
		"Medium": "Medio",
		"Move all 52 cards onto the four foundation piles, each suit from Ace up to King.": "Pasa las 52 cartas a las cuatro pilas de base, cada palo del As al Rey.",
		"Moves: %d": "Movimientos: %d",
		"Moves: 0": "Movimientos: 0",
		"New Deal": "Nueva mano",
		"New best!": "¡Nuevo récord!",
		"Only a King (or a run starting with a King) can go into an empty column.": "Solo un Rey (o una escalera que empiece con un Rey) puede ir a una columna vacía.",
		"Only empty a column when you have a King ready to move into it.": "Vacía una columna solo cuando tengas un Rey listo para ocuparla.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Resume": "Continuar",
		"Solitaire": "Solitario",
		"Tap a card to pick it up (with any cards on top of it), then tap where it should go.": "Toca una carta para tomarla (con las cartas que tenga encima) y luego toca adónde debe ir.",
		"Tap the stock to turn over a card. When it runs out, tap it again to turn the pile back over.": "Toca el mazo para dar vuelta una carta. Cuando se acabe, tócalo otra vez para volver a darlo vuelta.",
		"Time: %s   Moves: %d": "Tiempo: %s   Movimientos: %d",
		"Turning over face-down cards in the columns is usually the best move.": "Dar vuelta cartas boca abajo en las columnas suele ser la mejor jugada.",
		"Undo": "Deshacer",
		"Undo takes back a move. New Deal starts over.": "Deshacer anula un movimiento. Nueva mano empieza de nuevo.",
		"Work on the columns with the most face-down cards first.": "Trabaja primero en las columnas con más cartas boca abajo.",
		"You Win!": "¡Ganaste!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
