extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s wins!": "¡Gana %s!",
		"Always check whether your opponent can win with their next disc, and block it.": "Revisa siempre si tu rival puede ganar con su próxima ficha, y bloquéalo.",
		"Back to Hub": "Volver al inicio",
		"Build threats where your opponent must block — then the disc they drop may give you the spot above.": "Crea amenazas que tu rival deba bloquear — la ficha que ponga puede dejarte el lugar de arriba.",
		"Connect Four": "Cuatro en línea",
		"Doll": "Muñeco",
		"Don't drop a disc that lets your opponent win in the spot right above it.": "No pongas una ficha que deje ganar a tu rival en el lugar de justo arriba.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Get four of your discs in a row — across, down or diagonally.": "Pon cuatro de tus fichas en línea — horizontal, vertical o diagonal.",
		"Hard": "Difícil",
		"It's a draw!": "¡Empate!",
		"Medium": "Medio",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Red": "Rojo",
		"Red wins": "Victorias del rojo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Skull": "Calavera",
		"Tap a column to drop a disc into it. It falls to the lowest empty spot.": "Toca una columna para soltar una ficha. Cae al lugar libre más bajo.",
		"Tap 🌐 Play Online to play a friend on another phone with a room code.": "Toca 🌐 Jugar en línea para jugar con un amigo en otro teléfono usando un código de sala.",
		"The first to line up four wins. If the board fills up with no line, it's a draw.": "Gana el primero en alinear cuatro. Si el tablero se llena sin línea, es empate.",
		"The middle column is part of the most lines — play there early.": "La columna del medio forma parte de más líneas — juega ahí temprano.",
		"Turn: %s": "Turno: %s",
		"Two players share the phone. Red goes first.": "Dos jugadores comparten el teléfono. Empieza el rojo.",
		"Yellow": "Amarillo",
		"Yellow wins": "Victorias del amarillo",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
