extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"30-second round": "Ronda de 30 segundos",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't tap empty holes — watch for the mole, then strike.": "No toques hoyos vacíos — espera al topo y luego golpea.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Every hit scores a point. Moles duck back down if you're too slow.": "Cada golpe suma un punto. Los topos se esconden si eres muy lento.",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Keep your finger near the middle of the board: every hole is close by.": "Mantén el dedo cerca del centro del tablero: todos los hoyos quedan cerca.",
		"Lightning Hands": "Manos de rayo",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Mole Bopper": "Aplastatopos",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Rounds played": "Rondas jugadas",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start Round": "Empezar ronda",
		"Tap Start Round, then tap each mole as it pops up out of a hole.": "Toca Empezar ronda y luego toca cada topo que asome de un hoyo.",
		"The round ends when the timer runs out.": "La ronda termina cuando se acaba el tiempo.",
		"Time's up!\nScore: %d": "¡Se acabó el tiempo!\nPuntos: %d",
		"Time: %d": "Tiempo: %d",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Whack Pro": "Pro del martillo",
		"Whack as many moles as you can in 30 seconds!": "¡Golpea todos los topos que puedas en 30 segundos!",
		"Whack as many moles as you can in 30 seconds.": "Golpea todos los topos que puedas en 30 segundos.",
		"Whack-a-Mole": "Golpea al topo",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score in one round.": "Tu mejor puntaje en una ronda.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock. A round is only 30 seconds, so it isn't saved for later.": "⏸ pausa el reloj. Una ronda dura solo 30 segundos, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
		"🔨  Play": "🔨  Jugar",
		"🔨 Whack-a-Mole": "🔨 Golpea al topo",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
