extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s wins!": "¡Gana %s!",
		"2 Players": "2 jugadores",
		"Always block when your opponent has two in a row.": "Bloquea siempre cuando tu rival tenga dos en línea.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Bones": "Huesos",
		"Close": "Cerrar",
		"Computer is thinking...": "La computadora está pensando...",
		"Corners are the next best: each one is part of three lines.": "Las esquinas son lo siguiente mejor: cada una forma parte de tres líneas.",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Get three of your marks in a row — across, down or diagonally.": "Pon tres de tus marcas en línea — horizontal, vertical o diagonal.",
		"Hard": "Difícil",
		"It's a draw!": "¡Empate!",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"O wins": "Victorias de O",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Skull": "Calavera",
		"Tap an empty square to place your mark.": "Toca una casilla vacía para poner tu marca.",
		"The centre square is part of four lines — take it if you can.": "La casilla del centro forma parte de cuatro líneas — tómala si puedes.",
		"The computer wins!": "¡Gana la computadora!",
		"The first to line up three wins. If all nine squares fill up with no line, it's a draw.": "Gana el primero en alinear tres. Si las nueve casillas se llenan sin línea, es empate.",
		"Tic-Tac-Toe": "Tres en raya",
		"Turn: %s": "Turno: %s",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win by making two threats at once — they can only block one.": "Gana creando dos amenazas a la vez — solo pueden bloquear una.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"X wins": "Victorias de X",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"vs Computer": "vs Computadora",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
