extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s   (bet %d)": "%s   (apuesta %d)",
		"Bet: %d": "Apuesta: %d",
		"Blackjack! You win %d": "¡Blackjack! Ganas %d",
		"Bust!": "¡Te pasaste!",
		"Clear": "Borrar",
		"Deal": "Repartir",
		"Dealer": "Crupier",
		"Dealer busts — you win %d!": "El crupier se pasó — ¡ganas %d!",
		"Dealer wins": "Gana el crupier",
		"Double": "Doblar",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hit": "Pedir",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Minimum bet is %d": "La apuesta mínima es %d",
		"Next Hand": "Siguiente mano",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of chips — here's a fresh %d.": "Te quedaste sin fichas — aquí tienes %d nuevas.",
		"Place your bet": "Haz tu apuesta",
		"Push — bet returned": "Empate — se devuelve la apuesta",
		"Stand": "Plantarse",
		"You": "Tú",
		"You lose!": "¡Perdiste!",
		"You win %d!": "¡Ganas %d!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🂱 Blackjack": "🂱 Blackjack",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
