extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		" — keep capturing!": " — ¡sigue capturando!",
		"2 Players": "2 jugadores",
		"40 moves each with no captures and no ordinary piece moving is a draw.": "40 movimientos de cada uno sin capturas y sin mover fichas normales es empate.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Capture all of your opponent's pieces, or leave them with no move.": "Captura todas las fichas de tu rival o déjalo sin movimientos.",
		"Captures are compulsory: if you can jump, you must.": "Capturar es obligatorio: si puedes saltar, debes hacerlo.",
		"Checkers": "Damas",
		"Close": "Cerrar",
		"Computer is thinking...": "La computadora está pensando...",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draw — 40 moves each with no captures": "Empate — 40 jugadas cada uno sin capturas",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Jump diagonally over an enemy piece into the empty square behind it to capture it. You can keep jumping in the same turn.": "Salta en diagonal sobre una ficha rival hasta la casilla vacía de detrás para capturarla. Puedes seguir saltando en el mismo turno.",
		"Keep your back row filled for as long as you can — it stops the other side from getting kings.": "Mantén tu última fila ocupada todo lo que puedas — así el rival no consigue damas.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Pieces on the edges can't be jumped.": "Las fichas en los bordes no pueden ser saltadas.",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Player %d must continue capturing!": "¡El jugador %d debe seguir capturando!",
		"Player %d wins!": "¡Gana el jugador %d!",
		"Player %d's turn": "Turno del jugador %d",
		"Reach the far row and your piece is crowned a king, which can move and jump backwards too.": "Llega a la última fila y tu ficha se corona dama, que también puede moverse y saltar hacia atrás.",
		"Red": "Rojo",
		"Red wins": "Victorias del rojo",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Tap a piece, then the dark square to move to. Pieces move diagonally forward one square.": "Toca una ficha y luego la casilla oscura adonde moverla. Las fichas avanzan una casilla en diagonal.",
		"The computer wins!": "¡Gana la computadora!",
		"Trade pieces when you're ahead.": "Cambia fichas cuando vas ganando.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Use the compulsory-capture rule to force your opponent into a jump that sets up a double jump for you.": "Usa la captura obligatoria para forzar a tu rival a un salto que te deje un salto doble.",
		"White": "Blancas",
		"White wins": "Victorias de las blancas",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"vs Computer": "vs Computadora",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
