extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d players": "%d jugadores",
		"Agree on the rules before you start, and keep it fun for everyone.": "Pónganse de acuerdo en las reglas antes de empezar, y que sea divertido para todos.",
		"Anyone can say no to a dare — swap it for a question instead.": "Cualquiera puede rechazar un reto — cámbialo por una pregunta.",
		"Decide together what the chosen player has to do — a dare, a question, a sip, or a kiss on the cheek.": "Decidan juntos qué tiene que hacer el elegido — un reto, una pregunta, un trago o un beso en la mejilla.",
		"Drag the bottle or tap Spin!": "¡Arrastra la botella o toca Girar!",
		"Each numbered seat around the bottle is a player — go around the circle in order.": "Cada asiento numerado alrededor de la botella es un jugador — recorran el círculo en orden.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Grab the bottle with your finger and fling it round, or just tap Spin.": "Agarra la botella con el dedo y hazla girar, o simplemente toca Girar.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"It slows down and stops pointing at someone. That player is up!": "Va frenando y se detiene apuntando a alguien. ¡Le toca a esa persona!",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Player %d!": "¡Jugador %d!",
		"Point the phone's top at player 1 so the seats match where people sit.": "Apunta la parte de arriba del teléfono al jugador 1 para que los asientos coincidan con donde está cada uno.",
		"Put the phone in the middle of the circle and set how many players there are (2–12).": "Pon el teléfono en el centro del círculo e indica cuántos juegan (2–12).",
		"Spin the Bottle": "La botella",
		"Spin the bottle and see who it picks.": "Gira la botella y mira a quién elige.",
		"Spinning…": "Girando…",
		"Spins": "Giros",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🍾 Spin the Bottle": "🍾 La botella",
		"🍾 Spin!": "🍾 ¡Girar!",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
