extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Across": "Horizontal",
		"Back to Hub": "Volver al inicio",
		"Best time": "Mejor tiempo",
		"Check": "Revisar",
		"Check shows any wrong letters. Reveal letter fills in the current square if you're stuck.": "Revisar muestra las letras incorrectas. Revelar letra completa la casilla actual si te trabas.",
		"Crossword": "Crucigrama",
		"Down": "Vertical",
		"Easy": "Fácil",
		"Every puzzle is new, built fresh from a big list of clues.": "Cada puzzle es nuevo, armado a partir de una gran lista de pistas.",
		"Every word is right.": "Todas las palabras están bien.",
		"Expert": "Experto",
		"Fill in every word in the grid using the clues.": "Completa todas las palabras de la cuadrícula usando las pistas.",
		"Fill in the words you're sure of first — every letter helps the words that cross it.": "Completa primero las palabras que tengas seguras — cada letra ayuda a las palabras que se cruzan.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"Next ▶": "Siguiente ▶",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Puzzles solved": "Puzzles resueltos",
		"Reveal letter": "Revelar letra",
		"Short words are often the easiest way in.": "Las palabras cortas suelen ser la forma más fácil de empezar.",
		"Solved!": "¡Resuelto!",
		"Tap a square to choose a word. The clue for it appears above the keyboard.": "Toca una casilla para elegir una palabra. Su pista aparece sobre el teclado.",
		"Tap the same square again to switch between the Across and Down word.": "Vuelve a tocar la misma casilla para cambiar entre la palabra horizontal y la vertical.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Type letters with the keyboard — the cursor moves to the next square by itself.": "Escribe letras con el teclado — el cursor pasa solo a la casilla siguiente.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"◀ Prev": "◀ Anterior",
		"◀ Prev and Next ▶ jump between clues.": "◀ Anterior y Siguiente ▶ saltan entre pistas.",
		"📝 Crossword": "📝 Crucigrama",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
