extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d letters in": "%d letras puestas",
		"About ten words": "Unas diez palabras",
		"Across": "Horizontal",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best time": "Mejor tiempo",
		"Check": "Revisar",
		"Check shows any wrong letters. Reveal letter fills in the current square if you're stuck.": "Revisar muestra las letras incorrectas. Revelar letra completa la casilla actual si te trabas.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Crossword": "Crucigrama",
		"Crosswords solved, all time.": "Crucigramas resueltos en total.",
		"Down": "Vertical",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Every puzzle is new, built fresh from a big list of clues.": "Cada puzzle es nuevo, armado a partir de una gran lista de pistas.",
		"Every word is right.": "Todas las palabras están bien.",
		"Expert": "Experto",
		"Fill in every word in the grid using the clues.": "Completa todas las palabras de la cuadrícula usando las pistas.",
		"Fill in the words you're sure of first — every letter helps the words that cross it.": "Completa primero las palabras que tengas seguras — cada letra ayuda a las palabras que se cruzan.",
		"Fill the grid from the clues.": "Completa la cuadrícula con las pistas.",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Next Puzzle": "Siguiente puzzle",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Resume": "Continuar",
		"Reveal letter": "Revelar letra",
		"Short words are often the easiest way in.": "Las palabras cortas suelen ser la forma más fácil de empezar.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solved!": "¡Resuelto!",
		"Tap a square to choose a word. The clue for it appears above the keyboard.": "Toca una casilla para elegir una palabra. Su pista aparece sobre el teclado.",
		"Tap the same square again to switch between the Across and Down word.": "Vuelve a tocar la misma casilla para cambiar entre la palabra horizontal y la vertical.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"Type letters with the keyboard — the cursor moves to the next square by itself.": "Escribe letras con el teclado — el cursor pasa solo a la casilla siguiente.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the puzzle; Resume on the Home screen picks it up.": "⏸ pausa y guarda la partida; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"▶  New crossword": "▶  Nuevo crucigrama",
		"◀ Prev and Next ▶ jump between clues.": "◀ Anterior y Siguiente ▶ saltan entre pistas.",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📝 Crossword": "📝 Crucigrama",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
