extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Across": "Horizontal",
		"Back to Hub": "Volver al inicio",
		"Check": "Revisar",
		"Down": "Vertical",
		"Easy": "Fácil",
		"Every word is right.": "Todas las palabras están bien.",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"New": "Nuevo",
		"Next Puzzle": "Siguiente puzzle",
		"Next ▶": "Siguiente ▶",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Reveal letter": "Revelar letra",
		"Solved!": "¡Resuelto!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"◀ Prev": "◀ Anterior",
		"📝 Crossword": "📝 Crucigrama",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
