extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s gives out %d!": "¡%s reparte %d!",
		"%s got off the bus!": "¡%s se bajó del bus!",
		"%s's turn": "Turno de %s",
		"A wrong guess drinks: 1 in round one, 2 in round two, 3 in round three and 4 in round four. (Higher/lower ties count as wrong; inside/outside ties count as outside.)": "Si fallas, bebes: 1 en la primera ronda, 2 en la segunda, 3 en la tercera y 4 en la cuarta. (En mayor/menor, un empate cuenta como fallo; en adentro/afuera, cuenta como afuera.)",
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Back to Hub": "Volver al inicio",
		"Back to the start!": "¡De vuelta al principio!",
		"Black": "Negras",
		"Bus rides": "Viajes en bus",
		"Cards left": "Cartas restantes",
		"Choose how many players (2–10) and pass the phone around.": "Elige cuántos juegan (2–10) y pásense el teléfono.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Flip next card": "Dar vuelta la siguiente",
		"Flip the cards one by one. Hold the same rank? Give out drinks!": "Den vuelta las cartas una por una. ¿Tienes el mismo número? ¡Reparte tragos!",
		"Games played": "Partidas jugadas",
		"Get on the bus ➜": "Súbete al bus ➜",
		"Guess the suit!": "¡Adivina el palo!",
		"Guess well, get rid of your cards in the pyramid — and don't be the one who rides the bus!": "Adivina bien, deshazte de tus cartas en la pirámide — ¡y no seas quien se sube al bus!",
		"Hard": "Difícil",
		"Higher or lower than your first card?": "¿Mayor o menor que tu primera carta?",
		"Higher or lower: go higher when your first card is low and lower when it's high.": "Mayor o menor: di mayor cuando tu primera carta sea baja y menor cuando sea alta.",
		"Higher ⬆": "Mayor ⬆",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"Inside": "Adentro",
		"Inside or outside your first two cards?": "¿Adentro o afuera de tus dos primeras cartas?",
		"Inside or outside: the wider the gap between your first two cards, the better inside looks.": "Adentro o afuera: cuanto más separadas estén tus dos primeras cartas, mejor pinta adentro.",
		"It took %d tries.": "Le tomó %d intentos.",
		"Longest bus ride (tries)": "Viaje en bus más largo (intentos)",
		"Lower ⬇": "Menor ⬇",
		"Medium": "Medio",
		"New Game": "Nueva partida",
		"Next ➜": "Siguiente ➜",
		"Nobody has one. Phew!": "Nadie tiene una. ¡Uf!",
		"Off the bus!": "¡Fuera del bus!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Outside": "Afuera",
		"Part 1 — four rounds, each player once per round: red or black? Higher or lower than your first card? Inside or outside your first two? Then guess the suit. Every card you're dealt goes into your hand.": "Parte 1 — cuatro rondas, cada jugador una vez por ronda: ¿rojo o negro? ¿Mayor o menor que tu primera carta? ¿Adentro o afuera de las dos primeras? Luego adivina el palo. Cada carta que recibes queda en tu mano.",
		"Part 2 — the pyramid: ten cards in rows of 4, 3, 2 and 1. Flip them one at a time. Anyone holding the same rank gives out drinks — 1 for the bottom row up to 4 at the top — and lays that card down.": "Parte 2 — la pirámide: diez cartas en filas de 4, 3, 2 y 1. Se dan vuelta de a una. Quien tenga el mismo número reparte tragos — 1 en la fila de abajo hasta 4 arriba — y baja esa carta.",
		"Part 3 — whoever has the most cards left rides the bus: the four guesses again with fresh cards, in a row. Any wrong guess drinks and starts over, until all four are right.": "Parte 3 — quien tenga más cartas se sube al bus: las cuatro preguntas otra vez, seguidas, con cartas nuevas. Cada fallo bebe y empieza de nuevo, hasta acertar las cuatro.",
		"Pass the phone ➜": "Pasa el teléfono ➜",
		"Play Again": "Jugar de nuevo",
		"Player %d": "Jugador %d",
		"Red": "Rojo",
		"Red or black?": "¿Rojo o negro?",
		"Ride the Bus": "Súbete al bus",
		"Round %d of 4": "Ronda %d de 4",
		"Start Game": "Empezar partida",
		"Step %d of 4 · try %d": "Paso %d de 4 · intento %d",
		"To the pyramid ➜": "A la pirámide ➜",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"row %d: %d drinks each": "fila %d: %d tragos cada una",
		"✅ Right!": "✅ ¡Acertaste!",
		"❌ Wrong! Drink %d.": "❌ ¡Fallaste! Toma %d.",
		"🔺 The Pyramid": "🔺 La pirámide",
		"🚌 %s has the most cards and rides the bus!": "🚌 ¡%s tiene más cartas y se sube al bus!",
		"🚌 %s rides the bus!": "🚌 ¡%s se sube al bus!",
		"🚌 Ride the Bus": "🚌 Súbete al bus",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
