extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Alien Attack": "Ataque alienígena",
		"Aliens in the top rows are worth more points.": "Los alienígenas de las filas de arriba valen más puntos.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Clear out a whole column at the edge: the wave takes longer to reach the side and step down.": "Elimina una columna entera del borde: la oleada tarda más en llegar al costado y bajar.",
		"Clear the whole wave and a faster one arrives.": "Elimina toda la oleada y llega una más rápida.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Dodge their falling bombs — a hit costs one of your three lives.": "Esquiva sus bombas — cada impacto te cuesta una de tus tres vidas.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Game over when you run out of lives or the aliens reach the bottom.": "El juego termina cuando te quedas sin vidas o los alienígenas llegan abajo.",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Highest wave": "Oleada más alta",
		"Keep moving — standing still under the wave is how bombs find you.": "Sigue moviéndote — quedarte quieto bajo la oleada es la forma de que te den las bombas.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Rotate your device to landscape": "Gira tu teléfono a horizontal",
		"Score: %d": "Puntos: %d",
		"Shoot down the marching aliens before they reach the bottom.": "Derriba a los alienígenas que avanzan antes de que lleguen abajo.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Slide to move. Your cannon fires by itself — dodge the bombs!": "Desliza para moverte. Tu cañón dispara solo — ¡esquiva las bombas!",
		"Slide your finger left and right to move the cannon. It fires by itself.": "Desliza el dedo a izquierda y derecha para mover el cañón. Dispara solo.",
		"Start": "Empezar",
		"The aliens march side to side and step down each time they reach an edge.": "Los alienígenas marchan de lado a lado y bajan un paso cada vez que llegan a un borde.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Wave %d": "Oleada %d",
		"Wave %d   Score: %d   Lives: %s   Best: %d": "Oleada %d   Puntos: %d   Vidas: %s   Récord: %d",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"👾 Alien Attack": "👾 Ataque alienígena",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
