extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d colours": "%d colores",
		"%d of %d unlocked": "%d de %d desbloqueados",
		"%s   ·   The ceiling drops in %d": "%s   ·   El techo baja en %d",
		"Aim for the bubbles holding up a big cluster: dropping them is worth far more than popping.": "Apunta a las burbujas que sostienen un grupo grande: hacerlas caer vale mucho más que reventarlas.",
		"Aim, fire, pop three of a colour. Don't let them reach the line.": "Apunta, dispara, revienta tres de un color. No dejes que lleguen a la línea.",
		"Back to Hub": "Volver al inicio",
		"Bank shots off the walls to reach bubbles hidden behind others.": "Rebota en las paredes para alcanzar burbujas escondidas detrás de otras.",
		"Best score": "Mejor puntaje",
		"Bubble Pop": "Burbujas",
		"Bubbles bounce off the side walls and stick to the first bubble they touch.": "Las burbujas rebotan en las paredes y se pegan a la primera burbuja que tocan.",
		"Bubbles left hanging from nothing fall. Falling bubbles are worth much more, and more the more fall at once.": "Las burbujas que quedan colgando de nada caen. Las que caen valen mucho más, y más cuantas más caen a la vez.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Easy has 4 colours, Normal 5 and Hard 6, with the ceiling dropping sooner.": "Fácil tiene 4 colores, Normal 5 y Difícil 6, y el techo baja antes.",
		"Every few shots without a pop, the whole ceiling drops a row. Clear the board for a 500-point bonus.": "Cada pocos tiros sin reventar nada, todo el techo baja una fila. Limpia el tablero para ganar 500 puntos extra.",
		"Expert": "Experto",
		"Game over!": "¡Fin del juego!",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Join three or more of the same colour to pop them: 10 points each.": "Junta tres o más del mismo color para reventarlas: 10 puntos cada una.",
		"Keep an eye on the counter: when the ceiling is about to drop, make a pop count.": "Vigila el contador: cuando el techo esté por bajar, haz que el tiro cuente.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Most bubbles in one shot": "Más burbujas en un tiro",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"Next": "Siguiente",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Normal": "Normal",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Pop as many bubbles as you can before the pile reaches the line at the bottom.": "Revienta todas las burbujas que puedas antes de que la pila llegue a la línea de abajo.",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Tap the small bubble beside the shooter to swap it with the one you're holding.": "Toca la burbuja pequeña junto al lanzador para cambiarla por la que tienes.",
		"Touch and drag to aim — the dotted line shows the path — and let go to fire.": "Toca y arrastra para apuntar (la línea punteada muestra el camino) y suelta para disparar.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the game; Resume on the Home screen carries on.": "⏸ pausa y guarda la partida; Continuar en la pantalla de inicio la retoma.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
