extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Boards flooded, any size.": "Tableros inundados, de cualquier tamaño.",
		"Clear away a colour completely when you can — then it never needs another move.": "Cuando puedas, elimina un color por completo: así no necesita otra jugada.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Easy is 10 × 10 with 5 colours, Normal 14 × 14 with 6, Hard 18 × 18 with 7.": "Fácil es 10 × 10 con 5 colores, Normal 14 × 14 con 6, Difícil 18 × 18 con 7.",
		"Expert": "Experto",
		"Fewest moves (%s)": "Menos jugadas (%s)",
		"Fewest moves (Easy)": "Menos jugadas (Fácil)",
		"Fewest moves (Hard)": "Menos jugadas (Difícil)",
		"Fewest moves (Normal)": "Menos jugadas (Normal)",
		"Fill the board within the move limit shown at the top. The limit leaves a little room, but not much.": "Llena el tablero dentro del límite de jugadas que se ve arriba. El límite deja un poco de margen, pero no mucho.",
		"Flood It": "Inunda",
		"Flooded in %d moves!": "¡Inundado en %d jugadas!",
		"Grow towards the middle first: the flood's edge gets longer, and longer edges catch more cells.": "Crece primero hacia el centro: el borde de la inundación se alarga, y un borde largo atrapa más casillas.",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Loading...": "Cargando...",
		"Look a move ahead: a colour that swallows little now may open up a big patch next.": "Piensa una jugada adelante: un color que traga poco ahora puede abrir una zona grande después.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Moves: %d / %d": "Jugadas: %d / %d",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"Next puzzle": "Siguiente rompecabezas",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Normal": "Normal",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Out of moves!": "¡Sin jugadas!",
		"Paused": "En pausa",
		"Pick a colour, grow the flood. Fill the board before you run out of moves.": "Elige un color, haz crecer la inundación. Llena el tablero antes de quedarte sin jugadas.",
		"Play": "Jugar",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Tap a colour button (or any cell of that colour): the whole flood takes that colour and swallows the touching cells that match.": "Toca un botón de color (o cualquier casilla de ese color): toda la inundación toma ese color y traga las casillas vecinas iguales.",
		"The flood starts in the top-left corner: that cell and every cell of the same colour touching it.": "La inundación empieza en la esquina de arriba a la izquierda: esa casilla y todas las del mismo color que la tocan.",
		"Turn the whole board into one colour before you run out of moves.": "Deja todo el tablero de un solo color antes de quedarte sin jugadas.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses and keeps the board; Resume on the Home screen carries on.": "⏸ pausa y guarda el tablero; Continuar en la pantalla de inicio sigue la partida.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
