extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"\nBest: %s": "\nMejor: %s",
		"\nNew best!": "\n¡Nuevo récord!",
		"%d of %d unlocked": "%d de %d desbloqueados",
		"%s  —  %d×%d, %d mines": "%s  —  %d×%d, %d minas",
		"A 1 with only one hidden square next to it: that square is a mine.": "Un 1 con una sola casilla oculta al lado: esa casilla es una mina.",
		"A number tells you how many mines touch that square, diagonals included.": "Un número te dice cuántas minas tocan esa casilla, incluidas las diagonales.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Boards cleared, any size.": "Tableros despejados, cualquier tamaño.",
		"Boom! You hit a mine.": "¡Bum! Pisaste una mina.",
		"Change Difficulty": "Cambiar dificultad",
		"Choose a board": "Elige un tablero",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Dig every safe square. Numbers count the mines next door.": "Destapa todas las casillas seguras. Los números cuentan las minas vecinas.",
		"Dig up a mine and you lose. Pick Easy, Medium or Hard for bigger boards with more mines.": "Si destapas una mina, pierdes. Elige Fácil, Medio o Difícil para tableros más grandes con más minas.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Guess only when nothing else is left, and prefer squares far from the numbers.": "Adivina solo cuando no quede otra, y elige casillas lejos de los números.",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"If a number already has all its mines flagged, every other square around it is safe.": "Si un número ya tiene todas sus minas marcadas, las demás casillas a su alrededor son seguras.",
		"Loading...": "Cargando...",
		"Look for the 1-2-1 pattern along a wall: the mines are under the two 1s.": "Busca el patrón 1-2-1 junto a un borde: las minas están bajo los dos 1.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Minesweeper": "Buscaminas",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Switch to 🚩 mode to flag squares you think hide mines.": "Cambia al modo 🚩 para marcar las casillas donde crees que hay minas.",
		"Tap a number that already has all its flags around it to dig every other square next to it.": "Toca un número que ya tenga todas sus banderas alrededor para excavar las demás casillas vecinas.",
		"Tap a square to dig it. Your first tap is always safe and opens up an area.": "Toca una casilla para excavarla. Tu primer toque siempre es seguro y abre una zona.",
		"Tap to dig. Switch to 🚩 mode to flag mines.\nTap a number with all its flags placed to clear around it.": "Toca para excavar. Cambia al modo 🚩 para marcar minas.\nToca un número con todas sus banderas puestas para despejar alrededor.",
		"Uncover every square that doesn't hide a mine.": "Destapa todas las casillas que no esconden una mina.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You cleared the board!\nTime: %s%s": "¡Despejaste el tablero!\nTiempo: %s%s",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the clock and keeps the board; Resume on the Home screen picks it up.": "⏸ pausa el reloj y guarda el tablero; Continuar en la pantalla de inicio lo retoma.",
		"▶  Continue": "▶  Continuar",
		"⛏ Dig mode": "⛏ Modo excavar",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Tips": "💡 Consejos",
		"💣 Minesweeper": "💣 Buscaminas",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
		"😈 Hard": "😈 Difícil",
		"😐 Medium": "😐 Medio",
		"🙂 Easy": "🙂 Fácil",
		"🚩 Flag mode": "🚩 Modo bandera",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
