extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"\nBest: %s": "\nMejor: %s",
		"\nNew best!": "\n¡Nuevo récord!",
		"%s  —  %d×%d, %d mines": "%s  —  %d×%d, %d minas",
		"Back to Hub": "Volver al inicio",
		"Boom! You hit a mine.": "¡Bum! Pisaste una mina.",
		"Change Difficulty": "Cambiar dificultad",
		"Choose a board": "Elige un tablero",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"New": "Nuevo",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Tap to dig. Switch to 🚩 mode to flag mines.\nTap a number with all its flags placed to clear around it.": "Toca para excavar. Cambia al modo 🚩 para marcar minas.\nToca un número con todas sus banderas puestas para despejar alrededor.",
		"You cleared the board!\nTime: %s%s": "¡Despejaste el tablero!\nTiempo: %s%s",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"⛏ Dig mode": "⛏ Modo excavar",
		"💣 Minesweeper": "💣 Buscaminas",
		"🚩 Flag mode": "🚩 Modo bandera",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
