extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Computer — draw pile: %d": "Computadora — mazo: %d",
		"Computer: %s": "Computadora: %s",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Go!": "¡Ya!",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Lightning": "Relámpago",
		"Medium": "Medio",
		"Nobody can play — flipping new centre cards...": "Nadie puede jugar — volteando cartas nuevas al centro...",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Play cards one higher or lower than a centre pile. Empty your cards first!": "Juega cartas una más alta o más baja que una pila del centro. ¡Quédate sin cartas primero!",
		"Quick": "Rápida",
		"Relaxed": "Tranquila",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Start": "Empezar",
		"The computer was faster!": "¡La computadora fue más rápida!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %d cards left  ·  Computer: %d": "Tú: %d cartas  ·  Computadora: %d",
		"Your draw pile: %d": "Tu mazo: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"⚡ Speed": "⚡ Speed",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
