extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Choose how fast the computer plays: Relaxed, Quick or Lightning.": "Elige qué tan rápido juega la computadora: Tranquila, Rápida o Relámpago.",
		"Close": "Cerrar",
		"Computer — draw pile: %d": "Computadora — mazo: %d",
		"Computer: %s": "Computadora: %s",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Get rid of all your cards before the computer does. It's a race — no turns!": "Quédate sin cartas antes que la computadora. ¡Es una carrera, no hay turnos!",
		"Go!": "¡Ya!",
		"Hard": "Difícil",
		"Lightning": "Relámpago",
		"Loading...": "Cargando...",
		"Look at both centre piles at once — there's often a play on the other one.": "Mira las dos pilas del centro a la vez — muchas veces hay jugada en la otra.",
		"Look for runs in your hand, like 5-6-7, and play them one after another.": "Busca escaleras en tu mano, como 5-6-7, y júgalas una tras otra.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"No turns — race the computer to empty your hand.": "Sin turnos: corre contra la computadora para vaciar tu mano.",
		"Nobody can play — flipping new centre cards...": "Nadie puede jugar — volteando cartas nuevas al centro...",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Play cards one higher or lower than a centre pile. Empty your cards first!": "Juega cartas una más alta o más baja que una pila del centro. ¡Quédate sin cartas primero!",
		"Player": "Jugador",
		"Quick": "Rápida",
		"Races won against the computer.": "Carreras ganadas a la computadora.",
		"Relaxed": "Tranquila",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Speed": "Speed",
		"Speed matters more than perfection: just keep playing.": "La velocidad importa más que la perfección: sigue jugando.",
		"Start": "Empezar",
		"Tap a card in your hand to play it on a centre pile that is one higher or one lower. Ace and King connect.": "Toca una carta de tu mano para jugarla sobre una pila del centro que sea uno más o uno menos. El As y el Rey se conectan.",
		"The computer was faster!": "¡La computadora fue más rápida!",
		"The first to empty their hand and draw pile wins.": "Gana el primero en vaciar su mano y su mazo.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"When neither of you can play, a new card is flipped onto each centre pile.": "Cuando ninguno puede jugar, se da vuelta una carta nueva en cada pila del centro.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %d cards left  ·  Computer: %d": "Tú: %d cartas  ·  Computadora: %d",
		"You: %s": "Tú: %s",
		"Your draw pile: %d": "Tu mazo: %d",
		"Your hand refills up to five from your draw pile.": "Tu mano se rellena hasta cinco cartas desde tu mazo.",
		"Your turn (%s)": "Tu turno (%s)",
		"vs Computer": "vs Computadora",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the race. A race is quick, so it isn't saved for later.": "⏸ pausa la carrera. Una carrera es rápida, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"⚡ Lightning": "⚡ Relámpago",
		"⚡ Speed": "⚡ Speed",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"🐇 Quick": "🐇 Rápida",
		"🐢 Relaxed": "🐢 Tranquila",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
