extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d digits": "%d dígitos",
		"A number appears for a few seconds. Memorize it.": "Aparece un número durante unos segundos. Memorízalo.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Chunk the digits into groups of two or three, like a phone number, instead of memorizing them one by one.": "Agrupa los dígitos de dos en dos o de tres en tres, como un número de teléfono, en lugar de memorizarlos uno por uno.",
		"Close": "Cerrar",
		"Correct!": "¡Correcto!",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Digit Recall": "Recuerdo de dígitos",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Get it right and the next number is one digit longer.": "Si aciertas, el siguiente número tiene un dígito más.",
		"Get it wrong and you lose one of your 3 lives; you then try a new number of the same length. Lose all 3 and the game ends.": "Si fallas, pierdes una de tus 3 vidas y pruebas con un número nuevo de la misma longitud. Si pierdes las 3, se acaba la partida.",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Longest number: %d digits": "Número más largo: %d dígitos",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Memorize the number, then type it back. How long can you go?": "Memoriza el número y luego escríbelo. ¿Hasta dónde puedes llegar?",
		"Memorize the number…": "Memoriza el número…",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Not quite. The number was:": "No exactamente. El número era:",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Remember longer and longer numbers.": "Recuerda números cada vez más largos.",
		"Remember the number, then type it back. It grows every round.": "Recuerda el número y escríbelo. Crece en cada ronda.",
		"Resume": "Continuar",
		"Say the digits quietly to yourself in a steady rhythm while the number is on screen.": "Repite los dígitos en voz baja con un ritmo constante mientras el número está en pantalla.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start": "Empezar",
		"Type the number": "Escribe el número",
		"Until you miss": "Hasta que falles",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"When it disappears, type it back on the keypad. Use ⌫ to fix a slip before you finish.": "Cuando desaparezca, escríbelo en el teclado. Usa ⌫ para corregir un error antes de terminar.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score.": "Tu mejor puntaje.",
		"Your score is the length of the longest number you recalled.": "Tu puntaje es la longitud del número más largo que recordaste.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses. A game is quick, so it isn't saved for later.": "⏸ pausa. Una partida es rápida, así que no se guarda.",
		"▶  Continue": "▶  Continuar",
		"▶  Play": "▶  Jugar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
		"🔟 Digit Recall": "🔟 Recuerdo de dígitos",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
