extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"10 — Categories: name a category; go around until someone repeats or stalls.": "10 — Categorías: di una categoría; den la vuelta hasta que alguien repita o se trabe.",
		"2 — You: pick someone to drink.": "2 — Tú: elige a alguien para que tome.",
		"3 — Me: you drink.": "3 — Yo: tomas tú.",
		"4 — Floor: last to touch the floor drinks.": "4 — Piso: el último en tocar el piso toma.",
		"5 — Guys: all guys drink.": "5 — Chicos: toman todos los chicos.",
		"6 — Chicks: all chicks drink.": "6 — Chicas: toman todas las chicas.",
		"7 — Heaven: last hand up drinks.": "7 — Cielo: la última mano arriba toma.",
		"8 — Mate: pick a mate who drinks whenever you do.": "8 — Compañero: elige a alguien que tome cada vez que tú tomes.",
		"9 — Rhyme: say a word; go around rhyming until someone fails.": "9 — Rima: di una palabra; den la vuelta rimando hasta que alguien falle.",
		"A party card game: draw cards, follow their rules, and don't draw the fourth King!": "Un juego de cartas para fiestas: saca cartas, sigue sus reglas ¡y no saques el cuarto Rey!",
		"A — Waterfall: everyone drinks; you can't stop until the person before you does.": "A — Cascada: todos toman; no puedes parar hasta que pare la persona antes de ti.",
		"All chicks drink.": "Toman todas las chicas.",
		"All guys drink.": "Toman todos los chicos.",
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Ask a question. Whoever answers you drinks — until the next Q is drawn.": "Haz una pregunta. Quien te responda, toma — hasta que salga la próxima Q.",
		"BUST A RHYME": "RIMA",
		"Back to Hub": "Volver al inicio",
		"Cards left: %d": "Cartas restantes: %d",
		"Choose a drinking buddy — they drink whenever you do, for the rest of the game.": "Elige un compañero de tragos — toma cada vez que tú tomes, el resto del juego.",
		"Choose how many players, then pass the phone around the circle.": "Elige cuántos juegan y pásense el teléfono en ronda.",
		"Create a new rule everyone must follow for the rest of the game. Break it, drink.": "Crea una regla nueva que todos deben seguir el resto del juego. Si la rompes, tomas.",
		"DRINK THE CUP!": "¡TÓMATE LA COPA!",
		"Easy": "Fácil",
		"Everyone starts drinking at once. You can only stop when the person before you stops — you go first.": "Todos empiezan a tomar a la vez. Solo puedes parar cuando pare la persona antes de ti — tú empiezas.",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Give 1 drink to another player.": "Dale 1 trago a otro jugador.",
		"Hard": "Difícil",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"J — Make a rule: everyone follows it for the rest of the game.": "J — Crea una regla: todos la siguen el resto del juego.",
		"K — King's cup: pour some of your drink into the cup. The 4th King drinks it!": "K — Copa del rey: vierte un poco de tu bebida en la copa. ¡El 4.º Rey se la toma!",
		"KING'S CUP": "LA COPA DEL REY",
		"Kings Cup": "Kings Cup",
		"Last hand to touch the floor drinks.": "La última mano en tocar el piso, toma.",
		"Last hand up drinks.": "La última mano en levantarse, toma.",
		"MAKE A RULE": "INVENTA UNA REGLA",
		"Make the Jack rules fun, not mean — everyone has to live with them.": "Que las reglas de la J sean divertidas, no crueles — todos tienen que vivir con ellas.",
		"Medium": "Medio",
		"Most players": "Más jugadores",
		"Name a category. Go around with examples until someone repeats or hesitates — they drink.": "Di una categoría. En ronda, cada uno da un ejemplo hasta que alguien repita o dude — ese toma.",
		"New Game": "Nueva partida",
		"On your turn, tap any card from the circle, follow its rule, then tap Done.": "En tu turno, toca cualquier carta del círculo, sigue su regla y toca Listo.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"PICK A MATE": "ELIGE UN COMPAÑERO",
		"Pass the phone around. Pick a card from the circle,\nfollow the rule, tap Done. The 4th King drinks the cup!": "Pasen el teléfono. Elige una carta del círculo,\ncumple la regla y toca Listo. ¡El 4.º Rey se toma la copa!",
		"Player %d's turn": "Turno del jugador %d",
		"Pour a bit of your drink into the cup. (King %d/4)": "Echa un poco de tu trago en la copa. (Rey %d/4)",
		"Q — Question master: anyone who answers your questions drinks.": "Q — Maestro de preguntas: quien responda tus preguntas toma.",
		"QUESTION MASTER": "EL MAESTRO DE LAS PREGUNTAS",
		"Say a word. Go around rhyming until someone fails — they drink.": "Di una palabra. En ronda, cada uno dice una que rime hasta que alguien falle — ese toma.",
		"Start Game": "Empezar partida",
		"Stay sharp as Question Master: anyone who answers your question drinks.": "Mantente atento como Maestro de preguntas: quien conteste tu pregunta bebe.",
		"THREE IS ME": "TRES SOY YO",
		"TWO IS YOU": "DOS ERES TÚ",
		"Tap a card to draw it": "Toca una carta para sacarla",
		"The game ends when the last card is drawn.": "El juego termina cuando se saca la última carta.",
		"You drew the 4th king. Chug the cup!": "Sacaste el 4.º rey. ¡Tómate la copa!",
		"You drink 1.": "Tú tomas 1.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"✓ Done": "✓ Listo",
		"🍺 That's the\nwhole deck! 🍺": "🍺 ¡Se acabó\nel mazo! 🍺",
		"👑 Kings Cup": "👑 Kings Cup",
		"👑 Kings: %d/4": "👑 Reyes: %d/4",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
