extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"9: rhyme. 10: categories. J: never have I ever. Q: question master — anyone who answers your questions drinks.": "9: rimas. 10: categorías. J: yo nunca nunca. Q: maestro de preguntas — quien conteste tus preguntas bebe.",
		"A party card game: draw cards, follow their rules, and don't draw the fourth King!": "Un juego de cartas para fiestas: saca cartas, sigue sus reglas ¡y no saques el cuarto Rey!",
		"A: make a rule. 2: pick someone to drink. 3: you drink. 4: last to touch the floor drinks. 7: last hand up drinks. 8: pick a mate who drinks with you.": "A: inventa una regla. 2: elige a alguien que beba. 3: bebes tú. 4: el último en tocar el piso bebe. 7: la última mano en alzarse bebe. 8: elige un compañero que beba contigo.",
		"All chicks drink.": "Toman todas las chicas.",
		"All guys drink.": "Toman todos los chicos.",
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Ask a question. Whoever answers you drinks — until the next Q is drawn.": "Haz una pregunta. Quien te responda, toma — hasta que salga la próxima Q.",
		"BUST A RHYME": "RIMA",
		"Back to Hub": "Volver al inicio",
		"Choose a drinking buddy — they drink whenever you do, for the rest of the game.": "Elige un compañero de tragos — toma cada vez que tú tomes, el resto del juego.",
		"Choose how many players, then pass the phone around the circle.": "Elige cuántos juegan y pásense el teléfono en ronda.",
		"Create a new rule everyone must follow for the rest of the game.": "Crea una regla nueva que todos deben seguir el resto del juego.",
		"DRINK THE CUP!": "¡TÓMATE LA COPA!",
		"Each King: pour some of your drink into the cup in the middle. Whoever draws the fourth King drinks the cup!": "Cada Rey: echa un poco de tu bebida en el vaso del medio. ¡Quien saque el cuarto Rey se toma el vaso!",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Give 1 drink to another player.": "Dale 1 trago a otro jugador.",
		"Hard": "Difícil",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"KING'S CUP": "LA COPA DEL REY",
		"Kings Cup": "Kings Cup",
		"Last hand to touch the floor drinks.": "La última mano en tocar el piso, toma.",
		"Last hand up drinks.": "La última mano en levantarse, toma.",
		"MAKE A RULE": "INVENTA UNA REGLA",
		"Make the Ace rules fun, not mean — everyone has to live with them.": "Que las reglas del As sean divertidas, no crueles — todos tienen que cumplirlas.",
		"Medium": "Medio",
		"Most players": "Más jugadores",
		"NEVER HAVE I EVER": "YO NUNCA NUNCA",
		"Name a category. Go around with examples until someone repeats or hesitates — they drink.": "Di una categoría. En ronda, cada uno da un ejemplo hasta que alguien repita o dude — ese toma.",
		"New Game": "Nueva partida",
		"On your turn, tap any card from the circle. Its rule appears on screen — follow it, then tap Done.": "En tu turno, toca cualquier carta del círculo. Su regla aparece en pantalla — cúmplela y toca Listo.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"PICK A MATE": "ELIGE UN COMPAÑERO",
		"Pass the phone around. Pick a card from the circle,\nfollow the rule, tap Done. The 4th King drinks the cup!": "Pasen el teléfono. Elige una carta del círculo,\ncumple la regla y toca Listo. ¡El 4.º Rey se toma la copa!",
		"Player %d's turn": "Turno del jugador %d",
		"Pour a bit of your drink into the cup. (King %d/4)": "Echa un poco de tu trago en la copa. (Rey %d/4)",
		"QUESTION MASTER": "EL MAESTRO DE LAS PREGUNTAS",
		"Say a word. Go around rhyming until someone fails — they drink.": "Di una palabra. En ronda, cada uno dice una que rime hasta que alguien falle — ese toma.",
		"Say something you've never done. Anyone who has, drinks.": "Di algo que nunca hayas hecho. Quien sí lo haya hecho, toma.",
		"Start Game": "Empezar partida",
		"Stay sharp as Question Master: anyone who answers your question drinks.": "Mantente atento como Maestro de preguntas: quien conteste tu pregunta bebe.",
		"THREE IS ME": "TRES SOY YO",
		"TWO IS YOU": "DOS ERES TÚ",
		"Tap a card to draw it": "Toca una carta para sacarla",
		"You drew the 4th king. Chug the cup!": "Sacaste el 4.º rey. ¡Tómate la copa!",
		"You drink 1.": "Tú tomas 1.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"✓ Done": "✓ Listo",
		"🍺 DRINK\nTHE CUP! 🍺": "🍺 ¡TÓMATE\nLA COPA! 🍺",
		"👑 Kings Cup": "👑 Kings Cup",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
