extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"All chicks drink.": "Toman todas las chicas.",
		"All guys drink.": "Toman todos los chicos.",
		"Ask a question. Whoever answers you drinks — until the next Q is drawn.": "Haz una pregunta. Quien te responda, toma — hasta que salga la próxima Q.",
		"BUST A RHYME": "RIMA",
		"Back to Hub": "Volver al inicio",
		"Choose a drinking buddy — they drink whenever you do, for the rest of the game.": "Elige un compañero de tragos — toma cada vez que tú tomes, el resto del juego.",
		"Create a new rule everyone must follow for the rest of the game.": "Crea una regla nueva que todos deben seguir el resto del juego.",
		"DRINK THE CUP!": "¡TÓMATE LA COPA!",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Give 1 drink to another player.": "Dale 1 trago a otro jugador.",
		"Hard": "Difícil",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"KING'S CUP": "LA COPA DEL REY",
		"Last hand to touch the floor drinks.": "La última mano en tocar el piso, toma.",
		"Last hand up drinks.": "La última mano en levantarse, toma.",
		"MAKE A RULE": "INVENTA UNA REGLA",
		"Medium": "Medio",
		"NEVER HAVE I EVER": "YO NUNCA NUNCA",
		"Name a category. Go around with examples until someone repeats or hesitates — they drink.": "Di una categoría. En ronda, cada uno da un ejemplo hasta que alguien repita o dude — ese toma.",
		"New Game": "Nueva partida",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"PICK A MATE": "ELIGE UN COMPAÑERO",
		"Pass the phone around. Pick a card from the circle,\nfollow the rule, tap Done. The 4th King drinks the cup!": "Pasen el teléfono. Elige una carta del círculo,\ncumple la regla y toca Listo. ¡El 4.º Rey se toma la copa!",
		"Player %d's turn": "Turno del jugador %d",
		"Pour a bit of your drink into the cup. (King %d/4)": "Echa un poco de tu trago en la copa. (Rey %d/4)",
		"QUESTION MASTER": "EL MAESTRO DE LAS PREGUNTAS",
		"Say a word. Go around rhyming until someone fails — they drink.": "Di una palabra. En ronda, cada uno dice una que rime hasta que alguien falle — ese toma.",
		"Say something you've never done. Anyone who has, drinks.": "Di algo que nunca hayas hecho. Quien sí lo haya hecho, toma.",
		"Start Game": "Empezar partida",
		"THREE IS ME": "TRES SOY YO",
		"TWO IS YOU": "DOS ERES TÚ",
		"Tap a card to draw it": "Toca una carta para sacarla",
		"You drew the 4th king. Chug the cup!": "Sacaste el 4.º rey. ¡Tómate la copa!",
		"You drink 1.": "Tú tomas 1.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"✓ Done": "✓ Listo",
		"🍺 DRINK\nTHE CUP! 🍺": "🍺 ¡TÓMATE\nLA COPA! 🍺",
		"👑 Kings Cup": "👑 Kings Cup",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
