extends RefCounted

const WORDS := [
	{"word": "ELEPHANT", "category": "Animal"},
	{"word": "CHEETAH", "category": "Animal"},
	{"word": "GIRAFFE", "category": "Animal"},
	{"word": "KANGAROO", "category": "Animal"},
	{"word": "PENGUIN", "category": "Animal"},
	{"word": "GORILLA", "category": "Animal"},
	{"word": "ZEBRA", "category": "Animal"},
	{"word": "RACCOON", "category": "Animal"},
	{"word": "SQUIRREL", "category": "Animal"},
	{"word": "HEDGEHOG", "category": "Animal"},
	{"word": "BUFFALO", "category": "Animal"},
	{"word": "LEOPARD", "category": "Animal"},
	{"word": "PANTHER", "category": "Animal"},
	{"word": "MONKEY", "category": "Animal"},
	{"word": "RABBIT", "category": "Animal"},
	{"word": "HAMSTER", "category": "Animal"},
	{"word": "FERRET", "category": "Animal"},
	{"word": "MOOSE", "category": "Animal"},
	{"word": "CAMEL", "category": "Animal"},
	{"word": "OSTRICH", "category": "Animal"},
	{"word": "DOLPHIN", "category": "Sea creature"},
	{"word": "OCTOPUS", "category": "Sea creature"},
	{"word": "JELLYFISH", "category": "Sea creature"},
	{"word": "SEAHORSE", "category": "Sea creature"},
	{"word": "LOBSTER", "category": "Sea creature"},
	{"word": "STARFISH", "category": "Sea creature"},
	{"word": "WALRUS", "category": "Sea creature"},
	{"word": "STINGRAY", "category": "Sea creature"},
	{"word": "SARDINE", "category": "Sea creature"},
	{"word": "OYSTER", "category": "Sea creature"},
	{"word": "TURTLE", "category": "Reptile"},
	{"word": "LIZARD", "category": "Reptile"},
	{"word": "IGUANA", "category": "Reptile"},
	{"word": "TORTOISE", "category": "Reptile"},
	{"word": "CROCODILE", "category": "Reptile"},
	{"word": "PYTHON", "category": "Reptile"},
	{"word": "CHAMELEON", "category": "Reptile"},
	{"word": "GECKO", "category": "Reptile"},
	{"word": "ROTTWEILER", "category": "Type of dog"},
	{"word": "POODLE", "category": "Type of dog"},
	{"word": "BEAGLE", "category": "Type of dog"},
	{"word": "DALMATIAN", "category": "Type of dog"},
	{"word": "CHIHUAHUA", "category": "Type of dog"},
	{"word": "BULLDOG", "category": "Type of dog"},
	{"word": "LABRADOR", "category": "Type of dog"},
	{"word": "TERRIER", "category": "Type of dog"},
	{"word": "GREYHOUND", "category": "Type of dog"},
	{"word": "HUSKY", "category": "Type of dog"},
	{"word": "PARROT", "category": "Bird"},
	{"word": "FLAMINGO", "category": "Bird"},
	{"word": "PELICAN", "category": "Bird"},
	{"word": "SPARROW", "category": "Bird"},
	{"word": "PEACOCK", "category": "Bird"},
	{"word": "TOUCAN", "category": "Bird"},
	{"word": "VULTURE", "category": "Bird"},
	{"word": "FALCON", "category": "Bird"},
	{"word": "PIGEON", "category": "Bird"},
	{"word": "HUMMINGBIRD", "category": "Bird"},
	{"word": "ORANGE", "category": "Fruit"},
	{"word": "STRAWBERRY", "category": "Fruit"},
	{"word": "PINEAPPLE", "category": "Fruit"},
	{"word": "MANGO", "category": "Fruit"},
	{"word": "BANANA", "category": "Fruit"},
	{"word": "CHERRY", "category": "Fruit"},
	{"word": "APRICOT", "category": "Fruit"},
	{"word": "BLUEBERRY", "category": "Fruit"},
	{"word": "COCONUT", "category": "Fruit"},
	{"word": "WATERMELON", "category": "Fruit"},
	{"word": "PAPAYA", "category": "Fruit"},
	{"word": "KIWI", "category": "Fruit"},
	{"word": "BROCCOLI", "category": "Vegetable"},
	{"word": "CARROT", "category": "Vegetable"},
	{"word": "SPINACH", "category": "Vegetable"},
	{"word": "CUCUMBER", "category": "Vegetable"},
	{"word": "PUMPKIN", "category": "Vegetable"},
	{"word": "CELERY", "category": "Vegetable"},
	{"word": "CABBAGE", "category": "Vegetable"},
	{"word": "ZUCCHINI", "category": "Vegetable"},
	{"word": "POTATO", "category": "Vegetable"},
	{"word": "ONION", "category": "Vegetable"},
	{"word": "SPAGHETTI", "category": "Food"},
	{"word": "BURRITO", "category": "Food"},
	{"word": "PANCAKE", "category": "Food"},
	{"word": "SANDWICH", "category": "Food"},
	{"word": "LASAGNA", "category": "Food"},
	{"word": "PRETZEL", "category": "Food"},
	{"word": "WAFFLE", "category": "Food"},
	{"word": "OMELETTE", "category": "Food"},
	{"word": "DUMPLING", "category": "Food"},
	{"word": "POPCORN", "category": "Food"},
	{"word": "CHEESECAKE", "category": "Food"},
	{"word": "TACO", "category": "Food"},
	{"word": "LEMONADE", "category": "Drink"},
	{"word": "SMOOTHIE", "category": "Drink"},
	{"word": "ESPRESSO", "category": "Drink"},
	{"word": "MILKSHAKE", "category": "Drink"},
	{"word": "COCOA", "category": "Drink"},
	{"word": "JUICE", "category": "Drink"},
	{"word": "GUITAR", "category": "Musical instrument"},
	{"word": "TRUMPET", "category": "Musical instrument"},
	{"word": "VIOLIN", "category": "Musical instrument"},
	{"word": "PIANO", "category": "Musical instrument"},
	{"word": "SAXOPHONE", "category": "Musical instrument"},
	{"word": "CLARINET", "category": "Musical instrument"},
	{"word": "TROMBONE", "category": "Musical instrument"},
	{"word": "HARMONICA", "category": "Musical instrument"},
	{"word": "UKULELE", "category": "Musical instrument"},
	{"word": "ACCORDION", "category": "Musical instrument"},
	{"word": "CELLO", "category": "Musical instrument"},
	{"word": "DRUMS", "category": "Musical instrument"},
	{"word": "BASKETBALL", "category": "Sport"},
	{"word": "SOCCER", "category": "Sport"},
	{"word": "TENNIS", "category": "Sport"},
	{"word": "VOLLEYBALL", "category": "Sport"},
	{"word": "BASEBALL", "category": "Sport"},
	{"word": "HOCKEY", "category": "Sport"},
	{"word": "SWIMMING", "category": "Sport"},
	{"word": "BOXING", "category": "Sport"},
	{"word": "CYCLING", "category": "Sport"},
	{"word": "SURFING", "category": "Sport"},
	{"word": "BOWLING", "category": "Sport"},
	{"word": "ARCHERY", "category": "Sport"},
	{"word": "WHISTLE", "category": "Sports equipment"},
	{"word": "RACKET", "category": "Sports equipment"},
	{"word": "HELMET", "category": "Sports equipment"},
	{"word": "SKATEBOARD", "category": "Sports equipment"},
	{"word": "DUMBBELL", "category": "Sports equipment"},
	{"word": "SNOWBOARD", "category": "Sports equipment"},
	{"word": "ROCKET", "category": "Mode of transport"},
	{"word": "BICYCLE", "category": "Mode of transport"},
	{"word": "SUBMARINE", "category": "Mode of transport"},
	{"word": "HELICOPTER", "category": "Mode of transport"},
	{"word": "MOTORCYCLE", "category": "Mode of transport"},
	{"word": "TRACTOR", "category": "Mode of transport"},
	{"word": "SAILBOAT", "category": "Mode of transport"},
	{"word": "AIRPLANE", "category": "Mode of transport"},
	{"word": "SCOOTER", "category": "Mode of transport"},
	{"word": "TRAIN", "category": "Mode of transport"},
	{"word": "MOUNTAIN", "category": "Geographic feature"},
	{"word": "VOLCANO", "category": "Geographic feature"},
	{"word": "CANYON", "category": "Geographic feature"},
	{"word": "GLACIER", "category": "Geographic feature"},
	{"word": "ISLAND", "category": "Geographic feature"},
	{"word": "DESERT", "category": "Geographic feature"},
	{"word": "WATERFALL", "category": "Geographic feature"},
	{"word": "VALLEY", "category": "Geographic feature"},
	{"word": "LAGOON", "category": "Geographic feature"},
	{"word": "PENINSULA", "category": "Geographic feature"},
	{"word": "GALAXY", "category": "Space object"},
	{"word": "PLANET", "category": "Space object"},
	{"word": "COMET", "category": "Space object"},
	{"word": "ASTEROID", "category": "Space object"},
	{"word": "NEBULA", "category": "Space object"},
	{"word": "METEOR", "category": "Space object"},
	{"word": "SATELLITE", "category": "Space object"},
	{"word": "JACKET", "category": "Clothing item"},
	{"word": "SWEATER", "category": "Clothing item"},
	{"word": "SCARF", "category": "Clothing item"},
	{"word": "SANDALS", "category": "Clothing item"},
	{"word": "PAJAMAS", "category": "Clothing item"},
	{"word": "HOODIE", "category": "Clothing item"},
	{"word": "NECKTIE", "category": "Clothing item"},
	{"word": "OVERALLS", "category": "Clothing item"},
	{"word": "SNEAKERS", "category": "Clothing item"},
	{"word": "PENCIL", "category": "School supply"},
	{"word": "NOTEBOOK", "category": "School supply"},
	{"word": "ERASER", "category": "School supply"},
	{"word": "BACKPACK", "category": "School supply"},
	{"word": "SCISSORS", "category": "School supply"},
	{"word": "CRAYON", "category": "School supply"},
	{"word": "CALCULATOR", "category": "School supply"},
	{"word": "CANDLE", "category": "Household item"},
	{"word": "BLANKET", "category": "Household item"},
	{"word": "PILLOW", "category": "Household item"},
	{"word": "TOASTER", "category": "Household item"},
	{"word": "VACUUM", "category": "Household item"},
	{"word": "MICROWAVE", "category": "Household item"},
	{"word": "LADDER", "category": "Household item"},
	{"word": "BUCKET", "category": "Household item"},
	{"word": "MIRROR", "category": "Household item"},
	{"word": "WINDOW", "category": "Part of a house"},
	{"word": "CHIMNEY", "category": "Part of a house"},
	{"word": "BALCONY", "category": "Part of a house"},
	{"word": "BASEMENT", "category": "Part of a house"},
	{"word": "STAIRCASE", "category": "Part of a house"},
	{"word": "HALLWAY", "category": "Part of a house"},
	{"word": "GARAGE", "category": "Part of a house"},
	{"word": "KITCHEN", "category": "Part of a house"},
	{"word": "COMPUTER", "category": "Electronic device"},
	{"word": "TELEVISION", "category": "Electronic device"},
	{"word": "CAMERA", "category": "Electronic device"},
	{"word": "HEADPHONES", "category": "Electronic device"},
	{"word": "KEYBOARD", "category": "Electronic device"},
	{"word": "PRINTER", "category": "Electronic device"},
	{"word": "TABLET", "category": "Electronic device"},
	{"word": "SPEAKER", "category": "Electronic device"},
	{"word": "FIREFIGHTER", "category": "Job"},
	{"word": "TEACHER", "category": "Job"},
	{"word": "DENTIST", "category": "Job"},
	{"word": "PLUMBER", "category": "Job"},
	{"word": "ASTRONAUT", "category": "Job"},
	{"word": "CARPENTER", "category": "Job"},
	{"word": "MECHANIC", "category": "Job"},
	{"word": "PILOT", "category": "Job"},
	{"word": "FARMER", "category": "Job"},
	{"word": "CHEF", "category": "Job"},
	{"word": "PUZZLE", "category": "Type of game"},
	{"word": "CHESS", "category": "Type of game"},
	{"word": "CHECKERS", "category": "Type of game"},
	{"word": "DOMINOES", "category": "Type of game"},
	{"word": "BINGO", "category": "Type of game"},
	{"word": "BRAZIL", "category": "Country"},
	{"word": "CANADA", "category": "Country"},
	{"word": "MEXICO", "category": "Country"},
	{"word": "JAPAN", "category": "Country"},
	{"word": "ARGENTINA", "category": "Country"},
	{"word": "ITALY", "category": "Country"},
	{"word": "EGYPT", "category": "Country"},
	{"word": "AUSTRALIA", "category": "Country"},
	{"word": "NORWAY", "category": "Country"},
	{"word": "PORTUGAL", "category": "Country"},
	{"word": "THUNDER", "category": "Weather"},
	{"word": "RAINBOW", "category": "Weather"},
	{"word": "HURRICANE", "category": "Weather"},
	{"word": "TORNADO", "category": "Weather"},
	{"word": "BLIZZARD", "category": "Weather"},
	{"word": "DRIZZLE", "category": "Weather"},
	{"word": "SHOULDER", "category": "Body part"},
	{"word": "ELBOW", "category": "Body part"},
	{"word": "ANKLE", "category": "Body part"},
	{"word": "STOMACH", "category": "Body part"},
	{"word": "EYEBROW", "category": "Body part"},
	{"word": "KNUCKLE", "category": "Body part"},
	{"word": "JAVASCRIPT", "category": "Programming language"},
	{"word": "RUBY", "category": "Programming language"},
]
## Spanish words: accents dropped (no á/é/í/ó/ú keys), Ñ kept.
const WORDS_ES := [
	{"word": "ELEFANTE", "category": "Animal"},
	{"word": "GUEPARDO", "category": "Animal"},
	{"word": "JIRAFA", "category": "Animal"},
	{"word": "CANGURO", "category": "Animal"},
	{"word": "PINGUINO", "category": "Animal"},
	{"word": "GORILA", "category": "Animal"},
	{"word": "CEBRA", "category": "Animal"},
	{"word": "ARDILLA", "category": "Animal"},
	{"word": "MAPACHE", "category": "Animal"},
	{"word": "ERIZO", "category": "Animal"},
	{"word": "BUFALO", "category": "Animal"},
	{"word": "LEOPARDO", "category": "Animal"},
	{"word": "PANTERA", "category": "Animal"},
	{"word": "MONO", "category": "Animal"},
	{"word": "CONEJO", "category": "Animal"},
	{"word": "HAMSTER", "category": "Animal"},
	{"word": "HURON", "category": "Animal"},
	{"word": "ALCE", "category": "Animal"},
	{"word": "CAMELLO", "category": "Animal"},
	{"word": "AVESTRUZ", "category": "Animal"},
	{"word": "CARPINCHO", "category": "Animal"},
	{"word": "VICUÑA", "category": "Animal"},
	{"word": "DELFIN", "category": "Animal marino"},
	{"word": "PULPO", "category": "Animal marino"},
	{"word": "MEDUSA", "category": "Animal marino"},
	{"word": "CABALLITO", "category": "Animal marino"},
	{"word": "LANGOSTA", "category": "Animal marino"},
	{"word": "ESTRELLA", "category": "Animal marino"},
	{"word": "MORSA", "category": "Animal marino"},
	{"word": "BALLENA", "category": "Animal marino"},
	{"word": "SARDINA", "category": "Animal marino"},
	{"word": "OSTRA", "category": "Animal marino"},
	{"word": "TIBURON", "category": "Animal marino"},
	{"word": "TORTUGA", "category": "Reptil"},
	{"word": "LAGARTO", "category": "Reptil"},
	{"word": "IGUANA", "category": "Reptil"},
	{"word": "COCODRILO", "category": "Reptil"},
	{"word": "SERPIENTE", "category": "Reptil"},
	{"word": "CAMALEON", "category": "Reptil"},
	{"word": "GECKO", "category": "Reptil"},
	{"word": "YACARE", "category": "Reptil"},
	{"word": "LORO", "category": "Ave"},
	{"word": "FLAMENCO", "category": "Ave"},
	{"word": "PELICANO", "category": "Ave"},
	{"word": "GORRION", "category": "Ave"},
	{"word": "PAVO", "category": "Ave"},
	{"word": "TUCAN", "category": "Ave"},
	{"word": "BUITRE", "category": "Ave"},
	{"word": "HALCON", "category": "Ave"},
	{"word": "PALOMA", "category": "Ave"},
	{"word": "COLIBRI", "category": "Ave"},
	{"word": "CONDOR", "category": "Ave"},
	{"word": "HORNERO", "category": "Ave"},
	{"word": "NARANJA", "category": "Fruta"},
	{"word": "FRUTILLA", "category": "Fruta"},
	{"word": "PIÑA", "category": "Fruta"},
	{"word": "MANGO", "category": "Fruta"},
	{"word": "BANANA", "category": "Fruta"},
	{"word": "CEREZA", "category": "Fruta"},
	{"word": "DURAZNO", "category": "Fruta"},
	{"word": "ARANDANO", "category": "Fruta"},
	{"word": "COCO", "category": "Fruta"},
	{"word": "SANDIA", "category": "Fruta"},
	{"word": "PAPAYA", "category": "Fruta"},
	{"word": "KIWI", "category": "Fruta"},
	{"word": "MANZANA", "category": "Fruta"},
	{"word": "BROCOLI", "category": "Verdura"},
	{"word": "ZANAHORIA", "category": "Verdura"},
	{"word": "ESPINACA", "category": "Verdura"},
	{"word": "PEPINO", "category": "Verdura"},
	{"word": "CALABAZA", "category": "Verdura"},
	{"word": "APIO", "category": "Verdura"},
	{"word": "REPOLLO", "category": "Verdura"},
	{"word": "ZAPALLITO", "category": "Verdura"},
	{"word": "PAPA", "category": "Verdura"},
	{"word": "CEBOLLA", "category": "Verdura"},
	{"word": "ESPAGUETI", "category": "Comida"},
	{"word": "EMPANADA", "category": "Comida"},
	{"word": "PANQUEQUE", "category": "Comida"},
	{"word": "SANGUCHE", "category": "Comida"},
	{"word": "LASAÑA", "category": "Comida"},
	{"word": "MILANESA", "category": "Comida"},
	{"word": "ASADO", "category": "Comida"},
	{"word": "TORTILLA", "category": "Comida"},
	{"word": "ALFAJOR", "category": "Comida"},
	{"word": "PALOMITAS", "category": "Comida"},
	{"word": "LOCRO", "category": "Comida"},
	{"word": "LIMONADA", "category": "Bebida"},
	{"word": "LICUADO", "category": "Bebida"},
	{"word": "CAFE", "category": "Bebida"},
	{"word": "MATE", "category": "Bebida"},
	{"word": "CHOCOLATADA", "category": "Bebida"},
	{"word": "HORCHATA", "category": "Bebida"},
	{"word": "GUITARRA", "category": "Instrumento musical"},
	{"word": "TROMPETA", "category": "Instrumento musical"},
	{"word": "VIOLIN", "category": "Instrumento musical"},
	{"word": "PIANO", "category": "Instrumento musical"},
	{"word": "SAXOFON", "category": "Instrumento musical"},
	{"word": "CLARINETE", "category": "Instrumento musical"},
	{"word": "TROMBON", "category": "Instrumento musical"},
	{"word": "ARMONICA", "category": "Instrumento musical"},
	{"word": "CHARANGO", "category": "Instrumento musical"},
	{"word": "ACORDEON", "category": "Instrumento musical"},
	{"word": "BOMBO", "category": "Instrumento musical"},
	{"word": "BANDONEON", "category": "Instrumento musical"},
	{"word": "BALONCESTO", "category": "Deporte"},
	{"word": "FUTBOL", "category": "Deporte"},
	{"word": "TENIS", "category": "Deporte"},
	{"word": "VOLEIBOL", "category": "Deporte"},
	{"word": "BEISBOL", "category": "Deporte"},
	{"word": "HOCKEY", "category": "Deporte"},
	{"word": "NATACION", "category": "Deporte"},
	{"word": "BOXEO", "category": "Deporte"},
	{"word": "CICLISMO", "category": "Deporte"},
	{"word": "SURF", "category": "Deporte"},
	{"word": "RUGBY", "category": "Deporte"},
	{"word": "ESGRIMA", "category": "Deporte"},
	{"word": "COHETE", "category": "Medio de transporte"},
	{"word": "BICICLETA", "category": "Medio de transporte"},
	{"word": "SUBMARINO", "category": "Medio de transporte"},
	{"word": "HELICOPTERO", "category": "Medio de transporte"},
	{"word": "MOTO", "category": "Medio de transporte"},
	{"word": "TRACTOR", "category": "Medio de transporte"},
	{"word": "VELERO", "category": "Medio de transporte"},
	{"word": "AVION", "category": "Medio de transporte"},
	{"word": "MONOPATIN", "category": "Medio de transporte"},
	{"word": "TREN", "category": "Medio de transporte"},
	{"word": "COLECTIVO", "category": "Medio de transporte"},
	{"word": "MONTAÑA", "category": "Accidente geográfico"},
	{"word": "VOLCAN", "category": "Accidente geográfico"},
	{"word": "CAÑON", "category": "Accidente geográfico"},
	{"word": "GLACIAR", "category": "Accidente geográfico"},
	{"word": "ISLA", "category": "Accidente geográfico"},
	{"word": "DESIERTO", "category": "Accidente geográfico"},
	{"word": "CASCADA", "category": "Accidente geográfico"},
	{"word": "VALLE", "category": "Accidente geográfico"},
	{"word": "LAGUNA", "category": "Accidente geográfico"},
	{"word": "PENINSULA", "category": "Accidente geográfico"},
	{"word": "GALAXIA", "category": "Espacio"},
	{"word": "PLANETA", "category": "Espacio"},
	{"word": "COMETA", "category": "Espacio"},
	{"word": "ASTEROIDE", "category": "Espacio"},
	{"word": "NEBULOSA", "category": "Espacio"},
	{"word": "METEORO", "category": "Espacio"},
	{"word": "SATELITE", "category": "Espacio"},
	{"word": "CAMPERA", "category": "Ropa"},
	{"word": "SUETER", "category": "Ropa"},
	{"word": "BUFANDA", "category": "Ropa"},
	{"word": "SANDALIAS", "category": "Ropa"},
	{"word": "PIJAMA", "category": "Ropa"},
	{"word": "CORBATA", "category": "Ropa"},
	{"word": "ZAPATILLAS", "category": "Ropa"},
	{"word": "GORRA", "category": "Ropa"},
	{"word": "LAPIZ", "category": "Útiles escolares"},
	{"word": "CUADERNO", "category": "Útiles escolares"},
	{"word": "GOMA", "category": "Útiles escolares"},
	{"word": "MOCHILA", "category": "Útiles escolares"},
	{"word": "TIJERA", "category": "Útiles escolares"},
	{"word": "CRAYON", "category": "Útiles escolares"},
	{"word": "CALCULADORA", "category": "Útiles escolares"},
	{"word": "REGLA", "category": "Útiles escolares"},
	{"word": "VELA", "category": "Objeto de la casa"},
	{"word": "MANTA", "category": "Objeto de la casa"},
	{"word": "ALMOHADA", "category": "Objeto de la casa"},
	{"word": "TOSTADORA", "category": "Objeto de la casa"},
	{"word": "ASPIRADORA", "category": "Objeto de la casa"},
	{"word": "MICROONDAS", "category": "Objeto de la casa"},
	{"word": "ESCALERA", "category": "Objeto de la casa"},
	{"word": "BALDE", "category": "Objeto de la casa"},
	{"word": "ESPEJO", "category": "Objeto de la casa"},
	{"word": "VENTANA", "category": "Parte de una casa"},
	{"word": "CHIMENEA", "category": "Parte de una casa"},
	{"word": "BALCON", "category": "Parte de una casa"},
	{"word": "SOTANO", "category": "Parte de una casa"},
	{"word": "PASILLO", "category": "Parte de una casa"},
	{"word": "GARAJE", "category": "Parte de una casa"},
	{"word": "COCINA", "category": "Parte de una casa"},
	{"word": "TERRAZA", "category": "Parte de una casa"},
	{"word": "COMPUTADORA", "category": "Aparato electrónico"},
	{"word": "TELEVISOR", "category": "Aparato electrónico"},
	{"word": "CAMARA", "category": "Aparato electrónico"},
	{"word": "AURICULARES", "category": "Aparato electrónico"},
	{"word": "TECLADO", "category": "Aparato electrónico"},
	{"word": "IMPRESORA", "category": "Aparato electrónico"},
	{"word": "TABLETA", "category": "Aparato electrónico"},
	{"word": "PARLANTE", "category": "Aparato electrónico"},
	{"word": "BOMBERO", "category": "Profesión"},
	{"word": "MAESTRO", "category": "Profesión"},
	{"word": "DENTISTA", "category": "Profesión"},
	{"word": "PLOMERO", "category": "Profesión"},
	{"word": "ASTRONAUTA", "category": "Profesión"},
	{"word": "CARPINTERO", "category": "Profesión"},
	{"word": "MECANICO", "category": "Profesión"},
	{"word": "PILOTO", "category": "Profesión"},
	{"word": "GRANJERO", "category": "Profesión"},
	{"word": "COCINERO", "category": "Profesión"},
	{"word": "BRASIL", "category": "País"},
	{"word": "CANADA", "category": "País"},
	{"word": "MEXICO", "category": "País"},
	{"word": "JAPON", "category": "País"},
	{"word": "ARGENTINA", "category": "País"},
	{"word": "ITALIA", "category": "País"},
	{"word": "EGIPTO", "category": "País"},
	{"word": "AUSTRALIA", "category": "País"},
	{"word": "NORUEGA", "category": "País"},
	{"word": "PORTUGAL", "category": "País"},
	{"word": "URUGUAY", "category": "País"},
	{"word": "ESPAÑA", "category": "País"},
	{"word": "TRUENO", "category": "Clima"},
	{"word": "ARCOIRIS", "category": "Clima"},
	{"word": "HURACAN", "category": "Clima"},
	{"word": "TORNADO", "category": "Clima"},
	{"word": "NEVADA", "category": "Clima"},
	{"word": "LLOVIZNA", "category": "Clima"},
	{"word": "GRANIZO", "category": "Clima"},
	{"word": "HOMBRO", "category": "Parte del cuerpo"},
	{"word": "CODO", "category": "Parte del cuerpo"},
	{"word": "TOBILLO", "category": "Parte del cuerpo"},
	{"word": "ESTOMAGO", "category": "Parte del cuerpo"},
	{"word": "CEJA", "category": "Parte del cuerpo"},
	{"word": "RODILLA", "category": "Parte del cuerpo"},
	{"word": "MUÑECA", "category": "Parte del cuerpo"},
]
const MAX_WRONG := 6

var word: String = ""
var category: String = ""
var guessed: Dictionary = {}  # letter (String) -> true
var wrong_count: int = 0

## Spanish words and topics instead of English ones.
var spanish: bool = false

## Shuffled word indices still to be dealt, per language. Drawing from a bag
## instead of picking at random means no word repeats until every word has
## come up.
var _bags: Dictionary = {}

func reset() -> void:
	var words: Array = WORDS_ES if spanish else WORDS
	var bag: Array = _bags.get(spanish, [])
	if bag.is_empty():
		bag = range(words.size())
		bag.shuffle()
		_bags[spanish] = bag
	var entry: Dictionary = words[bag.pop_back()]
	word = entry.word
	category = entry.category
	guessed = {}
	wrong_count = 0

## Returns "correct", "wrong", or "ignored" (already guessed, or game already over).
func guess(letter: String) -> String:
	letter = letter.to_upper()
	if guessed.has(letter) or is_won() or is_lost():
		return "ignored"
	guessed[letter] = true
	if word.contains(letter):
		return "correct"
	wrong_count += 1
	return "wrong"

func is_won() -> bool:
	for c in word:
		if not guessed.has(c):
			return false
	return true

func is_lost() -> bool:
	return wrong_count >= MAX_WRONG

func display_word() -> String:
	var s := ""
	for c in word:
		s += (c + " ") if guessed.has(c) else "_ "
	return s.strip_edges()
