extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Animal": "Animal",
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"Bird": "Ave",
		"Body part": "Parte del cuerpo",
		"Clothing item": "Prenda de ropa",
		"Country": "País",
		"Drink": "Tomas",
		"Each wrong letter adds to the drawing. Six wrong guesses and the game is over.": "Cada letra equivocada suma al dibujo. Con seis errores se termina el juego.",
		"Easy": "Fácil",
		"Electronic device": "Aparato electrónico",
		"Expert": "Experto",
		"Food": "Comida",
		"Fruit": "Fruta",
		"Game over — the word was %s": "Perdiste — la palabra era %s",
		"Geographic feature": "Accidente geográfico",
		"Guess the hidden word one letter at a time before you run out of guesses.": "Adivina la palabra oculta letra por letra antes de quedarte sin intentos.",
		"Hangman": "Ahorcado",
		"Hard": "Difícil",
		"Household item": "Objeto de la casa",
		"Hub": "Inicio",
		"Job": "Profesión",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Mode of transport": "Medio de transporte",
		"Musical instrument": "Instrumento musical",
		"New Word": "Nueva palabra",
		"Once a few letters are in, look at the pattern and think of whole words.": "Cuando tengas algunas letras, mira el patrón y piensa en palabras completas.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Part of a house": "Parte de una casa",
		"Play Again": "Jugar de nuevo",
		"Programming language": "Lenguaje de programación",
		"Reptile": "Reptil",
		"School supply": "Útil escolar",
		"Sea creature": "Animal marino",
		"Space object": "Objeto del espacio",
		"Sport": "Deporte",
		"Sports equipment": "Equipamiento deportivo",
		"Start with common vowels like E, A and O, then common consonants like R, S, T and N.": "Empieza con vocales comunes como E, A y O, y luego consonantes comunes como S, R, N y L.",
		"Tap a letter to guess it. Right letters fill in every place they appear.": "Toca una letra para probarla. Las letras correctas aparecen en todos sus lugares.",
		"The topic is shown above the word, and each blank is one letter.": "El tema aparece sobre la palabra, y cada espacio es una letra.",
		"Topic": "Tema",
		"Type of dog": "Raza de perro",
		"Type of game": "Tipo de juego",
		"Use the topic to think of words that fit the length.": "Usa el tema para pensar palabras que tengan ese largo.",
		"Vegetable": "Verdura",
		"Weather": "Clima",
		"Wins": "Victorias",
		"Wrong guesses: %d/%d": "Errores: %d/%d",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You win! The word was %s": "¡Ganaste! La palabra era %s",
		"Your turn (%s)": "Tu turno (%s)",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
