extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d letters": "%d letras",
		"%d+ letters": "%d+ letras",
		"%s — already found": "%s — ya la encontraste",
		"%s — not a word": "%s — no es una palabra",
		"3–4 letters score 1 point, 5 letters 2, 6 letters 3, 7 letters 5, and 8 or more 11.": "3–4 letras valen 1 punto, 5 letras 2, 6 letras 3, 7 letras 5, y 8 o más 11.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Drag across touching letters to make a word. Diagonals count.": "Arrastra sobre letras vecinas para formar una palabra. Las diagonales cuentan.",
		"Drag across touching letters to make words of 3+ letters. You have 3 minutes.": "Arrastra por letras vecinas para formar palabras de 3 o más letras. Tienes 3 minutos.",
		"Each letter can be used only once in a word.": "Cada letra se puede usar una sola vez por palabra.",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Find as many words as you can in the letter grid before the 3 minutes run out.": "Encuentra todas las palabras que puedas en la cuadrícula antes de que pasen los 3 minutos.",
		"Found:": "Encontradas:",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Hunt around the vowels — most words go through them.": "Busca alrededor de las vocales — la mayoría de las palabras pasan por ellas.",
		"Long words are worth far more than short ones.": "Las palabras largas valen mucho más que las cortas.",
		"Longest you missed:": "Las más largas que te faltaron:",
		"Medium": "Medio",
		"Most words found": "Más palabras encontradas",
		"Once you find a word, try adding S, ED or ER to the end.": "Cuando encuentres una palabra, prueba agregarle S, ED o ER al final (las palabras son en inglés).",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Rounds played": "Rondas jugadas",
		"Score: %d — %d of %d words found.": "Puntos: %d — encontraste %d de %d palabras.",
		"Show missed words": "Ver palabras que faltaron",
		"Start": "Empezar",
		"Time's up!": "¡Se acabó el tiempo!",
		"When time's up you'll see how many words were hiding in the grid. Tap Show missed words, then any word, to see its path on the board.": "Cuando se acabe el tiempo verás cuántas palabras había escondidas en la cuadrícula. Toca Ver palabras que faltaron y luego cualquier palabra para ver su camino en el tablero.",
		"Word Hunt": "Cazapalabras",
		"Words are in English.": "Las palabras son en inglés.",
		"Words need at least 3 letters. They're checked against an English dictionary.": "Las palabras deben tener al menos 3 letras. Se revisan con un diccionario en inglés.",
		"Words you missed (tap one to see it):": "Palabras que te faltaron (toca una para verla):",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"⏱ %d:%02d   Score: %d   Best: %d": "⏱ %d:%02d   Puntos: %d   Récord: %d",
		"🎲 Word Hunt": "🎲 Cazapalabras",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
