extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%s — already found": "%s — ya la encontraste",
		"%s — not a word": "%s — no es una palabra",
		"Back to Hub": "Volver al inicio",
		"Drag across touching letters to make words of 3+ letters. You have 3 minutes.": "Arrastra por letras vecinas para formar palabras de 3 o más letras. Tienes 3 minutos.",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Found:": "Encontradas:",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Longest you missed:": "Las más largas que te faltaron:",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Score: %d — %d of %d words found.": "Puntos: %d — encontraste %d de %d palabras.",
		"Start": "Empezar",
		"Time's up!": "¡Se acabó el tiempo!",
		"Words are in English.": "Las palabras son en inglés.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"⏱ %d:%02d   Score: %d   Best: %d": "⏱ %d:%02d   Puntos: %d   Récord: %d",
		"🎲 Word Hunt": "🎲 Cazapalabras",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
