extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Aim for the middle of each gap, and get lined up early for the next one.": "Apunta al centro de cada hueco y alinéate temprano para el siguiente.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Bird Hop": "Pájaro saltarín",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Every pillar you pass is one point.": "Cada pilar que pasas es un punto.",
		"Expert": "Experto",
		"Fly through as many gaps between the pillars as you can.": "Vuela a través de todos los huecos entre pilares que puedas.",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Look at the next gap, not at the bird.": "Mira el próximo hueco, no al pájaro.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Short, gentle taps work better than frantic ones.": "Los toques cortos y suaves funcionan mejor que los desesperados.",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Tap anywhere (or press Space) to flap. Gravity pulls you down between taps.": "Toca en cualquier lugar (o presiona Espacio) para aletear. La gravedad te baja entre toques.",
		"Tap anywhere to fly": "Toca en cualquier parte para volar",
		"Tap to flap!": "¡Toca para aletear!",
		"Tap to flap. Slip through the gaps.": "Toca para aletear. Pasa por los huecos.",
		"Touching a pillar or the ground ends the run.": "Tocar un pilar o el suelo termina la partida.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score: pillars passed in one flight.": "Tu mejor puntaje: columnas pasadas en un vuelo.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the game. A round can't be saved for later: leaving it ends it.": "⏸ pausa el juego. Una ronda no se puede guardar: si sales, termina.",
		"▶  Continue": "▶  Continuar",
		"▶  Play": "▶  Jugar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"🐦 Bird Hop": "🐦 Pájaro saltarín",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
