extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Hard": "Difícil",
		"It's a tie! %d - %d": "¡Empate! %d - %d",
		"Mancala": "Mancala",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Player %d goes again!": "¡El jugador %d juega otra vez!",
		"Player %d wins! %d - %d": "¡Gana el jugador %d! %d - %d",
		"Player %d's turn": "Turno del jugador %d",
		"Player %d, %s": "Jugador %d, %s",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"bottom row": "fila de abajo",
		"top row": "fila de arriba",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
