extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Collect more seeds in your store than your opponent.": "Junta más semillas en tu depósito que tu rival.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Hard": "Difícil",
		"If your last seed lands in an empty pit on your side, you capture it and every seed in the pit directly opposite.": "Si tu última semilla cae en un hoyo vacío de tu lado, la capturas junto con todas las semillas del hoyo de enfrente.",
		"If your last seed lands in your store, you get another turn.": "Si tu última semilla cae en tu depósito, juegas otra vez.",
		"It's a tie! %d - %d": "¡Empate! %d - %d",
		"Look for a pit whose seed count reaches your store exactly — a free extra turn.": "Busca un hoyo cuyas semillas lleguen justo a tu depósito — un turno extra gratis.",
		"Mancala": "Mancala",
		"Medium": "Medio",
		"On your turn, tap one of your pits. Its seeds are sown one at a time into the following pits, counter-clockwise, including your own store but never your opponent's.": "En tu turno, toca uno de tus hoyos. Sus semillas se siembran de a una en los hoyos siguientes, en sentido antihorario, incluido tu depósito pero nunca el del rival.",
		"Online draws": "Empates en línea",
		"Online losses": "Derrotas en línea",
		"Online wins": "Victorias en línea",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pause": "Pausa",
		"Paused": "En pausa",
		"Pits close to your store are best for extra turns; use them first.": "Los hoyos cerca de tu depósito son los mejores para turnos extra; úsalos primero.",
		"Play Again": "Jugar de nuevo",
		"Player %d goes again!": "¡El jugador %d juega otra vez!",
		"Player %d wins! %d - %d": "¡Gana el jugador %d! %d - %d",
		"Player %d's turn": "Turno del jugador %d",
		"Player %d, %s": "Jugador %d, %s",
		"Player 1 wins": "Victorias del jugador 1",
		"Player 2 wins": "Victorias del jugador 2",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Tap 🌐 Play Online to play a friend on another phone with a room code.": "Toca 🌐 Jugar en línea para jugar con un amigo en otro teléfono usando un código de sala.",
		"The game ends when one side is empty; the other player collects their remaining seeds.": "El juego termina cuando un lado queda vacío; el otro jugador se lleva las semillas que le quedan.",
		"Two players share the phone. Player 1 owns the bottom row of pits and the store on the right; Player 2 the top row and the store on the left.": "Dos jugadores comparten el teléfono. El jugador 1 tiene la fila de hoyos de abajo y el depósito de la derecha; el jugador 2, la fila de arriba y el depósito de la izquierda.",
		"Watch for captures — yours and your opponent's. Keep an eye on your empty pits.": "Atento a las capturas — las tuyas y las del rival. Vigila tus hoyos vacíos.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"bottom row": "fila de abajo",
		"top row": "fila de arriba",
		"🌐 Play Online": "🌐 Jugar en línea",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
