extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d suits": "%d palos",
		"1 suit": "1 palo",
		"2 suits": "2 palos",
		"4 suits": "4 palos",
		"A complete King-to-Ace run in one suit is removed from the table.": "Una escalera completa de Rey a As de un mismo palo se retira de la mesa.",
		"Back to Hub": "Volver al inicio",
		"Before dealing, tidy up as much as you can: the new row covers everything.": "Antes de repartir, ordena todo lo que puedas: la nueva fila lo tapa todo.",
		"Best time (%s)": "Mejor tiempo (%s)",
		"Build eight complete runs from King down to Ace in the same suit to clear the table.": "Arma ocho escaleras completas de Rey a As del mismo palo para limpiar la mesa.",
		"Build in the same suit whenever you can: mixed runs can't be moved as one.": "Construye en el mismo palo siempre que puedas: las escaleras mezcladas no se mueven juntas.",
		"Choose 1, 2 or 4 suits for a new game — more suits is much harder.": "Elige 1, 2 o 4 palos para una partida nueva — más palos es mucho más difícil.",
		"Cleared in %d moves!": "¡Resuelto en %d movimientos!",
		"Easy": "Fácil",
		"Empty columns are gold — use them to reorganise runs.": "Las columnas vacías valen oro — úsalas para reordenar escaleras.",
		"Expert": "Experto",
		"Fill every empty column before dealing.": "Llena todas las columnas vacías antes de repartir.",
		"Games won": "Partidas ganadas",
		"Games won (%s)": "Partidas ganadas (%s)",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Moves: %d   Runs: %d/8   Deals left: %d": "Movimientos: %d   Escaleras: %d/8   Repartos: %d",
		"New": "Nuevo",
		"New best!": "¡Nuevo récord!",
		"Only a run of cards in the same suit can be moved together.": "Solo se pueden mover juntas las escaleras del mismo palo.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Spider": "Solitario Spider",
		"Start with 1 suit to learn the game.": "Empieza con 1 palo para aprender el juego.",
		"Suits: %d (new game)": "Palos: %d (nueva partida)",
		"Tap a card to move it (with the cards below it) to the best spot.": "Toca una carta para moverla (con las cartas de debajo) al mejor lugar.",
		"Tap the stock (top left) to deal one new card onto every column. Every column needs at least one card first.": "Toca el mazo (arriba a la izquierda) para repartir una carta nueva en cada columna. Antes, cada columna debe tener al menos una carta.",
		"Time: %d:%02d": "Tiempo: %d:%02d",
		"You Win!": "¡Ganaste!",
		"You can put any card on a card one rank higher, whatever its suit.": "Puedes poner cualquier carta sobre otra un número más alta, sin importar el palo.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"🕷️ Spider": "🕷️ Spider",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
