extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Computer is thinking...": "La computadora está pensando...",
		"Computer: Hard": "Computadora: difícil",
		"Computer: Normal": "Computadora: normal",
		"Draw — no mills for too long.": "Empate — demasiado tiempo sin molinos.",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"Mill! Tap a black piece to remove it.": "¡Molino! Toca una ficha negra para quitarla.",
		"Only 3 left: you can fly anywhere!": "Te quedan 3: ¡puedes volar a cualquier punto!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Select a piece, then an empty neighbour.": "Elige una ficha y luego un punto vecino vacío.",
		"Tap a point to place a piece.": "Toca un punto para poner una ficha.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %d to place, %d on board   ·   CPU: %d to place, %d on board": "Tú: %d por poner, %d en juego   ·   CPU: %d por poner, %d en juego",
		"Your turn (%s)": "Tu turno (%s)",
		"✳️ Nine Men's Morris": "✳️ Molino",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
