extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Aim for two mills that share a point: you can open and close one every turn.": "Busca dos molinos que compartan un punto: puedes abrir y cerrar uno en cada turno.",
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"Block the computer whenever it has two in a row with the third point empty.": "Bloquea a la computadora cuando tenga dos en línea con el tercer punto vacío.",
		"Choose Normal or Hard for the computer.": "Elige normal o difícil para la computadora.",
		"Computer is thinking...": "La computadora está pensando...",
		"Computer: Hard": "Computadora: difícil",
		"Computer: Normal": "Computadora: normal",
		"Don't place all your pieces on the outside — middle points connect to more lines.": "No pongas todas tus fichas afuera — los puntos del medio conectan con más líneas.",
		"Draw — no mills for too long.": "Empate — demasiado tiempo sin molinos.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"First, take turns placing your 9 pieces on empty points.": "Primero, pongan por turnos sus 9 fichas en puntos vacíos.",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Mill! Tap a black piece to remove it.": "¡Molino! Toca una ficha negra para quitarla.",
		"Nine Men's Morris": "Molino",
		"Once you're down to three pieces you can fly — move to any empty point.": "Cuando te queden tres fichas puedes volar — moverte a cualquier punto vacío.",
		"Only 3 left: you can fly anywhere!": "Te quedan 3: ¡puedes volar a cualquier punto!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Select a piece, then an empty neighbour.": "Elige una ficha y luego un punto vecino vacío.",
		"Take your opponent down to two pieces, or leave them with no move. You play against the computer.": "Deja a tu rival con dos fichas o sin movimientos. Juegas contra la computadora.",
		"Tap a point to place a piece.": "Toca un punto para poner una ficha.",
		"Then take turns moving a piece along a line to a neighbouring empty point.": "Luego, por turnos, muevan una ficha por una línea hasta un punto vecino vacío.",
		"Three of your pieces in a row along a line is a mill: remove one of the computer's pieces. Pieces in a mill are safe unless there's nothing else to take.": "Tres fichas tuyas en línea forman un molino: quita una ficha de la computadora. Las fichas en un molino están a salvo, salvo que no haya otras para quitar.",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %d to place, %d on board   ·   CPU: %d to place, %d on board": "Tú: %d por poner, %d en juego   ·   CPU: %d por poner, %d en juego",
		"Your turn (%s)": "Tu turno (%s)",
		"✳️ Nine Men's Morris": "✳️ Molino",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
