extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A complete row disappears and everything above it falls down.": "Una fila completa desaparece y todo lo de arriba cae.",
		"Avoid covering up holes: a gap under a block is hard to fill later.": "Evita tapar huecos: un espacio debajo de un bloque es difícil de llenar después.",
		"Back to Hub": "Volver al inicio",
		"Before starting, pick a Difficulty (Easy is slower, Hard starts at level 5) and a Board: Big and Huge wells make the pieces smaller, with more room to fit them.": "Antes de empezar, elige una Dificultad (Fácil es más lento, Difícil empieza en el nivel 5) y un Tablero: Grande y Enorme hacen las piezas más pequeñas, con más espacio para acomodarlas.",
		"Best": "Récord",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Big": "Grande",
		"Block Drop": "Bloques",
		"Board": "Tablero",
		"Check the Next box to plan where the following piece will go.": "Mira el cuadro Siguiente para planear dónde irá la próxima pieza.",
		"Classic": "Clásico",
		"Clearing 1, 2, 3 or 4 rows at once scores 100, 300, 500 or 800 points, times the level.": "Borrar 1, 2, 3 o 4 filas a la vez da 100, 300, 500 u 800 puntos, multiplicados por el nivel.",
		"Difficulty": "Dificultad",
		"Drag sideways to move the piece, tap to rotate it, and flick down to drop it.": "Arrastra hacia los lados para mover la pieza, toca para girarla y desliza rápido hacia abajo para soltarla.",
		"Dropping fast earns a few bonus points.": "Soltar rápido da algunos puntos extra.",
		"Easy": "Fácil",
		"Every 10 rows the level goes up and pieces fall faster.": "Cada 10 filas sube el nivel y las piezas caen más rápido.",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Fill whole rows to clear them. Tap to rotate, drag to move, flick down to drop.": "Completa filas para borrarlas. Toca para girar, arrastra para mover, desliza hacia abajo para soltar.",
		"Fit the falling pieces together to fill complete rows. Keep going as long as you can!": "Encaja las piezas que caen para completar filas. ¡Aguanta todo lo que puedas!",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Huge": "Enorme",
		"Keep the surface flat and leave one column open at the side for the long piece — four rows at once scores the most.": "Mantén la superficie pareja y deja una columna libre a un lado para la pieza larga — cuatro filas a la vez dan más puntos.",
		"Level": "Nivel",
		"Lines": "Líneas",
		"Medium": "Medio",
		"Most lines": "Más filas",
		"Next": "Siguiente",
		"Normal": "Normal",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Score": "Puntos",
		"Score: %d": "Puntos: %d",
		"Start": "Empezar",
		"The game ends when the pieces stack up to the top.": "El juego termina cuando las piezas se apilan hasta arriba.",
		"The ↺ and ↻ buttons turn the piece left or right.": "Los botones ↺ y ↻ giran la pieza a la izquierda o a la derecha.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🧱 Block Drop": "🧱 Bloques",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
