extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Chase the lights down: for each lit square, tap the square just below it, one row at a time. Then look at what's left in the bottom row.": "Persigue las luces hacia abajo: por cada casilla encendida, toca la de justo debajo, fila por fila. Luego fíjate qué queda en la última fila.",
		"Easy": "Fácil",
		"Every puzzle can be solved.": "Todos los puzzles tienen solución.",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Lights Out": "Lights Out",
		"Lit squares turn off and dark ones turn on.": "Las casillas encendidas se apagan y las apagadas se encienden.",
		"Medium": "Medio",
		"Moves: %d": "Movimientos: %d",
		"New best!": "¡Nuevo récord!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Puzzles solved": "Puzzles resueltos",
		"Restart": "Reiniciar",
		"Solved in %d moves!": "¡Resuelto en %d movimientos!",
		"Solved!": "¡Resuelto!",
		"Switch off every light on the board.": "Apaga todas las luces del tablero.",
		"Tapping a square toggles it and the squares directly above, below, left and right of it.": "Tocar una casilla la cambia a ella y a las casillas de arriba, abajo, izquierda y derecha.",
		"The order of your taps doesn't matter, and tapping a square twice undoes it — so each square only ever needs one tap or none.": "El orden de tus toques no importa, y tocar dos veces una casilla lo deshace — así que cada casilla necesita un toque o ninguno.",
		"Try to solve it in as few moves as you can.": "Intenta resolverlo en la menor cantidad de movimientos.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"💡 Lights Out": "💡 Lights Out",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
