extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"%d of %d unlocked": "%d de %d desbloqueados",
		"5 × 5 lights": "5 × 5 luces",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Chase the lights down: for each lit square, tap the square just below it, one row at a time. Then look at what's left in the bottom row.": "Persigue las luces hacia abajo: por cada casilla encendida, toca la de justo debajo, fila por fila. Luego fíjate qué queda en la última fila.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Every puzzle can be solved. Leave any time: ⏸ saves the puzzle and Resume on the Home screen picks it up.": "Todos los tableros tienen solución. Sal cuando quieras: ⏸ guarda el tablero y Continuar en la pantalla de inicio lo retoma.",
		"Expert": "Experto",
		"Fewest moves": "Menos movimientos",
		"Hard": "Difícil",
		"Host a game and invite a friend": "Crea una partida e invita a un amigo",
		"Light Flip": "Apagón",
		"Lit squares turn off and dark ones turn on.": "Las casillas encendidas se apagan y las apagadas se encienden.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Moves: %d": "Movimientos: %d",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No friends on this board yet.": "Aún no hay amigos en esta tabla.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Puzzles solved": "Puzzles resueltos",
		"Puzzles solved, all time.": "Tableros resueltos en total.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solved in %d moves!": "¡Resuelto en %d movimientos!",
		"Solved!": "¡Resuelto!",
		"Switch off every light on the board.": "Apaga todas las luces del tablero.",
		"Tap to flip a light and its neighbours. Turn them all off.": "Toca para cambiar una luz y sus vecinas. Apágalas todas.",
		"Tapping a square toggles it and the squares directly above, below, left and right of it.": "Tocar una casilla la cambia a ella y a las casillas de arriba, abajo, izquierda y derecha.",
		"The order of your taps doesn't matter, and tapping a square twice undoes it — so each square only ever needs one tap or none.": "El orden de tus toques no importa, y tocar dos veces una casilla lo deshace — así que cada casilla necesita un toque o ninguno.",
		"Try to solve it in as few moves as you can.": "Intenta resolverlo en la menor cantidad de movimientos.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"▶  Continue": "▶  Continuar",
		"▶  New puzzle": "▶  Nuevo tablero",
		"❓ How to Play": "❓ Cómo jugar",
		"🌍 Everyone": "🌍 Todos",
		"🎯 Goal": "🎯 Objetivo",
		"🏅 Achievements": "🏅 Logros",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"👥 Friends": "👥 Amigos",
		"💡 Light Flip": "💡 Apagón",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"📨 Invite a friend": "📨 Invitar a un amigo",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
