extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"After a hit, try the squares above, below, left and right to find which way the ship runs.": "Después de un impacto, prueba las casillas de arriba, abajo, izquierda y derecha para ver hacia dónde va el barco.",
		"Back to Hub": "Volver al inicio",
		"Best streak": "Mejor racha",
		"Both fleets have five ships: 5, 4, 3, 3 and 2 squares long. Ships never touch, not even at the corners.": "Cada flota tiene cinco barcos de 5, 4, 3, 3 y 2 casillas. Los barcos nunca se tocan, ni siquiera en las esquinas.",
		"Defeat. Your fleet is sunk.": "Derrota. Hundieron tu flota.",
		"Easy": "Fácil",
		"Enemy ships left: %d": "Barcos enemigos: %d",
		"Expert": "Experto",
		"Fire in a checkerboard pattern — every ship covers at least two squares, so you can't miss one.": "Dispara en patrón de tablero de ajedrez — cada barco ocupa al menos dos casillas, así no se te escapa ninguno.",
		"Hard": "Difícil",
		"Hit! Fire again.": "¡Tocado! Dispara otra vez.",
		"Hub": "Inicio",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"Miss. The enemy is aiming...": "Agua. El enemigo apunta...",
		"Once a ship is sunk, skip the squares around it — ships never touch.": "Cuando hundas un barco, sáltate las casillas de alrededor — los barcos nunca se tocan.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Sea Battle": "Batalla naval",
		"Sink the computer's whole fleet before it sinks yours.": "Hunde toda la flota de la computadora antes de que hunda la tuya.",
		"Tap a square in the enemy waters to fire. A hit, or sinking a ship, lets you fire again.": "Toca una casilla en aguas enemigas para disparar. Si das en el blanco o hundes un barco, vuelves a disparar.",
		"Tap the enemy waters to fire!": "¡Toca el agua enemiga para disparar!",
		"Tap 🔀 Shuffle to rearrange your ships before the first shot.": "Toca 🔀 Mezclar para reacomodar tus barcos antes del primer disparo.",
		"The first to sink every enemy ship wins.": "Gana el primero en hundir todos los barcos enemigos.",
		"They missed. Your turn!": "Fallaron. ¡Tu turno!",
		"They sank your ship!": "¡Hundieron tu barco!",
		"Victory! Their fleet is sunk.": "¡Victoria! Hundiste su flota.",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You sank a ship! Fire again.": "¡Hundiste un barco! Dispara otra vez.",
		"You win!": "¡Ganaste!",
		"You've been hit!": "¡Te dieron!",
		"Your fleet": "Tu flota",
		"Your ships left: %d": "Tus barcos: %d",
		"Your turn (%s)": "Tu turno (%s)",
		"🔀 Shuffle": "🔀 Mezclar",
		"🚢 Sea Battle": "🚢 Batalla naval",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
