extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A sum appears. Tap the right answer from the four choices.": "Aparece una operación. Toca la respuesta correcta entre las cuatro opciones.",
		"A wrong answer breaks your streak and costs you 3 seconds.": "Una respuesta incorrecta rompe tu racha y te cuesta 3 segundos.",
		"A wrong answer costs 3 seconds, about the time of a fast right one, so guessing blindly rarely pays.": "Una respuesta incorrecta cuesta 3 segundos, casi lo que tardas en acertar una rápida, así que adivinar a ciegas casi nunca conviene.",
		"Answer as many sums as you can in 60 seconds.": "Resuelve cuantas operaciones puedas en 60 segundos.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Best streak: %d": "Mejor racha: %d",
		"Best: %d": "Mejor: %d",
		"Don't chase exact digits: check the last digit first, it often rules out two choices.": "No calcules todo: mira primero la última cifra, a menudo descarta dos opciones.",
		"Easy": "Fácil",
		"Every right answer scores a point. Every 5 points the questions get harder: bigger numbers, times tables, division and brackets.": "Cada respuesta correcta vale un punto. Cada 5 puntos las preguntas se hacen más difíciles: números más grandes, tablas de multiplicar, divisiones y paréntesis.",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"How many sums can you solve in 60 seconds?": "¿Cuántas operaciones puedes resolver en 60 segundos?",
		"Hub": "Inicio",
		"Level %d": "Nivel %d",
		"Medium": "Medio",
		"New best!": "¡Nuevo récord!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Quick Math": "Cálculo rápido",
		"Score: %d": "Puntos: %d",
		"Start": "Empezar",
		"Time's up!": "¡Se acabó el tiempo!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"➕ Quick Math": "➕ Cálculo rápido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
