extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"A sum appears. Tap the right answer from the four choices.": "Aparece una operación. Toca la respuesta correcta entre las cuatro opciones.",
		"A wrong answer breaks your streak and costs you 3 seconds.": "Una respuesta incorrecta rompe tu racha y te cuesta 3 segundos.",
		"A wrong answer costs 3 seconds, about the time of a fast right one, so guessing blindly rarely pays.": "Una respuesta incorrecta cuesta 3 segundos, casi lo que tardas en acertar una rápida, así que adivinar a ciegas casi nunca conviene.",
		"Answer as many sums as you can in 60 seconds.": "Resuelve cuantas operaciones puedas en 60 segundos.",
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Best streak: %d": "Mejor racha: %d",
		"Best: %d": "Mejor: %d",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't chase exact digits: check the last digit first, it often rules out two choices.": "No calcules todo: mira primero la última cifra, a menudo descarta dos opciones.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Every right answer scores a point. Every 5 points the questions get harder: bigger numbers, times tables, division and brackets.": "Cada respuesta correcta vale un punto. Cada 5 puntos las preguntas se hacen más difíciles: números más grandes, tablas de multiplicar, divisiones y paréntesis.",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Hard": "Difícil",
		"How many sums can you solve in 60 seconds?": "¿Cuántas operaciones puedes resolver en 60 segundos?",
		"Level %d": "Nivel %d",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New best!": "¡Nuevo récord!",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Quick Math": "Cálculo rápido",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start": "Empezar",
		"Time's up!": "¡Se acabó el tiempo!",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"➕ Quick Math": "➕ Cálculo rápido",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
