extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"4 rounds, each player draws one card per round.\nGuess right, give a drink. Guess wrong, take a drink.\nRound 1: Red/Black (1) · 2: Higher/Lower (2)\n3: Inside/Outside (3) · 4: Suit (4)": "4 rondas, cada jugador saca una carta por ronda.\nSi aciertas, das un trago. Si fallas, tomas.\nRonda 1: Rojo/Negro (1) · 2: Mayor/Menor (2)\n3: Adentro/Afuera (3) · 4: Palo (4)",
		"A party card game: guess right to hand out drinks, guess wrong to take them.": "Un juego de cartas para fiestas: si aciertas repartes tragos, si fallas te los tomas.",
		"Any drink works — water and soda count too. Know your limits and play responsibly.": "Vale cualquier bebida — agua y refresco también. Conoce tus límites y juega con responsabilidad.",
		"Back to Hub": "Volver al inicio",
		"Black": "Negras",
		"Cards played": "Cartas jugadas",
		"Choose how many players, then pass the phone around. Each player gets four guesses, one per round.": "Elige cuántos juegan y pásense el teléfono. Cada jugador adivina cuatro veces, una por ronda.",
		"Correct: give %d  ·  Wrong: take %d": "Acierto: das %d  ·  Error: tomas %d",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Games played": "Partidas jugadas",
		"Guess the Suit": "Adivina el palo",
		"Hard": "Difícil",
		"Higher": "Mayor",
		"Higher or Lower": "Mayor o menor",
		"How many players?": "¿Cuántos jugadores?",
		"Hub": "Inicio",
		"In round 2, go higher when your first card is low and lower when it's high.": "En la ronda 2, di mayor cuando tu primera carta sea baja y menor cuando sea alta.",
		"In round 3, the wider the gap between your first two cards, the better inside looks.": "En la ronda 3, cuanto más separadas estén tus dos primeras cartas, mejor pinta adentro.",
		"Inside": "Adentro",
		"Inside or Outside": "Adentro o afuera",
		"Left in deck: %d red · %d black": "Quedan en el mazo: %d rojas · %d negras",
		"Lower": "Menor",
		"Medium": "Medio",
		"New Game": "Nueva partida",
		"Next Player ➜": "Siguiente jugador ➜",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Outside": "Afuera",
		"Player %d's turn": "Turno del jugador %d",
		"ROUND %d: %s": "RONDA %d: %s",
		"Red": "Rojo",
		"Red or Black": "Rojo o negro",
		"Right guesses": "Aciertos",
		"Right guesses let you give drinks away; wrong ones mean you drink. Later rounds are worth more.": "Si aciertas, repartes tragos; si fallas, bebes tú. Las últimas rondas valen más.",
		"Round 1: red or black? Round 2: higher or lower than your first card?": "Ronda 1: ¿rojo o negro? Ronda 2: ¿mayor o menor que tu primera carta?",
		"Round 3: inside or outside your first two cards? (A tie counts as outside.) Round 4: guess the suit.": "Ronda 3: ¿adentro o afuera de tus dos primeras cartas? (Un empate cuenta como afuera.) Ronda 4: adivina el palo.",
		"See Results ➜": "Ver resultados ➜",
		"Start Game": "Empezar partida",
		"Wrong guesses": "Fallos",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"✅ Correct! Give %d away.": "✅ ¡Correcto! Reparte %d.",
		"❌ Wrong! Drink %d.": "❌ ¡Fallaste! Toma %d.",
		"🂡 Red or Black": "🂡 Rojo o negro",
		"🍻 Game Over!": "🍻 ¡Fin del juego!",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
