extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best: %d": "Mejor: %d",
		"Easy": "Fácil",
		"Exit to Hub": "Salir al inicio",
		"Expert": "Experto",
		"Game Over": "Fin del juego",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Level %d   Score: %d   Lives: %s   Best: %d": "Nivel %d   Puntos: %d   Vidas: %s   Récord: %d",
		"Medium": "Medio",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Start": "Empezar",
		"Swipe to hop. Dodge the cars, ride the logs, and fill all five homes!": "Desliza para saltar. Esquiva los autos, súbete a los troncos y llena las cinco casitas.",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"🐸 Frog Crossing": "🐸 Cruza la rana",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
