extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Best score": "Mejor puntaje",
		"Best: %d": "Mejor: %d",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Each life has 30 seconds. Getting hit, falling in or running out of time costs a life.": "Cada vida tiene 30 segundos. Si te atropellan, caes al agua o se acaba el tiempo, pierdes una vida.",
		"Easy": "Fácil",
		"Every new row you reach is 10 points; a home is worth 50 plus a bonus for the time left.": "Cada fila nueva que alcanzas vale 10 puntos; una casa vale 50 más un bono por el tiempo restante.",
		"Expert": "Experto",
		"Fill all five homes to reach the next, faster level. You have three lives.": "Llena las cinco casas para pasar al siguiente nivel, más rápido. Tienes tres vidas.",
		"Frog Crossing": "Cruza la rana",
		"Game Over": "Fin del juego",
		"Games played": "Partidas jugadas",
		"Get your frog across the road and the river into all five homes at the top.": "Lleva a tu rana a través de la calle y el río hasta las cinco casas de arriba.",
		"Hard": "Difícil",
		"Highest level": "Nivel más alto",
		"Hop across the road and the river into all five homes.": "Cruza la carretera y el río hasta llenar las cinco casitas.",
		"Level %d   Score: %d   Lives: %s   Best: %d": "Nivel %d   Puntos: %d   Vidas: %s   Récord: %d",
		"Loading...": "Cargando...",
		"Logs carry you sideways — don't ride one off the edge of the screen.": "Los troncos te llevan de costado — no te dejes sacar por el borde de la pantalla.",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"On the road, dodge the cars. On the river, ride the logs — the water is deadly.": "En la calle, esquiva los autos. En el río, súbete a los troncos — el agua es mortal.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Score: %d": "Puntos: %d",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Start": "Empezar",
		"Swipe (or use the arrow keys) to hop one square up, down, left or right.": "Desliza (o usa las flechas) para saltar una casilla arriba, abajo, a la izquierda o a la derecha.",
		"Swipe to hop. Dodge the cars, ride the logs, and land on all five glowing lily pads at the top!": "Desliza para saltar. Esquiva los autos, súbete a los troncos y llega a los cinco nenúfares brillantes de arriba.",
		"Three lives": "Tres vidas",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Wait on the grass strip in the middle to time the river.": "Espera en el pasto del medio para calcular el momento de cruzar el río.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your best score.": "Tu mejor puntaje.",
		"Your turn (%s)": "Tu turno (%s)",
		"↺  Restart": "↺  Reiniciar",
		"⏸ pauses the game. A round can't be saved for later: leaving it ends it.": "⏸ pausa el juego. Una ronda no se puede guardar: si sales, termina.",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"🐸  Play": "🐸  Jugar",
		"🐸 Frog Crossing": "🐸 Cruza la rana",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
