extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Aces are 1, Jacks 11, Queens 12. Kings are 13 on their own — tap one to remove it.": "Los Ases valen 1, las J 11 y las Q 12. Los Reyes valen 13 solos — tócalos para quitarlos.",
		"Back to Hub": "Volver al inicio",
		"Before pairing, check which pair uncovers more cards.": "Antes de emparejar, fíjate qué pareja destapa más cartas.",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Clear all 28 cards from the pyramid.": "Quita las 28 cartas de la pirámide.",
		"Close": "Cerrar",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"Multiplayer": "Multijugador",
		"New": "Nuevo",
		"No moves left.": "No quedan movimientos.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Pairs that add to 13 · J=11 Q=12 K=13\nPass %d of %d · %d left in the pyramid": "Parejas que suman 13 · J=11 Q=12 K=13\nPasada %d de %d · quedan %d en la pirámide",
		"Paused": "En pausa",
		"Plan for cards you'll need later: remember what's still in the stock.": "Piensa en las cartas que necesitarás después: recuerda qué queda en el mazo.",
		"Play": "Jugar",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Pyramid": "Solitario Pirámide",
		"Remove Kings as soon as they're uncovered — they don't need a partner.": "Quita los Reyes apenas queden libres — no necesitan pareja.",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Single player": "Un jugador",
		"Solitaire": "Solitario",
		"Stock: %d": "Mazo: %d",
		"Tap the stock to turn over a card onto the waste pile. The top waste card can pair too.": "Toca el mazo para dar vuelta una carta en la pila de descarte. La carta de arriba del descarte también puede emparejarse.",
		"Tap two uncovered cards that add up to 13 to remove them. A card is uncovered when no card overlaps it from below.": "Toca dos cartas libres que sumen 13 para quitarlas. Una carta está libre cuando ninguna carta de abajo la tapa.",
		"Update the app to keep statistics.": "Actualiza la app para guardar estadísticas.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You can go through the stock three times. The game ends when no pairs are left.": "Puedes pasar por el mazo tres veces. El juego termina cuando no quedan parejas.",
		"You cleared the pyramid!": "¡Limpiaste la pirámide!",
		"You lose!": "¡Perdiste!",
		"You win!": "¡Ganaste!",
		"You: %s": "Tú: %s",
		"Your turn (%s)": "Tu turno (%s)",
		"↶ Undo": "↶ Deshacer",
		"↺  Restart": "↺  Reiniciar",
		"▶  Continue": "▶  Continuar",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🏆 Leaderboard": "🏆 Clasificación",
		"🏠 %s Home": "🏠 Inicio de %s",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
		"🔺 Pyramid": "🔺 Pirámide",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
