extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"2 Players": "2 jugadores",
		"A checker on the bar must come back in before you move anything else.": "Una ficha en la barra debe volver a entrar antes de que muevas cualquier otra.",
		"Back to Hub": "Volver al inicio",
		"Backgammon": "Backgammon",
		"Best score": "Mejor puntaje",
		"Best streak": "Mejor racha",
		"Black wins": "Victorias de las negras",
		"Build points (two or more checkers) in a row to block the enemy's path.": "Arma puntos seguidos (dos o más fichas) para bloquear el camino del rival.",
		"Close": "Cerrar",
		"Computer rolled %d and %d.": "La computadora sacó %d y %d.",
		"Computer rolled double %d!": "¡La computadora sacó doble %d!",
		"Computer's turn...": "Turno de la computadora...",
		"Couldn't load the leaderboard. Check your connection and try again.": "No se pudo cargar la clasificación. Revisa tu conexión e inténtalo de nuevo.",
		"Don't leave single checkers where the computer can hit them — stack them in pairs.": "No dejes fichas solas donde la computadora pueda golpearlas — agrúpalas de a dos.",
		"Draws": "Empates",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Gammons won": "Gammons ganados",
		"Hard": "Difícil",
		"Hitting a blot costs your opponent a lot of ground — take the chance when it's safe.": "Golpear una ficha sola le hace perder mucho terreno a tu rival — aprovecha cuando sea seguro.",
		"Loading...": "Cargando...",
		"Losses": "Derrotas",
		"Medium": "Medio",
		"More": "Más",
		"No legal moves — turn passes.": "No hay movimientos — pasa el turno.",
		"No moves.": "Sin movimientos.",
		"No scores yet — be the first!": "Aún no hay puntajes — ¡sé el primero!",
		"Once all your checkers are home, bear them off into the tray below. If the loser hasn't borne off any, it's a gammon (2×); with a checker still in the winner's home or on the bar, a backgammon (3×).": "Cuando todas tus fichas estén en casa, sácalas a la bandeja de abajo. Si el perdedor no sacó ninguna, es un gammon (2×); si además le queda una ficha en la casa del ganador o en la barra, un backgammon (3×).",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Paused": "En pausa",
		"Play Again": "Jugar de nuevo",
		"Play a game and your records will show up here.": "Juega una partida y aquí aparecerán tus récords.",
		"Player": "Jugador",
		"Resume": "Continuar",
		"Sign in (hub ⚙ Options) to put your best score on the board.": "Inicia sesión (⚙ Opciones en el menú) para poner tu mejor puntaje en la tabla.",
		"Tap a white checker to move it.": "Toca una ficha blanca para moverla.",
		"Tap here to bear off": "Toca aquí para sacar",
		"Tap 🎲 Roll, then tap a checker and a highlighted point to move it by one of the dice. Doubles let you move four times.": "Toca 🎲 Tirar y luego una ficha y un punto resaltado para moverla según uno de los dados. Con dobles mueves cuatro veces.",
		"The computer wins %s.": "La computadora gana %s.",
		"Update the app to see the leaderboards.": "Actualiza la app para ver las clasificaciones.",
		"When you're far ahead, just race home.": "Cuando vas muy adelante, solo corre a casa.",
		"White wins": "Victorias de las blancas",
		"Win rate": "Porcentaje de victorias",
		"Wins": "Victorias",
		"You can't land on a point with two or more enemy checkers. Land on a single one (a blot) to hit it and send it to the bar.": "No puedes caer en un punto con dos o más fichas rivales. Si caes en una ficha sola, la golpeas y la mandas a la barra.",
		"You lose!": "¡Perdiste!",
		"You must use both dice if you can. ↶ Undo takes back moves this turn.": "Debes usar los dos dados si puedes. ↶ Deshacer anula movimientos de este turno.",
		"You win %s!": "¡Ganas %s!",
		"You win!": "¡Ganaste!",
		"Your checkers travel up the left side, across the top and down the right side into your home board (bottom right).": "Tus fichas suben por el lado izquierdo, cruzan por arriba y bajan por el derecho hasta tu casa (abajo a la derecha).",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn — roll the dice.": "Tu turno — tira los dados.",
		"a backgammon": "un backgammon",
		"a gammon": "un gammon",
		"a single game": "una partida simple",
		"vs Computer": "vs Computadora",
		"↶ Undo": "↶ Deshacer",
		"❓ How to Play": "❓ Cómo jugar",
		"🎯 Goal": "🎯 Objetivo",
		"🎲 Backgammon": "🎲 Backgammon",
		"🎲 Roll": "🎲 Tirar",
		"🏆 Leaderboard": "🏆 Clasificación",
		"💡 Tips": "💡 Consejos",
		"📊 Statistics": "📊 Estadísticas",
		"📋 How to Play": "📋 Cómo jugar",
		"🔊 Sound": "🔊 Sonido",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
