extends RefCounted

## Generated by `python tools/hub.py i18n` from tools/i18n/es.json -- edit there.

const STRINGS := {
	"es": {
		"Back to Hub": "Volver al inicio",
		"Computer rolled %d and %d.": "La computadora sacó %d y %d.",
		"Computer rolled double %d!": "¡La computadora sacó doble %d!",
		"Computer's turn...": "Turno de la computadora...",
		"Easy": "Fácil",
		"Expert": "Experto",
		"Hard": "Difícil",
		"Hub": "Inicio",
		"Medium": "Medio",
		"No legal moves — turn passes.": "No hay movimientos — pasa el turno.",
		"No moves.": "Sin movimientos.",
		"Opponent disconnected — waiting...": "Tu rival se desconectó — esperando...",
		"Opponent's turn (%s)": "Turno del rival (%s)",
		"Play Again": "Jugar de nuevo",
		"Restart": "Reiniciar",
		"Tap a white checker to move it.": "Toca una ficha blanca para moverla.",
		"Tap here to bear off": "Toca aquí para sacar",
		"The computer wins %s.": "La computadora gana %s.",
		"You lose!": "¡Perdiste!",
		"You win %s!": "¡Ganas %s!",
		"You win!": "¡Ganaste!",
		"Your turn (%s)": "Tu turno (%s)",
		"Your turn — roll the dice.": "Tu turno — tira los dados.",
		"a backgammon": "un backgammon",
		"a gammon": "un gammon",
		"a single game": "una partida simple",
		"↶ Undo": "↶ Deshacer",
		"🎲 Backgammon": "🎲 Backgammon",
		"🎲 Roll": "🎲 Tirar",
	},
}

## Adds these translations for as long as `owner` (the game scene) lives.
## Goes straight to TranslationServer rather than the Lang autoload, so it
## also works on app versions from before Lang existed.
static func install(owner: Node) -> void:
	for locale in STRINGS:
		var t := Translation.new()
		t.locale = locale
		for key in STRINGS[locale]:
			t.add_message(key, STRINGS[locale][key])
		TranslationServer.add_translation(t)
		owner.tree_exiting.connect(TranslationServer.remove_translation.bind(t))
